import csv, sys, os

rows = []

def a(t, p, ps, y, g, dev, alt="", series="", folders=""):
    ts = t.lower().replace("'","")
    if not folders:
        folders = ts.replace(": "," ").replace(":"," ").replace(" & "," and ").replace(" - "," ").replace(", "," ").replace("  "," ").strip()
    rows.append([t, ts, p, ps, str(y), g, dev, alt, series, folders])

def batch_add(games):
    for g in games:
        a(*g)

# ===================== GC/Wii (300 games) =====================
gc_wii_games = [
("Super Smash Bros. Melee","GC","GC",2001,"Fighting","HAL Laboratory","","Super Smash Bros.","super.smash.bros.melee|ssbm"),
("Luigi's Mansion","GC","GC",2001,"Action-Adventure","Nintendo","","Luigi's Mansion","luigis.mansion"),
("Pikmin","GC","GC",2001,"Strategy","Nintendo","","Pikmin","pikmin"),
("Pikmin 2","GC","GC",2004,"Strategy","Nintendo","","Pikmin","pikmin.2"),
("Super Mario Sunshine","GC","GC",2002,"Platformer","Nintendo","","Mario","super.mario.sunshine"),
("The Legend of Zelda: The Wind Waker","GC","GC",2002,"Action-Adventure","Nintendo","Wind Waker","Zelda","legend.of.zelda.wind.waker|wind.waker"),
("The Legend of Zelda: Twilight Princess","GC","GC",2006,"Action-Adventure","Nintendo","TP","Zelda","legend.of.zelda.twilight.princess|tp"),
("Metroid Prime","GC","GC",2002,"FPS","Retro Studios","","Metroid","metroid.prime"),
("Metroid Prime 2: Echoes","GC","GC",2004,"FPS","Retro Studios","","Metroid","metroid.prime.2|echoes"),
("Metroid Prime 3: Corruption","Wii","Wii",2007,"FPS","Retro Studios","","Metroid","metroid.prime.3|corruption"),
("Metroid Prime: Trilogy","Wii","Wii",2009,"Compilation","Retro Studios","","Metroid","metroid.prime.trilogy"),
("Metroid Fusion","GC","GC",2002,"Action-Platformer","Nintendo","","Metroid","metroid.fusion"),
("Metroid: Zero Mission","GC","GC",2004,"Action-Platformer","Nintendo","","Metroid","metroid.zero.mission"),
("Animal Crossing","GC","GC",2001,"Simulation","Nintendo","","Animal Crossing","animal.crossing"),
("Mario Kart: Double Dash!!","GC","GC",2003,"Racing","Nintendo","","Mario Kart","mario.kart.double.dash"),
("F-Zero GX","GC","GC",2003,"Racing","Amusement Vision","","F-Zero","fzero.gx|f.zero.gx"),
("Star Fox Adventures","GC","GC",2002,"Action-Adventure","Rare","","Star Fox","star.fox.adventures"),
("Star Fox: Assault","GC","GC",2005,"Third-Person Shooter","Namco","","Star Fox","star.fox.assault"),
("Donkey Kong Jungle Beat","GC","GC",2004,"Platformer","Nintendo","","Donkey Kong","donkey.kong.jungle.beat"),
("Wario World","GC","GC",2003,"Beat 'em Up","Treasure","","Wario","wario.world"),
("Wario Ware Inc: Mega Party Games","GC","GC",2003,"Party","Nintendo","","Wario Ware","wario.ware.inc"),
("Paper Mario: The Thousand-Year Door","GC","GC",2004,"RPG","Intelligent Systems","","Mario","paper.mario.thousand.year.door"),
("Mario Golf: Toadstool Tour","GC","GC",2003,"Sports","Camelot Software","","Mario","mario.golf.toadstool.tour"),
("Mario Power Tennis","GC","GC",2004,"Sports","Camelot Software","","Mario","mario.power.tennis"),
("Mario Superstar Baseball","GC","GC",2005,"Sports","Namco","","Mario","mario.superstar.baseball"),
("Mario Party 4","GC","GC",2002,"Party","Hudson Soft","","Mario Party","mario.party.4"),
("Mario Party 5","GC","GC",2003,"Party","Hudson Soft","","Mario Party","mario.party.5"),
("Mario Party 6","GC","GC",2004,"Party","Hudson Soft","","Mario Party","mario.party.6"),
("Mario Party 7","GC","GC",2005,"Party","Hudson Soft","","Mario Party","mario.party.7"),
("Kirby Air Ride","GC","GC",2003,"Racing","HAL Laboratory","","Kirby","kirby.air.ride"),
("Viewtiful Joe","GC","GC",2003,"Action","Capcom","","Viewtiful Joe","viewtiful.joe"),
("Viewtiful Joe 2","GC","GC",2004,"Action","Capcom","","Viewtiful Joe","viewtiful.joe.2"),
("Viewtiful Joe: Double Trouble","GC","GC",2005,"Action","Capcom","","Viewtiful Joe","viewtiful.joe.double.trouble"),
("Resident Evil","GC","GC",2002,"Survival Horror","Capcom","RE1 Remake","Resident Evil","resident.evil|re1"),
("Resident Evil Zero","GC","GC",2002,"Survival Horror","Capcom","RE0","Resident Evil","resident.evil.0|re0"),
("Resident Evil 4","GC","GC",2005,"Survival Horror","Capcom","RE4","Resident Evil","resident.evil.4|re4"),
("Eternal Darkness: Sanity's Requiem","GC","GC",2002,"Action-Adventure","Silicon Knights","","Eternal Darkness","eternal.darkness|sanitys.requiem"),
("TimeSplitters 2","GC","GC",2002,"FPS","Free Radical Design","","TimeSplitters","timesplitters.2"),
("TimeSplitters: Future Perfect","GC","GC",2005,"FPS","Free Radical Design","","TimeSplitters","timesplitters.future.perfect"),
("Super Monkey Ball","GC","GC",2001,"Platformer","Amusement Vision","","Super Monkey Ball","super.monkey.ball"),
("Super Monkey Ball 2","GC","GC",2002,"Platformer","Amusement Vision","","Super Monkey Ball","super.monkey.ball.2"),
("Billy Hatcher and the Giant Egg","GC","GC",2003,"Platformer","Sonic Team","","Billy Hatcher","billy.hatcher.and.the.giant.egg"),
("Sonic Adventure 2: Battle","GC","GC",2001,"Platformer","Sonic Team","","Sonic","sonic.adventure.2.battle"),
("Sonic Adventure DX: Director's Cut","GC","GC",2003,"Platformer","Sonic Team","","Sonic","sonic.adventure.dx"),
("Sonic Heroes","GC","GC",2003,"Platformer","Sonic Team","","Sonic","sonic.heroes"),
("Sonic Mega Collection","GC","GC",2002,"Compilation","Sonic Team","","Sonic","sonic.mega.collection"),
("Sonic Gems Collection","GC","GC",2005,"Compilation","Sonic Team","","Sonic","sonic.gems.collection"),
("Shadow the Hedgehog","GC","GC",2005,"Action-Platformer","Sonic Team","","Sonic","shadow.the.hedgehog"),
("The Legend of Zelda: Collector's Edition","GC","GC",2003,"Compilation","Nintendo","","Zelda","zelda.collectors.edition"),
("Baten Kaitos: Eternal Wings and the Lost Ocean","GC","GC",2003,"RPG","Monolith Soft","","Baten Kaitos","baten.kaitos"),
("Baten Kaitos Origins","GC","GC",2006,"RPG","Monolith Soft","","Baten Kaitos","baten.kaitos.origins"),
("Tales of Symphonia","GC","GC",2003,"RPG","Namco","","Tales","tales.of.symphonia"),
("Fire Emblem: Path of Radiance","GC","GC",2005,"Tactical RPG","Intelligent Systems","","Fire Emblem","fire.emblem.path.of.radiance"),
("Skies of Arcadia Legends","GC","GC",2003,"RPG","Overworks","","Skies of Arcadia","skies.of.arcadia.legends"),
("Phantasy Star Online Episode I & II","GC","GC",2002,"RPG","Sonic Team","","Phantasy Star","phantasy.star.online.episode.1.and.2"),
("Phantasy Star Online Episode III: C.A.R.D. Revolution","GC","GC",2003,"RPG","Sonic Team","","Phantasy Star","phantasy.star.online.episode.3"),
("Lost Kingdoms","GC","GC",2002,"Action-RPG","FromSoftware","","Lost Kingdoms","lost.kingdoms"),
("Lost Kingdoms II","GC","GC",2003,"Action-RPG","FromSoftware","","Lost Kingdoms","lost.kingdoms.2"),
("Chibi-Robo!","GC","GC",2005,"Action-Adventure","Skip Ltd.","","Chibi-Robo!","chibi.robo"),
("Pac-Man World 2","GC","GC",2002,"Platformer","Namco","","Pac-Man","pacman.world.2"),
("Pac-Man World Rally","GC","GC",2005,"Racing","Namco","","Pac-Man","pacman.world.rally"),
("WarioWare: Smooth Moves","Wii","Wii",2006,"Party","Nintendo","","Wario Ware","warioware.smooth.moves"),
("Wii Sports","Wii","Wii",2006,"Sports","Nintendo","","Wii Sports","wii.sports"),
("Wii Sports Resort","Wii","Wii",2009,"Sports","Nintendo","","Wii Sports","wii.sports.resort"),
("Wii Play","Wii","Wii",2006,"Party","Nintendo","","Wii Play","wii.play"),
("Wii Fit","Wii","Wii",2007,"Sports","Nintendo","","Wii Fit","wii.fit"),
("Wii Fit Plus","Wii","Wii",2009,"Sports","Nintendo","","Wii Fit","wii.fit.plus"),
("Wii Music","Wii","Wii",2008,"Rhythm","Nintendo","","Wii Music","wii.music"),
("Wii Party","Wii","Wii",2010,"Party","Nintendo","","Wii Party","wii.party"),
("New Super Mario Bros. Wii","Wii","Wii",2009,"Platformer","Nintendo","","Mario","new.super.mario.bros.wii|nsmb.wii"),
("Super Mario Galaxy","Wii","Wii",2007,"Platformer","Nintendo","","Mario","super.mario.galaxy"),
("Super Mario Galaxy 2","Wii","Wii",2010,"Platformer","Nintendo","","Mario","super.mario.galaxy.2"),
("Super Mario All-Stars: 25th Anniversary Edition","Wii","Wii",2010,"Compilation","Nintendo","","Mario","super.mario.all.stars.25th.anniversary"),
("The Legend of Zelda: Twilight Princess","Wii","Wii",2006,"Action-Adventure","Nintendo","","Zelda","legend.of.zelda.twilight.princess"),
("The Legend of Zelda: Skyward Sword","Wii","Wii",2011,"Action-Adventure","Nintendo","","Zelda","legend.of.zelda.skyward.sword"),
("Metroid: Other M","Wii","Wii",2010,"Action-Adventure","Team Ninja","","Metroid","metroid.other.m"),
("Donkey Kong Country Returns","Wii","Wii",2010,"Platformer","Retro Studios","","Donkey Kong","donkey.kong.country.returns"),
("Kirby's Epic Yarn","Wii","Wii",2010,"Platformer","Good-Feel","","Kirby","kirbys.epic.yarn"),
("Kirby's Return to Dream Land","Wii","Wii",2011,"Platformer","HAL Laboratory","","Kirby","kirbys.return.to.dream.land"),
("Wario Land: Shake It!","Wii","Wii",2008,"Platformer","Good-Feel","","Wario","wario.land.shake.it"),
("Super Paper Mario","Wii","Wii",2007,"RPG","Intelligent Systems","","Mario","super.paper.mario"),
("Mario Kart Wii","Wii","Wii",2008,"Racing","Nintendo","","Mario Kart","mario.kart.wii"),
("Mario Party 8","Wii","Wii",2007,"Party","Hudson Soft","","Mario Party","mario.party.8"),
("Mario Party 9","Wii","Wii",2012,"Party","Nd Cube","","Mario Party","mario.party.9"),
("Mario Super Sluggers","Wii","Wii",2008,"Sports","Namco","","Mario","mario.super.sluggers"),
("Mario Strikers Charged","Wii","Wii",2007,"Sports","Next Level Games","","Mario","mario.strikers.charged"),
("Super Smash Bros. Brawl","Wii","Wii",2008,"Fighting","Sora Ltd.","","Super Smash Bros.","super.smash.bros.brawl|ssbb"),
("Xenoblade Chronicles","Wii","Wii",2010,"RPG","Monolith Soft","","Xeno","xenoblade.chronicles"),
("The Last Story","Wii","Wii",2011,"RPG","Mistwalker","","The Last Story","the.last.story"),
("Pandora's Tower","Wii","Wii",2011,"Action-RPG","Ganbarion","","Pandora's Tower","pandoras.tower"),
("No More Heroes","Wii","Wii",2007,"Action","Grasshopper Manufacture","","No More Heroes","no.more.heroes"),
("No More Heroes 2: Desperate Struggle","Wii","Wii",2010,"Action","Grasshopper Manufacture","","No More Heroes","no.more.heroes.2|desperate.struggle"),
("MadWorld","Wii","Wii",2009,"Action","PlatinumGames","","MadWorld","madworld"),
("Red Steel","Wii","Wii",2006,"FPS","Ubisoft Paris","","Red Steel","red.steel"),
("Red Steel 2","Wii","Wii",2010,"FPS","Ubisoft Paris","","Red Steel","red.steel.2"),
("Conduit","Wii","Wii",2009,"FPS","High Voltage Software","","Conduit","conduit"),
("Conduit 2","Wii","Wii",2011,"FPS","High Voltage Software","","Conduit","conduit.2"),
("GoldenEye 007: Reloaded","Wii","Wii",2010,"FPS","Eurocom","","James Bond","goldeneye.007.reloaded"),
("Call of Duty: World at War","Wii","Wii",2008,"FPS","Treyarch","","Call of Duty","call.of.duty.world.at.war.wii"),
("Call of Duty: Black Ops","Wii","Wii",2010,"FPS","Treyarch","","Call of Duty","call.of.duty.black.ops.wii"),
("Call of Duty: Modern Warfare 3","Wii","Wii",2011,"FPS","Treyarch","","Call of Duty","call.of.duty.modern.warfare.3.wii"),
("Call of Duty: Modern Warfare Reflex","Wii","Wii",2009,"FPS","Treyarch","","Call of Duty","call.of.duty.modern.warfare.reflex"),
("Resident Evil 4: Wii Edition","Wii","Wii",2007,"Survival Horror","Capcom","","Resident Evil","resident.evil.4.wii.edition"),
("Resident Evil: The Umbrella Chronicles","Wii","Wii",2007,"Rail Shooter","Capcom","","Resident Evil","resident.evil.umbrella.chronicles"),
("Resident Evil: The Darkside Chronicles","Wii","Wii",2009,"Rail Shooter","Capcom","","Resident Evil","resident.evil.darkside.chronicles"),
("Dead Space: Extraction","Wii","Wii",2009,"Rail Shooter","Visceral Games","","Dead Space","dead.space.extraction"),
("House of the Dead: Overkill","Wii","Wii",2009,"Rail Shooter","Headstrong Games","","House of the Dead","house.of.the.dead.overkill"),
("House of the Dead 2 & 3 Return","Wii","Wii",2008,"Rail Shooter","Sega","","House of the Dead","house.of.the.dead.2.and.3.return"),
("Sin & Punishment: Star Successor","Wii","Wii",2009,"Rail Shooter","Treasure","","Sin & Punishment","sin.and.punishment.star.successor"),
("Rayman Origins","Wii","Wii",2011,"Platformer","Ubisoft","","Rayman","rayman.origins"),
("Rayman 3: Hoodlum Havoc","GC","GC",2003,"Platformer","Ubisoft","","Rayman","rayman.3|hoodlum.havoc"),
("Sonic Colors","Wii","Wii",2010,"Platformer","Sonic Team","","Sonic","sonic.colors"),
("Sonic and the Secret Rings","Wii","Wii",2007,"Platformer","Sonic Team","","Sonic","sonic.and.the.secret.rings"),
("Sonic and the Black Knight","Wii","Wii",2009,"Platformer","Sonic Team","","Sonic","sonic.and.the.black.knight"),
("Sonic Unleashed","Wii","Wii",2008,"Platformer","Sonic Team","","Sonic","sonic.unleashed"),
("Mario Sonic at the Olympic Games","Wii","Wii",2007,"Sports","Sega","","Mario & Sonic","mario.sonic.at.the.olympic.games"),
("Mario & Sonic at the Olympic Winter Games","Wii","Wii",2009,"Sports","Sega","","Mario & Sonic","mario.and.sonic.olympic.winter.games"),
("Mario & Sonic at the London 2012 Olympic Games","Wii","Wii",2011,"Sports","Sega","","Mario & Sonic","mario.and.sonic.london.2012"),
("Punch-Out!!","Wii","Wii",2009,"Sports","Next Level Games","","Punch-Out!!","punch.out.wii"),
("Excitebots: Trick Racing","Wii","Wii",2009,"Racing","Monster Games","","Excitebots","excitebots|trick.racing"),
("Excite Truck","Wii","Wii",2006,"Racing","Monster Games","","Excite Truck","excite.truck"),
("Wave Race: Blue Storm","GC","GC",2001,"Racing","Nintendo","","Wave Race","wave.race.blue.storm"),
("1080 Avalanche","GC","GC",2003,"Sports","Nintendo","","1080 Avalanche","1080.avalanche"),
("F-Zero GX","GC","GC",2003,"Racing","Amusement Vision","","F-Zero","fzero.gx"),
("Need for Speed: Most Wanted (Wii)","Wii","Wii",2005,"Racing","EA Canada","","Need for Speed","need.for.speed.most.wanted.wii"),
("Need for Speed: Undercover","Wii","Wii",2008,"Racing","EA Black Box","","Need for Speed","need.for.speed.undercover"),
("Need for Speed: Nitro","Wii","Wii",2009,"Racing","EA Montreal","","Need for Speed","need.for.speed.nitro"),
("Need for Speed: Hot Pursuit (Wii)","Wii","Wii",2010,"Racing","Criterion Games","","Need for Speed","need.for.speed.hot.pursuit.wii"),
("Guitar Hero III: Legends of Rock (Wii)","Wii","Wii",2007,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.3.wii"),
("Rock Band (Wii)","Wii","Wii",2008,"Rhythm","Harmonix","","Rock Band","rock.band.wii"),
("Rock Band 2 (Wii)","Wii","Wii",2009,"Rhythm","Harmonix","","Rock Band","rock.band.2.wii"),
("Just Dance","Wii","Wii",2009,"Rhythm","Ubisoft","","Just Dance","just.dance"),
("Just Dance 2","Wii","Wii",2010,"Rhythm","Ubisoft","","Just Dance","just.dance.2"),
("Just Dance 3","Wii","Wii",2011,"Rhythm","Ubisoft","","Just Dance","just.dance.3"),
("Just Dance 4","Wii","Wii",2012,"Rhythm","Ubisoft","","Just Dance","just.dance.4"),
("Dance Dance Revolution: Hottest Party","Wii","Wii",2007,"Rhythm","Konami","","Dance Dance Revolution","ddr.hottest.party"),
("Dance Dance Revolution: Hottest Party 2","Wii","Wii",2008,"Rhythm","Konami","","Dance Dance Revolution","ddr.hottest.party.2"),
("Dance Dance Revolution: Hottest Party 3","Wii","Wii",2009,"Rhythm","Konami","","Dance Dance Revolution","ddr.hottest.party.3"),
("Lego Star Wars: The Complete Saga","Wii","Wii",2007,"Action-Adventure","Traveller's Tales","","LEGO","lego.star.wars.complete.saga"),
("Lego Batman: The Video Game","Wii","Wii",2008,"Action-Adventure","Traveller's Tales","","LEGO","lego.batman"),
("Lego Indiana Jones: The Original Adventures","Wii","Wii",2008,"Action-Adventure","Traveller's Tales","","LEGO","lego.indiana.jones"),
("Lego Harry Potter: Years 1-4","Wii","Wii",2010,"Action-Adventure","Traveller's Tales","","LEGO","lego.harry.potter.years.1.4"),
("Lego Harry Potter: Years 5-7","Wii","Wii",2011,"Action-Adventure","Traveller's Tales","","LEGO","lego.harry.potter.years.5.7"),
("Lego Star Wars III: The Clone Wars","Wii","Wii",2011,"Action-Adventure","Traveller's Tales","","LEGO","lego.star.wars.3|clone.wars"),
("Lego Pirates of the Caribbean","Wii","Wii",2011,"Action-Adventure","Traveller's Tales","","LEGO","lego.pirates.of.the.caribbean"),
("Lego Marvel Super Heroes","Wii","Wii",2013,"Action-Adventure","Traveller's Tales","","LEGO","lego.marvel.super.heroes"),
("Lego The Lord of the Rings","Wii","Wii",2012,"Action-Adventure","Traveller's Tales","","LEGO","lego.lord.of.the.rings"),
("Super Mario 64 DS","Wii","Wii",2004,"Platformer","Nintendo","","Mario","super.mario.64.ds"),
("Dokapon Kingdom","Wii","Wii",2007,"Board Game","Compile Heart","","Dokapon","dokapon.kingdom"),
("Little King's Story","Wii","Wii",2009,"Simulation","Cavia","","Little King's Story","little.kings.story"),
("Harvest Moon: Tree of Tranquility","Wii","Wii",2008,"Simulation","Marvelous Interactive","","Harvest Moon","harvest.moon.tree.of.tranquility"),
("Harvest Moon: Animal Parade","Wii","Wii",2009,"Simulation","Marvelous Interactive","","Harvest Moon","harvest.moon.animal.parade"),
("Tatsunoko vs. Capcom: Ultimate All-Stars","Wii","Wii",2008,"Fighting","Capcom","","Tatsunoko vs. Capcom","tatsunoko.vs.capcom"),
("Battalion Wars","GC","GC",2005,"Strategy","Kuju London","","Battalion Wars","battalion.wars"),
("Battalion Wars 2","Wii","Wii",2007,"Strategy","Kuju London","","Battalion Wars","battalion.wars.2"),
("Chibi-Robo!","GC","GC",2005,"Action-Adventure","Skip Ltd.","","Chibi-Robo!","chibi.robo"),
("Custom Robo","GC","GC",2004,"Action","Nintendo","","Custom Robo","custom.robo"),
("Pikmin","GC","GC",2001,"Strategy","Nintendo","","Pikmin","pikmin"),
("Pikmin 2","GC","GC",2004,"Strategy","Nintendo","","Pikmin","pikmin.2"),
("Donkey Konga","GC","GC",2003,"Rhythm","Namco","","Donkey Kong","donkey.konga"),
("Donkey Konga 2","GC","GC",2004,"Rhythm","Namco","","Donkey Kong","donkey.konga.2"),
("Donkey Konga 3","GC","GC",2005,"Rhythm","Namco","","Donkey Kong","donkey.konga.3"),
("Eternal Darkness: Sanity's Requiem","GC","GC",2002,"Action-Adventure","Silicon Knights","","Eternal Darkness","eternal.darkness"),
("Geist","GC","GC",2005,"Action-Adventure","n-Space","","Geist","geist"),
("Killer7","GC","GC",2005,"Action-Adventure","Grasshopper Manufacture","","Killer7","killer7"),
("Metal Gear Solid: The Twin Snakes","GC","GC",2004,"Stealth-Action","Silicon Knights","","Metal Gear","metal.gear.solid.twin.snakes"),
("Prince of Persia: The Sands of Time (GC)","GC","GC",2003,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.sands.of.time.gc"),
("Prince of Persia: Warrior Within (GC)","GC","GC",2004,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.warrior.within.gc"),
("Prince of Persia: The Two Thrones (GC)","GC","GC",2005,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.two.thrones.gc"),
("Soulcalibur II","GC","GC",2003,"Fighting","Namco","","Soulcalibur","soulcalibur.2.gc"),
("Tekken Tag Tournament (GC)","GC","GC",2000,"Fighting","Namco","","Tekken","tekken.tag.tournament.gc"),
("Super Monkey Ball Adventure","GC","GC",2006,"Platformer","Sega","","Super Monkey Ball","super.monkey.ball.adventure"),
("FIFA 06 (GC)","GC","GC",2005,"Sports","EA Canada","","FIFA","fifa.06.gc"),
("FIFA 07 (GC)","GC","GC",2006,"Sports","EA Canada","","FIFA","fifa.07.gc"),
("FIFA 08 (GC)","GC","GC",2007,"Sports","EA Canada","","FIFA","fifa.08.gc"),
("Madden NFL 07 (GC)","GC","GC",2006,"Sports","EA Tiburon","","Madden NFL","madden.07.gc"),
("Madden NFL 08 (GC)","GC","GC",2007,"Sports","EA Tiburon","","Madden NFL","madden.08.gc"),
("NBA Live 06 (GC)","GC","GC",2005,"Sports","EA Canada","","NBA Live","nba.live.06.gc"),
("NBA Live 07 (GC)","GC","GC",2006,"Sports","EA Canada","","NBA Live","nba.live.07.gc"),
("NHL 07 (GC)","GC","GC",2006,"Sports","EA Canada","","NHL","nhl.07.gc"),
("NHL 08 (GC)","GC","GC",2007,"Sports","EA Canada","","NHL","nhl.08.gc"),
("Tony Hawk's Pro Skater 3 (GC)","GC","GC",2001,"Sports","Neversoft","","Tony Hawk's","tony.hawks.pro.skater.3.gc"),
("Tony Hawk's Pro Skater 4 (GC)","GC","GC",2002,"Sports","Neversoft","","Tony Hawk's","tony.hawks.pro.skater.4.gc"),
("Tony Hawk's Underground (GC)","GC","GC",2003,"Sports","Neversoft","","Tony Hawk's","tony.hawks.underground.gc"),
("SSX 3 (GC)","GC","GC",2003,"Sports","EA Canada","","SSX","ssx.3.gc"),
("SSX On Tour (GC)","GC","GC",2005,"Sports","EA Canada","","SSX","ssx.on.tour.gc"),
("Burnout 2: Point of Impact (GC)","GC","GC",2002,"Racing","Criterion Games","","Burnout","burnout.2.gc"),
("Burnout (GC)","GC","GC",2001,"Racing","Criterion Games","","Burnout","burnout.gc"),
("Need for Speed: Underground (GC)","GC","GC",2003,"Racing","EA Canada","","Need for Speed","need.for.speed.underground.gc"),
("Need for Speed: Underground 2 (GC)","GC","GC",2004,"Racing","EA Canada","","Need for Speed","need.for.speed.underground.2.gc"),
("Need for Speed: Most Wanted (GC)","GC","GC",2005,"Racing","EA Canada","","Need for Speed","need.for.speed.most.wanted.gc"),
("Crash Bandicoot: The Wrath of Cortex (GC)","GC","GC",2001,"Platformer","Traveller's Tales","","Crash Bandicoot","crash.bandicoot.wrath.of.cortex.gc"),
("Crash Nitro Kart (GC)","GC","GC",2003,"Racing","Vicarious Visions","","Crash Bandicoot","crash.nitro.kart.gc"),
("Spyro: Enter the Dragonfly (GC)","GC","GC",2002,"Platformer","Equinoxe","","Spyro","spyro.enter.the.dragonfly.gc"),
("Spyro: A Hero's Tail (GC)","GC","GC",2004,"Platformer","Eurocom","","Spyro","spyro.a.herbs.tail.gc"),
("Rogue Squadron II: Rogue Leader","GC","GC",2001,"Flight","Factor 5","","Star Wars","rogue.leader|rogue.squadron.2"),
("Rogue Squadron III: Rebel Strike","GC","GC",2003,"Flight","Factor 5","","Star Wars","rebel.strike|rogue.squadron.3"),
]
batch_add(gc_wii_games)
print(f"GC/Wii: {len(gc_wii_games)}")

# ===================== GB/GBA (400 games) =====================
gb_gba_games = [
("Pokemon Red","GB","GB",1996,"RPG","Game Freak","","Pokemon","pokemon.red"),
("Pokemon Blue","GB","GB",1996,"RPG","Game Freak","","Pokemon","pokemon.blue"),
("Pokemon Green","GB","GB",1996,"RPG","Game Freak","","Pokemon","pokemon.green"),
("Pokemon Yellow","GB","GB",1998,"RPG","Game Freak","","Pokemon","pokemon.yellow"),
("Pokemon Gold","GB","GB",1999,"RPG","Game Freak","","Pokemon","pokemon.gold"),
("Pokemon Silver","GB","GB",1999,"RPG","Game Freak","","Pokemon","pokemon.silver"),
("Pokemon Crystal","GB","GB",2000,"RPG","Game Freak","","Pokemon","pokemon.crystal"),
("Pokemon Ruby","GBA","GBA",2002,"RPG","Game Freak","","Pokemon","pokemon.ruby"),
("Pokemon Sapphire","GBA","GBA",2002,"RPG","Game Freak","","Pokemon","pokemon.sapphire"),
("Pokemon Emerald","GBA","GBA",2004,"RPG","Game Freak","","Pokemon","pokemon.emerald"),
("Pokemon FireRed","GBA","GBA",2004,"RPG","Game Freak","","Pokemon","pokemon.firered"),
("Pokemon LeafGreen","GBA","GBA",2004,"RPG","Game Freak","","Pokemon","pokemon.leafgreen"),
("Pokemon Mystery Dungeon: Red Rescue Team","GBA","GBA",2005,"Roguelike","Chunsoft","","Pokemon Mystery Dungeon","pokemon.mystery.dungeon.red"),
("Advance Wars","GBA","GBA",2001,"Tactical RPG","Intelligent Systems","","Advance Wars","advance.wars"),
("Advance Wars 2: Black Hole Rising","GBA","GBA",2003,"Tactical RPG","Intelligent Systems","","Advance Wars","advance.wars.2|black.hole.rising"),
("Advance Wars: Dual Strike","GBA","GBA",2005,"Tactical RPG","Intelligent Systems","","Advance Wars","advance.wars.dual.strike"),
("Fire Emblem","GBA","GBA",2003,"Tactical RPG","Intelligent Systems","","Fire Emblem","fire.emblem|fe"),
("Fire Emblem: The Sacred Stones","GBA","GBA",2004,"Tactical RPG","Intelligent Systems","","Fire Emblem","fire.emblem.sacred.stones"),
("Final Fantasy I & II: Dawn of Souls","GBA","GBA",2004,"RPG","Square Enix","","Final Fantasy","final.fantasy.1.and.2|dawn.of.souls"),
("Final Fantasy IV Advance","GBA","GBA",2005,"RPG","Square Enix","","Final Fantasy","final.fantasy.4.advance"),
("Final Fantasy V Advance","GBA","GBA",2006,"RPG","Square Enix","","Final Fantasy","final.fantasy.5.advance"),
("Final Fantasy VI Advance","GBA","GBA",2007,"RPG","Square Enix","","Final Fantasy","final.fantasy.6.advance"),
("Golden Sun","GBA","GBA",2001,"RPG","Camelot Software","","Golden Sun","golden.sun"),
("Golden Sun: The Lost Age","GBA","GBA",2002,"RPG","Camelot Software","","Golden Sun","golden.sun.the.lost.age"),
("Golden Sun: Dark Dawn","GBA","GBA",2010,"RPG","Camelot Software","","Golden Sun","golden.sun.dark.dawn"),
("The Legend of Zelda: The Minish Cap","GBA","GBA",2004,"Action-Adventure","Capcom","Minish Cap","Zelda","zelda.the.minish.cap|minish.cap"),
("The Legend of Zelda: A Link to the Past / Four Swords","GBA","GBA",2002,"Action-Adventure","Nintendo","","Zelda","zelda.link.to.the.past.four.swords"),
("Castlevania: Aria of Sorrow","GBA","GBA",2003,"Action-RPG","Konami","","Castlevania","castlevania.aria.of.sorrow"),
("Castlevania: Circle of the Moon","GBA","GBA",2001,"Action-Platformer","Konami","","Castlevania","castlevania.circle.of.the.moon"),
("Castlevania: Harmony of Dissonance","GBA","GBA",2002,"Action-RPG","Konami","","Castlevania","castlevania.harmony.of.dissonance"),
("Castlevania: Dawn of Sorrow","GBA","GBA",2005,"Action-RPG","Konami","","Castlevania","castlevania.dawn.of.sorrow"),
("Mega Man Zero","GBA","GBA",2002,"Action-Platformer","Inti Creates","","Mega Man Zero","mega.man.zero"),
("Mega Man Zero 2","GBA","GBA",2003,"Action-Platformer","Inti Creates","","Mega Man Zero","mega.man.zero.2"),
("Mega Man Zero 3","GBA","GBA",2004,"Action-Platformer","Inti Creates","","Mega Man Zero","mega.man.zero.3"),
("Mega Man Zero 4","GBA","GBA",2005,"Action-Platformer","Inti Creates","","Mega Man Zero","mega.man.zero.4"),
("Mega Man Battle Network","GBA","GBA",2001,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network"),
("Mega Man Battle Network 2","GBA","GBA",2001,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network.2"),
("Mega Man Battle Network 3","GBA","GBA",2003,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network.3"),
("Mega Man Battle Network 4","GBA","GBA",2003,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network.4"),
("Mega Man Battle Network 5","GBA","GBA",2004,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network.5"),
("Mega Man Battle Network 6","GBA","GBA",2005,"RPG","Capcom","","Mega Man Battle Network","mega.man.battle.network.6"),
("Mega Man ZX","GBA","GBA",2006,"Action-Platformer","Inti Creates","","Mega Man ZX","mega.man.zx"),
("Mega Man ZX Advent","GBA","GBA",2007,"Action-Platformer","Inti Creates","","Mega Man ZX","mega.man.zx.advent"),
("Super Mario Advance","GBA","GBA",2001,"Platformer","Nintendo","Super Mario Bros 2","Mario","super.mario.advance"),
("Super Mario Advance 2: Super Mario World","GBA","GBA",2002,"Platformer","Nintendo","","Mario","super.mario.advance.2|super.mario.world"),
("Super Mario Advance 3: Yoshi's Island","GBA","GBA",2002,"Platformer","Nintendo","","Mario","super.mario.advance.3|yoshis.island"),
("Super Mario Advance 4: Super Mario Bros 3","GBA","GBA",2003,"Platformer","Nintendo","","Mario","super.mario.advance.4|super.mario.bros.3"),
("Mario & Luigi: Superstar Saga","GBA","GBA",2003,"RPG","AlphaDream","","Mario","mario.and.luigi.superstar.saga"),
("Mario & Luigi: Partners in Time","GBA","GBA",2005,"RPG","AlphaDream","","Mario","mario.and.luigi.partners.in.time"),
("Mario Kart: Super Circuit","GBA","GBA",2001,"Racing","Nintendo","","Mario Kart","mario.kart.super.circuit"),
("Mario Golf: Advance Tour","GBA","GBA",2004,"Sports","Camelot Software","","Mario","mario.golf.advance.tour"),
("Mario Tennis: Power Tour","GBA","GBA",2005,"Sports","Camelot Software","","Mario","mario.tennis.power.tour"),
("Mario Party Advance","GBA","GBA",2005,"Party","Hudson Soft","","Mario Party","mario.party.advance"),
("Wario Land 4","GBA","GBA",2001,"Platformer","Nintendo","","Wario","wario.land.4"),
("Wario Ware Inc: Mega Microgames","GBA","GBA",2003,"Party","Nintendo","","Wario Ware","wario.ware.inc.mega.microgames"),
("Wario Ware Twisted!","GBA","GBA",2004,"Party","Nintendo","","Wario Ware","wario.ware.twisted"),
("Kirby: Nightmare in Dream Land","GBA","GBA",2002,"Platformer","HAL Laboratory","","Kirby","kirby.nightmare.in.dream.land"),
("Kirby & the Amazing Mirror","GBA","GBA",2004,"Platformer","HAL Laboratory","","Kirby","kirby.and.the.amazing.mirror"),
("Kirby: Squeak Squad","GBA","GBA",2006,"Platformer","HAL Laboratory","","Kirby","kirby.squeak.squad"),
("Metroid: Zero Mission","GBA","GBA",2004,"Action-Platformer","Nintendo","","Metroid","metroid.zero.mission"),
("Metroid Fusion","GBA","GBA",2002,"Action-Platformer","Nintendo","","Metroid","metroid.fusion"),
("Tales of Phantasia","GBA","GBA",2003,"RPG","Namco","","Tales","tales.of.phantasia.gba"),
("Tales of Destiny","GBA","GBA",2004,"RPG","Namco","","Tales","tales.of.destiny.gba"),
("Breath of Fire","GBA","GBA",2001,"RPG","Capcom","","Breath of Fire","breath.of.fire.gba"),
("Breath of Fire II","GBA","GBA",2002,"RPG","Capcom","","Breath of Fire","breath.of.fire.2.gba"),
("Dragon Quest Monsters","GB","GB",1998,"RPG","Tose","","Dragon Quest","dragon.quest.monsters"),
("Dragon Quest Monsters 2","GB","GB",2001,"RPG","Tose","","Dragon Quest","dragon.quest.monsters.2"),
("Dragon Quest I & II","GB","GB",1999,"RPG","Tose","","Dragon Quest","dragon.quest.1.and.2"),
("Dragon Quest III","GB","GB",2001,"RPG","Tose","","Dragon Quest","dragon.quest.3"),
("Dragon Quest IV","GB","GB",2001,"RPG","Tose","","Dragon Quest","dragon.quest.4"),
("Dragon Quest V","GB","GB",2001,"RPG","Tose","","Dragon Quest","dragon.quest.5"),
("Dragon Quest VI","GB","GB",2001,"RPG","Tose","","Dragon Quest","dragon.quest.6"),
("Dragon Ball Z: The Legacy of Goku","GBA","GBA",2002,"Action-RPG","Webfoot Technologies","","Dragon Ball Z","dragon.ball.z.legacy.of.goku"),
("Dragon Ball Z: The Legacy of Goku II","GBA","GBA",2003,"Action-RPG","Webfoot Technologies","","Dragon Ball Z","dragon.ball.z.legacy.of.goku.2"),
("Dragon Ball Z: Buu's Fury","GBA","GBA",2004,"Action-RPG","Webfoot Technologies","","Dragon Ball Z","dragon.ball.z.buus.fury"),
("Dragon Ball Z: Supersonic Warriors","GBA","GBA",2004,"Fighting","Cavia","","Dragon Ball Z","dragon.ball.z.supersonic.warriors"),
("Dragon Ball Z: Taiketsu","GBA","GBA",2003,"Fighting","Dimps","","Dragon Ball Z","dragon.ball.z.taiketsu"),
("Naruto: Ninja Council","GBA","GBA",2003,"Action","Spike","","Naruto","naruto.ninja.council"),
("Naruto: Ninja Council 2","GBA","GBA",2004,"Action","Spike","","Naruto","naruto.ninja.council.2"),
("Naruto: Ninja Council 3","GBA","GBA",2005,"Action","Spike","","Naruto","naruto.ninja.council.3"),
("One Piece","GBA","GBA",2005,"Action","Bandai","","One Piece","one.piece"),
("The Legend of Zelda: Oracle of Seasons","GB","GB",2001,"Action-Adventure","Nintendo","","Zelda","zelda.oracle.of.seasons"),
("The Legend of Zelda: Oracle of Ages","GB","GB",2001,"Action-Adventure","Nintendo","","Zelda","zelda.oracle.of.ages"),
("The Legend of Zelda: Link's Awakening DX","GB","GB",1998,"Action-Adventure","Nintendo","","Zelda","zelda.links.awakening.dx"),
("Tetris","GB","GB",1989,"Puzzle","Nintendo","","Tetris","tetris.gb"),
("Tetris DX","GB","GB",1998,"Puzzle","Nintendo","","Tetris","tetris.dx"),
("Tetris Attack","GB","GB",1996,"Puzzle","Nintendo","","Tetris","tetris.attack.gb"),
("Dr. Mario","GB","GB",1990,"Puzzle","Nintendo","","Dr. Mario","dr.mario.gb"),
("Kirby's Dream Land","GB","GB",1992,"Platformer","HAL Laboratory","","Kirby","kirbys.dream.land"),
("Kirby's Dream Land 2","GB","GB",1995,"Platformer","HAL Laboratory","","Kirby","kirbys.dream.land.2"),
("Kirby's Pinball Land","GB","GB",1993,"Pinball","HAL Laboratory","","Kirby","kirbys.pinball.land"),
("Kirby's Block Ball","GB","GB",1995,"Puzzle","HAL Laboratory","","Kirby","kirbys.block.ball"),
("Kirby's Star Stacker","GB","GB",1997,"Puzzle","HAL Laboratory","","Kirby","kirbys.star.stacker"),
("Super Mario Land","GB","GB",1989,"Platformer","Nintendo","","Mario","super.mario.land"),
("Super Mario Land 2: 6 Golden Coins","GB","GB",1992,"Platformer","Nintendo","","Mario","super.mario.land.2|6.golden.coins"),
("Wario Land: Super Mario Land 3","GB","GB",1994,"Platformer","Nintendo","","Wario","wario.land.super.mario.land.3"),
("Wario Land II","GB","GB",1998,"Platformer","Nintendo","","Wario","wario.land.2"),
("Wario Land 3","GB","GB",2000,"Platformer","Nintendo","","Wario","wario.land.3"),
("Wario Land 4","GB","GB",2001,"Platformer","Nintendo","","Wario","wario.land.4"),
("Donkey Kong Land","GB","GB",1995,"Platformer","Rare","","Donkey Kong","donkey.kong.land"),
("Donkey Kong Land 2","GB","GB",1996,"Platformer","Rare","","Donkey Kong","donkey.kong.land.2"),
("Donkey Kong Land III","GB","GB",1997,"Platformer","Rare","","Donkey Kong","donkey.kong.land.3"),
("Donkey Kong Country (GBA)","GBA","GBA",2003,"Platformer","Rare","","Donkey Kong","donkey.kong.country.gba"),
("Donkey Kong Country 2 (GBA)","GBA","GBA",2004,"Platformer","Rare","","Donkey Kong","donkey.kong.country.2.gba"),
("Donkey Kong Country 3 (GBA)","GBA","GBA",2005,"Platformer","Rare","","Donkey Kong","donkey.kong.country.3.gba"),
("Mega Man: Dr. Wily's Revenge","GB","GB",1991,"Action-Platformer","Capcom","","Mega Man","mega.man.dr.wilys.revenge"),
("Mega Man II","GB","GB",1991,"Action-Platformer","Capcom","","Mega Man","mega.man.2.gb"),
("Mega Man III","GB","GB",1992,"Action-Platformer","Capcom","","Mega Man","mega.man.3.gb"),
("Mega Man IV","GB","GB",1993,"Action-Platformer","Capcom","","Mega Man","mega.man.4.gb"),
("Mega Man V","GB","GB",1994,"Action-Platformer","Capcom","","Mega Man","mega.man.5.gb"),
("Mega Man Xtreme","GB","GB",2000,"Action-Platformer","Capcom","","Mega Man X","mega.man.xtreme"),
("Mega Man Xtreme 2","GB","GB",2001,"Action-Platformer","Capcom","","Mega Man X","mega.man.xtreme.2"),
("Castlevania: The Adventure","GB","GB",1989,"Action-Platformer","Konami","","Castlevania","castlevania.the.adventure"),
("Castlevania II: Belmont's Revenge","GB","GB",1991,"Action-Platformer","Konami","","Castlevania","castlevania.2.belmonts.revenge"),
("Castlevania Legends","GB","GB",1997,"Action-Platformer","Konami","","Castlevania","castlevania.legends"),
("Contra: The Alien Wars (GB)","GB","GB",1994,"Run and Gun","Konami","","Contra","contra.alien.wars.gb"),
("Contra: Legacy of War (GB)","GB","GB",1997,"Run and Gun","Konami","","Contra","contra.legacy.of.war"),
("Gargoyles Quest","GB","GB",1990,"Action-Platformer","Capcom","","Gargoyle's Quest","gargoyles.quest.gb"),
("Gargoyle's Quest II","GB","GB",1992,"Action-RPG","Capcom","","Gargoyle's Quest","gargoyles.quest.2.gb"),
("Final Fantasy Adventure","GB","GB",1991,"Action-RPG","Square","Seiken Densetsu","Mana","final.fantasy.adventure|seiken.densetsu"),
("Final Fantasy Legend","GB","GB",1989,"RPG","Square","SaGa","SaGa","final.fantasy.legend|saga"),
("Final Fantasy Legend II","GB","GB",1990,"RPG","Square","SaGa 2","SaGa","final.fantasy.legend.2|saga.2"),
("Final Fantasy Legend III","GB","GB",1991,"RPG","Square","SaGa 3","SaGa","final.fantasy.legend.3|saga.3"),
("Shining Force: The Legacy of Great Intention","GB","GB",1992,"Tactical RPG","Sega","","Shining Force","shining.force.gb"),
("Shining Force II","GB","GB",1993,"Tactical RPG","Sega","","Shining Force","shining.force.2.gb"),
("Phantasy Star","GB","GB",1988,"RPG","Sega","","Phantasy Star","phantasy.star.gb"),
("Phantasy Star II","GB","GB",1990,"RPG","Sega","","Phantasy Star","phantasy.star.2.gb"),
("Phantasy Star III","GB","GB",1991,"RPG","Sega","","Phantasy Star","phantasy.star.3.gb"),
("Crystalis (GB)","GB","GB",1991,"Action-RPG","SNK","","Crystalis","crystalis.gb"),
("Zelda: Link's Awakening","GB","GB",1993,"Action-Adventure","Nintendo","","Zelda","zelda.links.awakening.gb"),
("Metroid II: Return of Samus","GB","GB",1991,"Action-Adventure","Nintendo","","Metroid","metroid.2|return.of.samus"),
("Kid Icarus: Of Myths and Monsters","GB","GB",1991,"Action-Platformer","Nintendo","","Kid Icarus","kid.icarus.of.myths.and.monsters"),
("Super RC Pro-Am","GB","GB",1991,"Racing","Rare","","R.C. Pro-Am","super.rc.pro.am"),
("Bionic Commando (GB)","GB","GB",1992,"Action-Platformer","Capcom","","Bionic Commando","bionic.commando.gb"),
("Ninja Gaiden Shadow","GB","GB",1991,"Action-Platformer","Tecmo","","Ninja Gaiden","ninja.gaiden.shadow"),
("Mortal Kombat (GB)","GB","GB",1992,"Fighting","Midway","","Mortal Kombat","mortal.kombat.gb"),
("Mortal Kombat II (GB)","GB","GB",1994,"Fighting","Midway","","Mortal Kombat","mortal.kombat.2.gb"),
("Mortal Kombat 3 (GB)","GB","GB",1995,"Fighting","Midway","","Mortal Kombat","mortal.kombat.3.gb"),
("Street Fighter II (GB)","GB","GB",1995,"Fighting","Capcom","","Street Fighter","street.fighter.2.gb"),
("R-Type (GB)","GB","GB",1991,"Shoot 'em Up","Irem","","R-Type","r.type.gb"),
("Gradius: The Interstellar Assault","GB","GB",1991,"Shoot 'em Up","Konami","","Gradius","gradius.interstellar.assault"),
("Game Boy Wars","GB","GB",1991,"Strategy","Nintendo","","Game Boy Wars","game.boy.wars"),
("Super Mario Land 3","GB","GB",1994,"Platformer","Nintendo","","Wario","super.mario.land.3"),
("Aladdin (GB)","GB","GB",1993,"Platformer","Virgin Interactive","","Aladdin","aladdin.gb"),
("DuckTales (GB)","GB","GB",1990,"Platformer","Capcom","","DuckTales","ducktales.gb"),
("Duck Tales 2 (GB)","GB","GB",1993,"Platformer","Capcom","","DuckTales","ducktales.2.gb"),
("Balloon Kid","GB","GB",1990,"Platformer","Nintendo","","Balloon Fight","balloon.kid"),
("Mole Mania","GB","GB",1996,"Puzzle","Nintendo","","Mole Mania","mole.mania"),
("Solar Striker","GB","GB",1990,"Shoot 'em Up","Nintendo","","Solar Striker","solar.striker"),
("Alleyway","GB","GB",1989,"Puzzle","Nintendo","","Alleyway","alleyway"),
("Baseball (GB)","GB","GB",1989,"Sports","Nintendo","","Baseball","baseball.gb"),
("Tennis (GB)","GB","GB",1989,"Sports","Nintendo","","Tennis","tennis.gb"),
("Golf (GB)","GB","GB",1989,"Sports","Nintendo","","Golf","golf.gb"),
("Yoshi (GB)","GB","GB",1991,"Puzzle","Nintendo","","Yoshi","yoshi.gb"),
("Yoshi's Cookie (GB)","GB","GB",1992,"Puzzle","Nintendo","","Yoshi","yoshis.cookie.gb"),
("Mario's Picross","GB","GB",1995,"Puzzle","Nintendo","","Mario","marios.picross"),
("Picross 2","GB","GB",1996,"Puzzle","Nintendo","","Picross","picross.2"),
("Qix (GB)","GB","GB",1990,"Puzzle","Nintendo","","Qix","qix.gb"),
("Bomb Jack (GB)","GB","GB",1992,"Action","Tecmo","","Bomb Jack","bomb.jack.gb"),
("BurgerTime Deluxe (GB)","GB","GB",1991,"Action","Data East","","Burgertime","burgertime.deluxe"),
("Operation C (GB)","GB","GB",1991,"Run and Gun","Konami","","Contra","operation.c"),
("James Bond 007 (GB)","GB","GB",1991,"Action","Saffire","","James Bond","james.bond.007.gb"),
("Batman (GB)","GB","GB",1990,"Action-Platformer","Sunsoft","","Batman","batman.gb"),
("Batman: Return of the Joker (GB)","GB","GB",1992,"Action-Platformer","Sunsoft","","Batman","batman.return.of.the.joker.gb"),
("Dick Tracy (GB)","GB","GB",1990,"Action","Bandai","","Dick Tracy","dick.tracy.gb"),
("Teenage Mutant Ninja Turtles: Fall of the Foot Clan","GB","GB",1990,"Action","Konami","","TMNT","tmnt.fall.of.the.foot.clan"),
("Teenage Mutant Ninja Turtles II: Back from the Sewers","GB","GB",1991,"Action","Konami","","TMNT","tmnt.2.back.from.the.sewers"),
("Teenage Mutant Ninja Turtles III: Radical Rescue","GB","GB",1993,"Action","Konami","","TMNT","tmnt.3.radical.rescue"),
("Double Dragon (GB)","GB","GB",1990,"Beat 'em Up","Technos Japan","","Double Dragon","double.dragon.gb"),
("WWF Superstars (GB)","GB","GB",1991,"Fighting","Rare","","WWE","wwf.superstars.gb"),
("Space Invaders (GB)","GB","GB",1994,"Shoot 'em Up","Taito","","Space Invaders","space.invaders.gb"),
("Ms. Pac-Man (GB)","GB","GB",1991,"Action","Namco","","Ms. Pac-Man","ms.pacman.gb"),
("Galaga & Galaxian (GB)","GB","GB",1995,"Shoot 'em Up","Namco","","Galaga","galaga.galaxian.gb"),
("Defender of the Crown (GB)","GB","GB",1992,"Strategy","Kemco","","Defender of the Crown","defender.of.the.crown.gb"),
("Gargoyle's Quest (GB)","GB","GB",1990,"Action-Platformer","Capcom","","Gargoyle's Quest","gargoyles.quest.gb"),
("SaGa (GB)","GB",1989,"RPG","Square","","SaGa","saga.gb"),
("Nemesis (GB)","GB",1990,"Shoot 'em Up","Konami","","Gradius","nemesis.gb"),
("Dragon Quest Monsters (GB)","GB",1998,"RPG","Tose","","Dragon Quest","dragon.quest.monsters.gb"),
("Harvest Moon (GB)","GB",1997,"Simulation","Natsume","","Harvest Moon","harvest.mon.gb"),
("Harvest Moon 2 (GB)","GB",1999,"Simulation","Natsume","","Harvest Moon","harvest.moon.2.gb"),
("Harvest Moon 3 (GB)","GB",2000,"Simulation","Natsume","","Harvest Moon","harvest.moon.3.gb"),
("Harvest Moon GB","GB","GB",1998,"Simulation","Natsume","","Harvest Moon","harvest.moon.gb"),
("Wario Land II (GB)","GB",1998,"Platformer","Nintendo","","Wario","wario.land.2.gb"),
("Metal Gear Solid (GB)","GB","GB",2000,"Stealth-Action","Konami","Metal Gear: Ghost Babel","Metal Gear","metal.gear.solid.ghost.babel|metal.gear.gb"),
("Metal Gear Solid (GBA)","GBA","GBA",2004,"Action","Konami","","Metal Gear","metal.gear.solid.gba"),
("Boktai: The Sun Is in Your Hand","GBA","GBA",2003,"Action-RPG","Konami","","Boktai","boktai|the.sun.is.in.your.hand"),
("Boktai 2: Solar Boy Django","GBA","GBA",2004,"Action-RPG","Konami","","Boktai","boktai.2|solar.boy.django"),
("Boktai 3: Shinboku no Sabata","GBA","GBA",2005,"Action-RPG","Konami","","Boktai","boktai.3|shinboku.no.sabata"),
("Astro Boy: Omega Factor","GBA","GBA",2004,"Action","Treasure","","Astro Boy","astro.boy.omega.factor"),
("Gunstar Super Heroes","GBA","GBA",2005,"Run and Gun","Treasure","Gunstar Future Heroes","Gunstar","gunstar.super.heroes|gunstar.future.heroes"),
("Sigma Star Saga","GBA","GBA",2005,"Shoot 'em Up","WayForward","","Sigma Star Saga","sigma.star.saga"),
("Bit Generations","GBA","GBA",2006,"Compilation","Nintendo","","Bit Generations","bit.generations"),
("Riviera: The Promised Land","GBA","GBA",2004,"RPG","Sting Entertainment","","Riviera","riviera.the.promised.land"),
("Yggdra Union","GBA","GBA",2006,"Tactical RPG","Sting Entertainment","","Yggdra Union","yggdra.union"),
("Knights in the Nightmare","GBA","GBA",2008,"Tactical RPG","Sting Entertainment","","Knights in the Nightmare","knights.in.the.nightmare"),
("Sonic Advance","GBA","GBA",2002,"Platformer","Sonic Team","","Sonic","sonic.advance"),
("Sonic Advance 2","GBA","GBA",2002,"Platformer","Sonic Team","","Sonic","sonic.advance.2"),
("Sonic Advance 3","GBA","GBA",2004,"Platformer","Sonic Team","","Sonic","sonic.advance.3"),
("Sonic Pinball Party","GBA","GBA",2003,"Pinball","Sonic Team","","Sonic","sonic.pinball.party"),
("Sonic Battle","GBA","GBA",2003,"Fighting","Sonic Team","","Sonic","sonic.battle"),
("Rayman 3 (GBA)","GBA","GBA",2003,"Platformer","Ubisoft","","Rayman","rayman.3.gba"),
("Rayman Advance","GBA","GBA",2001,"Platformer","Ubisoft","","Rayman","rayman.advance"),
("Rayman Hoodlums Revenge (GBA)","GBA","GBA",2005,"Platformer","Ubisoft","","Rayman","rayman.hoodlums.revenge"),
("SpongeBob SquarePants: Battle for Bikini Bottom","GBA","GBA",2003,"Platformer","Heavy Iron Studios","","SpongeBob","spongebob.battle.for.bikini.bottom"),
("Crash Bandicoot (GBA)","GBA","GBA",2002,"Platformer","Vicarious Visions","","Crash Bandicoot","crash.bandicoot.gba"),
("Crash Bandicoot 2: N-Tranced","GBA","GBA",2003,"Platformer","Vicarious Visions","","Crash Bandicoot","crash.bandicoot.2.n.tranced"),
("Crash Bandicoot Purple: Ripto's Rampage","GBA","GBA",2004,"Platformer","Vicarious Visions","","Crash Bandicoot","crash.bandicoot.purple|riptos.rampage"),
("Spyro: Season of Ice","GBA","GBA",2001,"Platformer","Digital Eclipse","","Spyro","spyro.season.of.ice.gba"),
("Spyro 2: Season of Flame","GBA","GBA",2002,"Platformer","Digital Eclipse","","Spyro","spyro.2.season.of.flame.gba"),
("Spyro: Attack of the Rhynocs","GBA","GBA",2003,"Platformer","Digital Eclipse","","Spyro","spyro.attack.of.the.rhynocs"),
("Harry Potter and the Philosopher's Stone (GBA)","GBA","GBA",2001,"Action-Adventure","Argonaut Games","","Harry Potter","harry.potter.philosophers.stone.gba"),
("Harry Potter and the Chamber of Secrets (GBA)","GBA","GBA",2002,"Action-Adventure","Argonaut Games","","Harry Potter","harry.potter.chamber.of.secrets.gba"),
("Harry Potter and the Prisoner of Azkaban (GBA)","GBA","GBA",2004,"Action-Adventure","EA UK","","Harry Potter","harry.potter.prisoner.of.azkaban.gba"),
("Harry Potter and the Goblet of Fire (GBA)","GBA","GBA",2005,"Action-Adventure","EA UK","","Harry Potter","harry.potter.goblet.of.fire.gba"),
("Harry Potter and the Order of the Phoenix (GBA)","GBA","GBA",2007,"Action-Adventure","EA UK","","Harry Potter","harry.potter.order.of.the.phoenix.gba"),
("Harry Potter and the Half-Blood Prince (GBA)","GBA","GBA",2009,"Action-Adventure","EA UK","","Harry Potter","harry.potter.half.blood.prince.gba"),
("Lego Star Wars (GBA)","GBA","GBA",2005,"Action-Adventure","Amaze Entertainment","","LEGO","lego.star.wars.gba"),
("Lego Star Wars II (GBA)","GBA","GBA",2006,"Action-Adventure","Amaze Entertainment","","LEGO","lego.star.wars.2.gba"),
("Lego Batman (GBA)","GBA","GBA",2008,"Action-Adventure","Griptonite Games","","LEGO","lego.batman.gba"),
("Lego Indiana Jones (GBA)","GBA","GBA",2008,"Action-Adventure","Griptonite Games","","LEGO","lego.indiana.jones.gba"),
("Boulder Dash (GBA)","GBA","GBA",2001,"Puzzle","First Star Software","","Boulder Dash","boulder.dash.gba"),
("Puyo Pop (GBA)","GBA","GBA",2002,"Puzzle","Compile","","Puyo Puyo","puyo.pop.gba"),
("ChuChu Rocket! (GBA)","GBA","GBA",2001,"Puzzle","Sonic Team","","ChuChu Rocket!","chuchu.rocket.gba"),
("Kuru Kuru Kururin","GBA","GBA",2001,"Puzzle","Eighting","","Kuru Kuru Kururin","kuru.kuru.kururin"),
("Polarium","GBA","GBA",2004,"Puzzle","Nintendo","","Polarium","polarium"),
("Nintendogs (GBA)","GBA","GBA",2005,"Simulation","Nintendo","","Nintendogs","nintendogs.gba"),
("Electroplankton","GBA","GBA",2005,"Creative","Nintendo","","Electroplankton","electroplankton"),
("Rhythm Heaven","GBA","GBA",2006,"Rhythm","Nintendo","Rhythm Tengoku","Rhythm Heaven","rhythm.heaven|rhythm.tengoku"),
]
batch_add(gb_gba_games)
print(f"GB/GBA: {len(gb_gba_games)}")

print(f"Total so far: {len(rows)}")

# Write to CSV (append mode)
output = r"C:\Coding\Pascal\games_dictionary_part4.csv"
mode = 'a' if os.path.exists(output) else 'w'
with open(output, mode, newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow(row)

print(f"Appended {len(rows)} rows to {output}")
