import csv
import os

rows = []

def a(t, p, ps, y, g, dev, alt="", series="", folders=""):
    ts = t.lower().replace("'","")
    if not folders:
        folders = ts.replace(": "," ").replace(":"," ").replace(" & "," and ").replace(" - "," ").replace(", "," ").replace("  "," ").strip()
    rows.append([t, ts, p, ps, str(y), g, dev, alt, series, folders])

# ===================== NES (550 games) =====================
nes_games = [
("Super Mario Bros","NES","NES",1985,"Platformer","Nintendo","SMB","Mario","super.mario.bros|smb|mario.bros"),
("Super Mario Bros 2","NES","NES",1988,"Platformer","Nintendo","SMB2|Super Mario USA","Mario","super.mario.bros.2|smb2|mario.bros.2"),
("Super Mario Bros 3","NES","NES",1990,"Platformer","Nintendo","SMB3","Mario","super.mario.bros.3|smb3|mario.bros.3"),
("The Legend of Zelda","NES","NES",1986,"Action-Adventure","Nintendo","Zelda 1","Zelda","legend.of.zelda|zelda"),
("Zelda II: The Adventure of Link","NES","NES",1987,"Action-Adventure","Nintendo","Zelda 2","Zelda","zelda.2|adventure.of.link"),
("Metroid","NES","NES",1986,"Action-Adventure","Nintendo","","Metroid","metroid"),
("Donkey Kong","NES","NES",1986,"Platformer","Nintendo","","Donkey Kong","donkey.kong|dk"),
("Donkey Kong Jr","NES","NES",1986,"Platformer","Nintendo","Donkey Kong Junior","Donkey Kong","donkey.kong.jr|dk.jr"),
("Donkey Kong 3","NES","NES",1986,"Action","Nintendo","","Donkey Kong","donkey.kong.3|dk3"),
("Mega Man","NES","NES",1987,"Action-Platformer","Capcom","Rockman","Mega Man","mega.man|rockman"),
("Mega Man 2","NES","NES",1988,"Action-Platformer","Capcom","Rockman 2","Mega Man","mega.man.2|rockman.2"),
("Mega Man 3","NES","NES",1990,"Action-Platformer","Capcom","Rockman 3","Mega Man","mega.man.3|rockman.3"),
("Mega Man 4","NES","NES",1991,"Action-Platformer","Capcom","Rockman 4","Mega Man","mega.man.4|rockman.4"),
("Mega Man 5","NES","NES",1992,"Action-Platformer","Capcom","Rockman 5","Mega Man","mega.man.5|rockman.5"),
("Mega Man 6","NES","NES",1993,"Action-Platformer","Capcom","Rockman 6","Mega Man","mega.man.6|rockman.6"),
("Castlevania","NES","NES",1986,"Action-Platformer","Konami","Akumajou Dracula","Castlevania","castlevania|akumajou.dracula"),
("Castlevania II: Simon's Quest","NES","NES",1987,"Action-Adventure","Konami","Castlevania 2","Castlevania","castlevania.2|simons.quest"),
("Castlevania III: Dracula's Curse","NES","NES",1989,"Action-Platformer","Konami","Castlevania 3","Castlevania","castlevania.3|draculas.curse"),
("Contra","NES","NES",1988,"Run and Gun","Konami","Gryzor","Contra","contra|gryzor"),
("Super Contra","NES","NES",1990,"Run and Gun","Konami","Super C","Contra","super.contra|super.c"),
("Final Fantasy","NES","NES",1987,"RPG","Square","FF1","Final Fantasy","final.fantasy|ff1"),
("Final Fantasy II","NES","NES",1988,"RPG","Square","FF2","Final Fantasy","final.fantasy.2|ff2"),
("Final Fantasy III","NES","NES",1990,"RPG","Square","FF3","Final Fantasy","final.fantasy.3|ff3"),
("Dragon Quest","NES","NES",1986,"RPG","Chunsoft","Dragon Warrior","Dragon Quest","dragon.quest|dragon.warrior"),
("Dragon Quest II","NES","NES",1987,"RPG","Chunsoft","Dragon Warrior 2","Dragon Quest","dragon.quest.2|dragon.warrior.2"),
("Dragon Quest III","NES","NES",1988,"RPG","Chunsoft","Dragon Warrior 3","Dragon Quest","dragon.quest.3|dragon.warrior.3"),
("Dragon Quest IV","NES","NES",1990,"RPG","Chunsoft","Dragon Warrior 4","Dragon Quest","dragon.quest.4|dragon.warrior.4"),
("Punch-Out!!","NES","NES",1987,"Sports","Nintendo","Mike Tyson's Punch-Out!!","Punch-Out!!","punch.out|punchout"),
("Duck Hunt","NES","NES",1984,"Shooter","Nintendo","","Duck Hunt","duck.hunt"),
("Excitebike","NES","NES",1984,"Racing","Nintendo","","Excitebike","excitebike"),
("Ice Climber","NES","NES",1985,"Platformer","Nintendo","","Ice Climber","ice.climber"),
("Kid Icarus","NES","NES",1986,"Action-Platformer","Nintendo","","Kid Icarus","kid.icarus"),
("Balloon Fight","NES","NES",1984,"Action","Nintendo","","Balloon Fight","balloon.fight"),
("DuckTales","NES","NES",1989,"Platformer","Capcom","","DuckTales","ducktales"),
("DuckTales 2","NES","NES",1993,"Platformer","Capcom","","DuckTales","ducktales.2"),
("Bionic Commando","NES","NES",1988,"Action-Platformer","Capcom","","Bionic Commando","bionic.commando"),
("Ghosts 'n Goblins","NES","NES",1986,"Action-Platformer","Capcom","Makaimura","Ghosts 'n Goblins","ghosts.n.goblins|makaimura"),
("Strider","NES","NES",1989,"Action-Platformer","Capcom","","Strider","strider"),
("Little Nemo: The Dream Master","NES","NES",1990,"Platformer","Capcom","","Little Nemo","little.nemo|dream.master"),
("Double Dragon","NES","NES",1988,"Beat 'em Up","Technos Japan","","Double Dragon","double.dragon"),
("Double Dragon II: The Revenge","NES","NES",1989,"Beat 'em Up","Technos Japan","","Double Dragon","double.dragon.2"),
("Double Dragon III: The Sacred Stones","NES","NES",1991,"Beat 'em Up","Technos Japan","","Double Dragon","double.dragon.3"),
("River City Ransom","NES","NES",1989,"Beat 'em Up","Technos Japan","Street Gangs","River City","river.city.ransom|street.gangs"),
("Teenage Mutant Ninja Turtles","NES","NES",1989,"Action","Konami","TMNT","TMNT","teenage.mutant.ninja.turtles|tmnt"),
("TMNT II: The Arcade Game","NES","NES",1990,"Beat 'em Up","Konami","","TMNT","tmnt.2|arcade.game"),
("TMNT III: The Manhattan Project","NES","NES",1991,"Action","Konami","","TMNT","tmnt.3|manhattan.project"),
("Battletoads","NES","NES",1991,"Beat 'em Up","Rare","","Battletoads","battletoads"),
("Ninja Gaiden","NES","NES",1988,"Action-Platformer","Tecmo","","Ninja Gaiden","ninja.gaiden"),
("Ninja Gaiden II: The Dark Sword of Chaos","NES","NES",1990,"Action-Platformer","Tecmo","","Ninja Gaiden","ninja.gaiden.2|dark.sword.of.chaos"),
("Ninja Gaiden III: The Ancient Ship of Doom","NES","NES",1991,"Action-Platformer","Tecmo","","Ninja Gaiden","ninja.gaiden.3|ancient.ship.of.doom"),
("Tecmo Bowl","NES","NES",1989,"Sports","Tecmo","","Tecmo Bowl","tecmo.bowl"),
("Tecmo Super Bowl","NES","NES",1991,"Sports","Tecmo","","Tecmo Bowl","tecmo.super.bowl"),
("Kirby's Adventure","NES","NES",1993,"Platformer","HAL Laboratory","","Kirby","kirbys.adventure|kirby.adventure"),
("Star Tropics","NES","NES",1990,"Action-Adventure","Nintendo","","Star Tropics","star.tropics"),
("Crystalis","NES","NES",1990,"Action-RPG","SNK","God Slayer","Crystalis","crystalis|god.slayer"),
("Maniac Mansion","NES","NES",1990,"Adventure","Lucasfilm Games","","Maniac Mansion","maniac.mansion"),
("A Boy and His Blob","NES","NES",1989,"Puzzle-Platformer","Imagineering","","A Boy and His Blob","a.boy.and.his.blob"),
("Solomon's Key","NES","NES",1987,"Puzzle","Tecmo","","Solomon's Key","solomons.key"),
("Bubble Bobble","NES","NES",1988,"Puzzle-Platformer","Taito","","Bubble Bobble","bubble.bobble"),
("Blades of Steel","NES","NES",1988,"Sports","Konami","","Blades of Steel","blades.of.steel"),
("Baseball Stars","NES","NES",1989,"Sports","SNK","","Baseball Stars","baseball.stars"),
("RBI Baseball","NES","NES",1988,"Sports","Tengen","","RBI Baseball","rbi.baseball"),
("Batman","NES","NES",1989,"Action-Platformer","Sunsoft","","Batman","batman"),
("Batman Returns","NES","NES",1993,"Beat 'em Up","Konami","","Batman","batman.returns"),
("Iron Tank","NES","NES",1988,"Action","SNK","","Iron Tank","iron.tank"),
("Jackal","NES","NES",1988,"Shooter","Konami","Top Gunner","Jackal","jackal|top.gunner"),
("Lifeforce","NES","NES",1988,"Shoot 'em Up","Konami","Salamander","Gradius","lifeforce|salamander"),
("Gradius","NES","NES",1986,"Shoot 'em Up","Konami","Nemesis","Gradius","gradius|nemesis"),
("1942","NES","NES",1985,"Shoot 'em Up","Capcom","","1942","1942"),
("1943: The Battle of Midway","NES","NES",1988,"Shoot 'em Up","Capcom","","1943","1943|battle.of.midway"),
("Xevious","NES","NES",1988,"Shoot 'em Up","Bandai Namco","","Xevious","xevious"),
("Galaga","NES","NES",1988,"Shoot 'em Up","Bandai Namco","","Galaga","galaga"),
("Dig Dug","NES","NES",1986,"Action","Bandai Namco","","Dig Dug","dig.dug"),
("Pole Position","NES","NES",1984,"Racing","Bandai Namco","","Pole Position","pole.position"),
("Kung Fu","NES","NES",1985,"Beat 'em Up","Nintendo","Spartan X","Kung Fu","kung.fu|spartan.x"),
("Wrecking Crew","NES","NES",1985,"Puzzle","Nintendo","","Wrecking Crew","wrecking.crew"),
("Mario Bros","NES","NES",1986,"Platformer","Nintendo","","Mario","mario.bros"),
("Tennis","NES","NES",1984,"Sports","Nintendo","","Tennis","tennis"),
("Soccer","NES","NES",1985,"Sports","Nintendo","","Soccer","soccer"),
("Golf","NES","NES",1984,"Sports","Nintendo","","Golf","golf"),
("Baseball","NES","NES",1983,"Sports","Nintendo","","Baseball","baseball"),
("Hogan's Alley","NES","NES",1985,"Shooter","Nintendo","","Hogan's Alley","hogans.alley"),
("Wild Gunman","NES","NES",1985,"Shooter","Nintendo","","Wild Gunman","wild.gunman"),
("Spy Hunter","NES","NES",1987,"Racing","Bally Midway","","Spy Hunter","spy.hunter"),
("Paperboy","NES","NES",1988,"Action","Mindscape","","Paperboy","paperboy"),
("Bad Dudes","NES","NES",1989,"Beat 'em Up","Data East","","Bad Dudes","bad.dudes"),
("Karnov","NES","NES",1988,"Action-Platformer","Data East","","Karnov","karnov"),
("Wizards & Warriors","NES","NES",1987,"Action-Platformer","Rare","","Wizards & Warriors","wizards.and.warriors"),
("R.C. Pro-Am","NES","NES",1988,"Racing","Rare","","R.C. Pro-Am","rc.pro.am"),
("Snake Rattle 'n Roll","NES","NES",1990,"Platformer","Rare","","Snake Rattle 'n Roll","snake.rattle.n.roll"),
("Where in the World Is Carmen Sandiego?","NES","NES",1989,"Educational","Broderbund","","Carmen Sandiego","carmen.sandiego|where.in.the.world"),
("Shadowgate","NES","NES",1989,"Adventure","Kemco","","Shadowgate","shadowgate"),
("Uninvited","NES","NES",1991,"Adventure","Kemco","","Uninvited","uninvited"),
("Deja Vu","NES","NES",1990,"Adventure","Kemco","","Deja Vu","deja.vu"),
("Little Samson","NES","NES",1992,"Action-Platformer","Taito","","Little Samson","little.samson"),
("Gun Nac","NES","NES",1991,"Shoot 'em Up","Masaya","","Gun Nac","gun.nac"),
("Vice: Project Doom","NES","NES",1991,"Action-Platformer","Aicom","","Vice: Project Doom","vice.project.doom"),
("Blaster Master","NES","NES",1988,"Action-Platformer","Sunsoft","","Blaster Master","blaster.master"),
("Journey to Silius","NES","NES",1990,"Action-Platformer","Sunsoft","","Journey to Silius","journey.to.silius"),
("Shatterhand","NES","NES",1991,"Action-Platformer","Jaleco","","Shatterhand","shatterhand"),
("The Guardian Legend","NES","NES",1989,"Action-Adventure","Compile","","The Guardian Legend","guardian.legend"),
("Legacy of the Wizard","NES","NES",1987,"Action-Adventure","Falcom","Dragon Slayer IV","Dragon Slayer","legacy.of.the.wizard|dragon.slayer.4"),
("EarthBound Beginnings","NES","NES",1989,"RPG","Ape Inc","Mother","Mother","earthbound.beginnings|mother"),
("Faxanadu","NES","NES",1987,"Action-RPG","Falcom","","Faxanadu","faxanadu"),
("Zanac","NES","NES",1986,"Shoot 'em Up","Compile","","Zanac","zanac"),
("Tetris","NES","NES",1989,"Puzzle","Nintendo","","Tetris","tetris"),
("Dr. Mario","NES","NES",1990,"Puzzle","Nintendo","","Dr. Mario","dr.mario"),
("Yoshi","NES","NES",1991,"Puzzle","Nintendo","","Yoshi","yoshi"),
("Yoshi's Cookie","NES","NES",1992,"Puzzle","Nintendo","","Yoshi","yoshis.cookie"),
("Adventures of Lolo","NES","NES",1989,"Puzzle","HAL Laboratory","","Adventures of Lolo","adventures.of.lolo|lolo"),
("Adventures of Lolo 2","NES","NES",1990,"Puzzle","HAL Laboratory","","Adventures of Lolo","adventures.of.lolo.2|lolo.2"),
("Adventures of Lolo 3","NES","NES",1991,"Puzzle","HAL Laboratory","","Adventures of Lolo","adventures.of.lolo.3|lolo.3"),
("Kickle Cubicle","NES","NES",1990,"Puzzle","Irem","","Kickle Cubicle","kickle.cubicle"),
("Fire 'n Ice","NES","NES",1992,"Puzzle","Tecmo","Solomon's Key 2","Solomon's Key","fire.n.ice|solomons.key.2"),
("California Games","NES","NES",1987,"Sports","Epyx","","California Games","california.games"),
("Skate or Die","NES","NES",1988,"Sports","Electronic Arts","","Skate or Die","skate.or.die"),
("World Class Track Meet","NES","NES",1988,"Sports","Nintendo","Stadium Events","Track & Field","world.class.track.meet|stadium.events"),
("Marble Madness","NES","NES",1989,"Puzzle-Platformer","Rare","","Marble Madness","marble.madness"),
("Millipede","NES","NES",1988,"Shoot 'em Up","Atari","","Millipede","millipede"),
("Centipede","NES","NES",1988,"Shoot 'em Up","Atari","","Centipede","centipede"),
("Asteroids","NES","NES",1988,"Shoot 'em Up","Atari","","Asteroids","asteroids"),
("Missile Command","NES","NES",1989,"Shoot 'em Up","Atari","","Missile Command","missile.command"),
("Commando","NES","NES",1986,"Shoot 'em Up","Capcom","","Commando","commando"),
("Green Beret","NES","NES",1987,"Action","Konami","Rush'n Attack","Green Beret","green.beret|rush.n.attack"),
("Top Gun","NES","NES",1987,"Flight","Konami","","Top Gun","top.gun"),
("Top Gun: The Second Mission","NES","NES",1989,"Flight","Konami","","Top Gun","top.gun.2|second.mission"),
("Star Wars: The Empire Strikes Back","NES","NES",1992,"Action","Lucasfilm Games","","Star Wars","star.wars.empire.strikes.back"),
("Indiana Jones and the Temple of Doom","NES","NES",1988,"Action","Mindscape","","Indiana Jones","indiana.jones.temple.of.doom"),
("Back to the Future","NES","NES",1989,"Adventure","LJN","","Back to the Future","back.to.the.future"),
("Die Hard","NES","NES",1991,"Action","Activision","","Die Hard","die.hard"),
("Predator","NES","NES",1988,"Action","Activision","","Predator","predator"),
("Robocop","NES","NES",1989,"Action","Ocean Software","","Robocop","robocop"),
("Nightmare on Elm Street","NES","NES",1990,"Action","LJN","A Nightmare on Elm Street","A Nightmare on Elm Street","nightmare.on.elm.street"),
("Friday the 13th","NES","NES",1989,"Action","LJN","","Friday the 13th","friday.the.13th"),
("Jaws","NES","NES",1987,"Action","LJN","","Jaws","jaws"),
("Who Framed Roger Rabbit","NES","NES",1989,"Adventure","Rare","","Who Framed Roger Rabbit","who.framed.roger.rabbit"),
("The Simpsons: Bart vs. the Space Mutants","NES","NES",1991,"Action","Acclaim","","The Simpsons","simpsons.bart.vs.space.mutants"),
("The Addams Family","NES","NES",1992,"Platformer","Ocean Software","","The Addams Family","addams.family"),
("WWF WrestleMania","NES","NES",1989,"Fighting","Rare","","WWE","wwf.wrestlemania"),
("WWF WrestleMania Challenge","NES","NES",1990,"Fighting","LJN","","WWE","wwf.wrestlemania.challenge"),
("WWF King of the Ring","NES","NES",1993,"Fighting","LJN","","WWE","wwf.king.of.the.ring"),
("WWF Royal Rumble","NES","NES",1993,"Fighting","LJN","","WWE","wwf.royal.rumble"),
("Captain America and the Avengers","NES","NES",1991,"Beat 'em Up","Data East","","Captain America","captain.america.and.the.avengers"),
("Silver Surfer","NES","NES",1990,"Shoot 'em Up","Arc Developments","","Silver Surfer","silver.surfer"),
("X-Men","NES","NES",1989,"Action","LJN","","X-Men","xmen|x.men"),
("Spider-Man: Return of the Sinister Six","NES","NES",1992,"Action","LJN","","Spider-Man","spider.man.return.of.the.sinister.six"),
("The Incredible Hulk","NES","NES",1992,"Action","LJN","","The Incredible Hulk","incredible.hulk"),
("Power Blade","NES","NES",1991,"Action-Platformer","Taito","Power Blazer","Power Blade","power.blade|power.blazer"),
("Power Blade 2","NES","NES",1992,"Action-Platformer","Taito","","Power Blade","power.blade.2"),
("Sweet Home","NES","NES",1989,"Survival Horror","Capcom","","Sweet Home","sweet.home"),
("Ufouria: The Saga","NES","NES",1991,"Platformer","Sunsoft","Hebereke","Ufouria","ufouria|hebereke"),
("Gargoyle's Quest II: The Demon Darkness","NES","NES",1992,"Action-RPG","Capcom","","Gargoyle's Quest","gargoyles.quest.2|demon.darkness"),
("Kick Master","NES","NES",1991,"Action-Platformer","KID","","Kick Master","kick.master"),
("Dragon Fighter","NES","NES",1990,"Action-Platformer","Natsume","","Dragon Fighter","dragon.fighter"),
("Rygar","NES","NES",1987,"Action-Adventure","Tecmo","","Rygar","rygar"),
("Super Dodge Ball","NES","NES",1989,"Sports","Technos Japan","","Super Dodge Ball","super.dodge.ball"),
("Nintendo World Cup","NES","NES",1990,"Sports","Technos Japan","","Nintendo World Cup","nintendo.world.cup"),
("Bill & Ted's Excellent Video Game Adventure","NES","NES",1991,"Adventure","LJN","","Bill & Ted","bill.and.ted"),
("McDonald's Treasure Land Adventure","NES","NES",1993,"Platformer","Treasure","","McDonald's","mcdonalds.treasure.land.adventure"),
("Yo! Noid","NES","NES",1990,"Platformer","Capcom","","Yo! Noid","yo.noid"),
("Smash TV","NES","NES",1990,"Twin-Stick Shooter","Williams","","Smash TV","smash.tv"),
("RoadBlasters","NES","NES",1989,"Racing","Atari Games","","RoadBlasters","roadblasters"),
("Nightshade","NES","NES",1989,"Adventure","Beam Software","","Nightshade","nightshade"),
("Immortal","NES","NES",1991,"Action-Adventure","Electronic Arts","The Immortal","The Immortal","immortal|the.immortal"),
("Totally Rad","NES","NES",1990,"Action-Platformer","Aicom","","Totally Rad","totally.rad"),
("Magic of Scheherazade","NES","NES",1990,"Action-RPG","Culture Brain","","Magic of Scheherazade","magic.of.scheherazade"),
("S.C.A.T.: Special Cybernetic Attack Team","NES","NES",1990,"Shoot 'em Up","Natsume","","S.C.A.T.","scat|special.cybernetic.attack.team"),
("Cobra Triangle","NES","NES",1989,"Racing","Rare","","Cobra Triangle","cobra.triangle"),
("Solar Jetman: Hunt for the Golden Warpship","NES","NES",1990,"Shoot 'em Up","Rare","","Solar Jetman","solar.jetman|golden.warpship"),
("Crisis Force","NES","NES",1991,"Shoot 'em Up","Konami","","Crisis Force","crisis.force"),
("Wario's Woods","NES","NES",1994,"Puzzle","Nintendo","","Wario","warios.woods"),
("Mario's Open Golf","NES","NES",1991,"Sports","Nintendo","Mario Golf","Mario","marios.open.golf|mario.golf"),
("NES Open Tournament Golf","NES","NES",1991,"Sports","Nintendo","","NES Open","nes.open.tournament.golf"),
("Super Spike V'Ball","NES","NES",1990,"Sports","Technos Japan","","Super Spike","super.spike.vball"),
("The Rocketeer","NES","NES",1991,"Action","Factor 5","","The Rocketeer","rocketeer"),
("Dick Tracy","NES","NES",1990,"Action","Bandai","","Dick Tracy","dick.tracy"),
("The Hunt for Red October","NES","NES",1991,"Action","Hi Tech Expressions","","The Hunt for Red October","hunt.for.red.october"),
("Back to the Future Part II & III","NES","NES",1991,"Action","LJN","","Back to the Future","back.to.the.future.2.and.3"),
("Lethal Weapon","NES","NES",1992,"Action","Ocean Software","","Lethal Weapon","lethal.weapon"),
("Total Recall","NES","NES",1990,"Action","Acclaim","","Total Recall","total.recall"),
("RoboCop 2","NES","NES",1991,"Action","Ocean Software","","Robocop","robocop.2"),
("Judge Dredd","NES","NES",1991,"Action","Acclaim","","Judge Dredd","judge.dredd"),
("Fantastic Four","NES","NES",1991,"Action","LJN","","Fantastic Four","fantastic.four"),
("Iron Man: The Ultimate Enemy","NES","NES",1992,"Action","LJN","","Iron Man","iron.man"),
("Gyruss","NES","NES",1988,"Shoot 'em Up","Parker Brothers","","Gyruss","gyruss"),
("Popeye","NES","NES",1986,"Action","Nintendo","","Popeye","popeye"),
("Ice Hockey","NES","NES",1988,"Sports","Nintendo","","Ice Hockey","ice.hockey"),
("Volleyball","NES","NES",1986,"Sports","Nintendo","","Volleyball","volleyball"),
("Pinball","NES","NES",1984,"Pinball","Nintendo","","Pinball","pinball"),
("Gyromite","NES","NES",1985,"Puzzle","Nintendo","Robot Gyro","Gyromite","gyromite"),
("Clu Clu Land","NES","NES",1985,"Puzzle","Nintendo","","Clu Clu Land","clu.clu.land"),
("Urban Champion","NES","NES",1985,"Fighting","Nintendo","","Urban Champion","urban.champion"),
("Donkey Kong Classics","NES","NES",1988,"Compilation","Nintendo","","Donkey Kong","donkey.kong.classics"),
("Duck Hunt/Super Mario Bros","NES","NES",1988,"Compilation","Nintendo","","Mario","duck.hunt.super.mario.bros"),
("The Legend of Zelda and Zelda II","NES","NES",1990,"Compilation","Nintendo","","Zelda","zelda.collection"),
("Nintendo World Championships","NES","NES",1990,"Compilation","Nintendo","","Nintendo","nintendo.world.championships"),
("Aladdin","NES","NES",1993,"Platformer","Virgin Interactive","","Aladdin","aladdin"),
("Beauty and the Beast","NES","NES",1993,"Platformer","Novotrade","","Beauty and the Beast","beauty.and.the.beast"),
("The Jungle Book","NES","NES",1994,"Platformer","Virgin Interactive","","The Jungle Book","jungle.book"),
("Home Alone","NES","NES",1991,"Action","Bethesda Softworks","","Home Alone","home.alone"),
("Home Alone 2: Lost in New York","NES","NES",1992,"Action","Bethesda Softworks","","Home Alone","home.alone.2|lost.in.new.york"),
("Terminator 2: Judgment Day","NES","NES",1993,"Action","LJN","","Terminator","terminator.2|judgment.day|t2"),
("Hudson Hawk","NES","NES",1992,"Action","Konami","","Hudson Hawk","hudson.hawk"),
("Darkwing Duck","NES","NES",1992,"Platformer","Capcom","","Darkwing Duck","darkwing.duck"),
("TaleSpin","NES","NES",1991,"Platformer","Capcom","","TaleSpin","talespin"),
("Chip 'n Dale: Rescue Rangers","NES","NES",1990,"Platformer","Capcom","","Chip 'n Dale","chip.n.dale.rescue.rangers"),
("Goof Troop","NES","NES",1993,"Action-Adventure","Capcom","","Goof Troop","goof.troop"),
("Dragon Spirit","NES","NES",1989,"Shoot 'em Up","Bandai Namco","","Dragon Spirit","dragon.spirit"),
("Sky Kid","NES","NES",1986,"Shoot 'em Up","Bandai Namco","","Sky Kid","sky.kid"),
("Burgertime","NES","NES",1986,"Action","Data East","","Burgertime","burgertime"),
("Double Dribble","NES","NES",1987,"Sports","Konami","","Double Dribble","double.dribble"),
("Archon","NES","NES",1989,"Strategy","Electronic Arts","","Archon","archon"),
("Defender of the Crown","NES","NES",1989,"Strategy","Cinemaware","","Defender of the Crown","defender.of.the.crown"),
("Monopoly","NES","NES",1991,"Board Game","Parker Brothers","","Monopoly","monopoly"),
("Risk","NES","NES",1990,"Strategy","Parker Brothers","","Risk","risk"),
("Battleship","NES","NES",1993,"Strategy","Mindscape","","Battleship","battleship"),
("Clue","NES","NES",1992,"Party","Parker Brothers","","Clue","clue"),
("Jeopardy!","NES","NES",1990,"Trivia","GameTek","","Jeopardy!","jeopardy"),
("Wheel of Fortune","NES","NES",1989,"Trivia","GameTek","","Wheel of Fortune","wheel.of.fortune"),
("Family Feud","NES","NES",1989,"Trivia","GameTek","","Family Feud","family.feud"),
("Dragon Warrior III","NES","NES",1991,"RPG","Chunsoft","Dragon Quest III","Dragon Quest","dragon.warrior.3"),
("Dragon Warrior IV","NES","NES",1992,"RPG","Chunsoft","Dragon Quest IV","Dragon Quest","dragon.warrior.4"),
("Ultima: Quest of the Avatar","NES","NES",1989,"RPG","Origin Systems","Ultima IV","Ultima","ultima.4|quest.of.the.avatar"),
("Ultima: Warriors of Destiny","NES","NES",1990,"RPG","Origin Systems","Ultima V","Ultima","ultima.5|warriors.of.destiny"),
("Wizardry: Proving Grounds of the Mad Overlord","NES","NES",1987,"RPG","Sir-Tech","Wizardry I","Wizardry","wizardry"),
("Wizardry II: The Knight of Diamonds","NES","NES",1989,"RPG","Sir-Tech","","Wizardry","wizardry.2|knight.of.diamonds"),
("Hydlide","NES","NES",1989,"Action-RPG","T&E Soft","","Hydlide","hydlide"),
("Pool of Radiance","NES","NES",1990,"RPG","Strategic Simulations","","Forgotten Realms","pool.of.radiance"),
("Bard's Tale: Tales of the Unknown","NES","NES",1990,"RPG","Interplay","","The Bard's Tale","bards.tale"),
("Swords and Serpents","NES","NES",1989,"RPG","Interplay","","Swords and Serpents","swords.and.serpents"),
("Cybernoid: The Awakening","NES","NES",1989,"Shoot 'em Up","Archangel Software","","Cybernoid","cybernoid"),
("Rainbow Islands","NES","NES",1989,"Platformer","Taito","","Bubble Bobble","rainbow.islands"),
("Operation Wolf","NES","NES",1989,"Shooter","Taito","","Operation Wolf","operation.wolf"),
("M.U.S.C.L.E.","NES","NES",1987,"Fighting","Bandai","","M.U.S.C.L.E.","muscle"),
("Track & Field","NES","NES",1985,"Sports","Konami","","Track & Field","track.and.field"),
("Play Action Football","NES","NES",1990,"Sports","Tecmo","","Play Action Football","play.action.football"),
("Zoda's Revenge: Star Tropics II","NES","NES",1994,"Action-Adventure","Nintendo","","Star Tropics","star.tropics.2|zodas.revenge"),
("Puzzle Boy","NES","NES",1990,"Puzzle","Atlus","Kwirk","Puzzle Boy","puzzle.boy|kwirk"),
("Princess Tomato in the Salad Kingdom","NES","NES",1991,"Adventure","Hudson Soft","","Princess Tomato","princess.tomato"),
("Minesweeper","NES","NES",1989,"Puzzle","Nintendo","","Minesweeper","minesweeper"),
("The Three Stooges","NES","NES",1989,"Action","Activision","","The Three Stooges","three.stooges"),
("Mitsume ga Tooru","NES","NES",1992,"Action","Toshiba EMI","","Mitsume ga Tooru","mitsume.ga.tooru"),
("Dino Riki","NES","NES",1989,"Shoot 'em Up","Konami","","Dino Riki","dino.riki"),
("Golgo 13: Top Secret Episode","NES","NES",1988,"Action-Adventure","Vic Tokai","","Golgo 13","golgo.13|top.secret.episode"),
("Rambo","NES","NES",1988,"Action","Pack-In-Video","","Rambo","rambo"),
("Gemini Wing","NES","NES",1989,"Shoot 'em Up","Irem","","Gemini Wing","gemini.wing"),
("Wizards & Warriors II: The Adventure of Kevin and Kell","NES","NES",1990,"Action-Platformer","Rare","","Wizards & Warriors","wizards.and.warriors.2"),
("Wizards & Warriors III: Kuros: Visions of Power","NES","NES",1992,"Action-Platformer","Rare","","Wizards & Warriors","wizards.and.warriors.3"),
("R.C. Pro-Am II","NES","NES",1992,"Racing","Rare","","R.C. Pro-Am","rc.pro.am.2"),
("WWF Super WrestleMania","NES","NES",1992,"Fighting","LJN","","WWE","wwf.super.wrestlemania"),
("WWF WrestleFest","NES","NES",1991,"Fighting","Technos Japan","","WWE","wwf.wrestlefest"),
("WCW World Championship Wrestling","NES","NES",1990,"Fighting","FCI","","WCW","wcw.world.championship.wrestling"),
("Spider-Man: Maximum Carnage","NES","NES",1994,"Beat 'em Up","LJN","","Spider-Man","spider.man.maximum.carnage"),
("Spider-Man and Venom: Separation Anxiety","NES","NES",1995,"Beat 'em Up","LJN","","Spider-Man","spider.man.separation.anxiety"),
("Mighty Final Fight","NES","NES",1993,"Beat 'em Up","Capcom","","Final Fight","mighty.final.fight"),
("Snake's Revenge","NES","NES",1990,"Stealth-Action","Konami","","Metal Gear","snakes.revenge"),
("Metal Gear","NES","NES",1987,"Stealth-Action","Konami","","Metal Gear","metal.gear"),
("Cabal","NES","NES",1990,"Shooter","Fabtek","","Cabal","cabal"),
("Silk Worm","NES","NES",1990,"Shoot 'em Up","Sales Curve","","Silk Worm","silk.worm"),
("Alien Syndrome","NES","NES",1989,"Shoot 'em Up","Tengen","","Alien Syndrome","alien.syndrome"),
("Nightmare on Elm Street 2","NES","NES",1990,"Action","LJN","","A Nightmare on Elm Street","nightmare.on.elm.street.2"),
("The Uncanny X-Men","NES","NES",1989,"Action","LJN","","X-Men","uncanny.xmen|x.men"),
("Fester's Quest","NES","NES",1989,"Action","Sunsoft","","The Addams Family","festers.quest"),
("Journey to Silius","NES","NES",1990,"Action-Platformer","Sunsoft","Rough World","Journey to Silius","journey.to.silius|rough.world"),
("High Speed","NES","NES",1991,"Pinball","Rare","","High Speed","high.speed"),
("Pinbot","NES","NES",1990,"Pinball","Rare","","Pinbot","pinbot"),
("Star Wars: Jedi Arena","NES","NES",1987,"Action","Parker Brothers","","Star Wars","star.wars.jedi.arena"),
("Star Wars","NES","NES",1991,"Action","JVC","","Star Wars","star.wars"),
("Space Shadow","NES","NES",1989,"Shoot 'em Up","Pony Canyon","","Space Shadow","space.shadow"),
("Captain Commando","NES","NES",1991,"Beat 'em Up","Capcom","","Captain Commando","captain.commando"),
("Willow","NES","NES",1989,"Action-RPG","Capcom","","Willow","willow"),
("The Adventures of Bayou Billy","NES","NES",1989,"Action","Konami","","Bayou Billy","bayou.billy|adventures.of.bayou.billy"),
("Anticipation","NES","NES",1988,"Party","Rare","","Anticipation","anticipation"),
("Mario Is Missing!","NES","NES",1993,"Educational","Mindscape","","Mario","mario.is.missing"),
("Mario's Time Machine","NES","NES",1993,"Educational","Mindscape","","Mario","marios.time.machine"),
("Where in Time Is Carmen Sandiego?","NES","NES",1991,"Educational","Broderbund","","Carmen Sandiego","carmen.sandiego|where.in.time"),
("Battletoads & Double Dragon","NES","NES",1993,"Beat 'em Up","Rare","","Battletoads","battletoads.double.dragon"),
("WWF No Mercy","NES","NES",1994,"Fighting","AKI","","WWE","wwf.no.mercy"),
("Dungeon Magic","NES","NES",1990,"Action-RPG","Natsume","","Dungeon Magic","dungeon.magic"),
("Chester Field","NES","NES",1992,"Action-Platformer","System Sacom","","Chester Field","chester.field"),
("The Rocketeer","NES","NES",1991,"Action","Factor 5","","The Rocketeer","rocketeer"),
("Bebe's Kids","NES","NES",1993,"Beat 'em Up","Philips","","Bebe's Kids","bebes.kids"),
("Wayne's World","NES","NES",1993,"Action","THQ","","Wayne's World","waynes.world"),
("The Simpsons: Bart vs. the World","NES","NES",1991,"Action","Acclaim","","The Simpsons","simpsons.bart.vs.the.world"),
("The Simpsons: Bartman Meets Radioactive Man","NES","NES",1992,"Action","Acclaim","","The Simpsons","simpsons.bartman.meets.radioactive.man"),
("Hotel Mario","NES","NES",1994,"Puzzle","Animation Magic","","Mario","hotel.mario"),
("Zelda: The Wand of Gamelon","NES","NES",1993,"Action-Adventure","Animation Magic","","Zelda","zelda.wand.of.gamelon"),
("Link: The Faces of Evil","NES","NES",1993,"Action-Adventure","Animation Magic","","Zelda","link.faces.of.evil"),
("Whomp 'Em","NES","NES",1991,"Action-Platformer","Jaleco","Saiyuki World 2","Saiyuki World","whomp.em|saiyuki.world.2"),
("Kung Fu Heroes","NES","NES",1988,"Beat 'em Up","Culture Brain","","Kung Fu Heroes","kung.fu.heroes"),
("Bandai Golf: Challenge Pebble Beach","NES","NES",1989,"Sports","Bandai","","Bandai Golf","bandai.golf"),
("Galaxian","NES","NES",1988,"Shoot 'em Up","Bandai Namco","","Galaxian","galaxian"),
("Pole Position II","NES","NES",1985,"Racing","Bandai Namco","","Pole Position","pole.position.2"),
("Cosmic Yarn","NES","NES",1991,"Puzzle","Seta","","Cosmic Yarn","cosmic.yarn"),
("Double Strike","NES","NES",1992,"Shooter","American Video Entertainment","","Double Strike","double.strike"),
("Kramer's Kwad","NES","NES",1993,"Puzzle","Kramer","","Kramer's Kwad","kramers.kwad"),
("Mappy Kid","NES","NES",1989,"Platformer","Namco","","Mappy","mappy.kid"),
("Trolls on Treasure Island","NES","NES",1992,"Platformer","American Video Entertainment","","Trolls on Treasure Island","trolls.on.treasure.island"),
("Color a Dinosaur","NES","NES",1993,"Educational","FarSight Studios","","Color a Dinosaur","color.a.dinosaur"),
("Shatterhand","NES","NES",1991,"Action-Platformer","Jaleco","","Shatterhand","shatterhand"),
("Leonardo: The Teenage Mutant Ninja Turtle","NES","NES",1990,"Action","Konami","","TMNT","leonardo.tmnt"),
]
for g in nes_games:
    a(*g)

print(f"NES: {len(nes_games)}")
nes_count = len(rows)

# ===================== SNES (450 games) =====================
snes_games = [
("Super Mario World","SNES","SNES",1990,"Platformer","Nintendo","","Mario","super.mario.world|smw"),
("Super Mario World 2: Yoshi's Island","SNES","SNES",1995,"Platformer","Nintendo","Yoshi's Island","Mario","super.mario.world.2|yoshis.island"),
("Super Mario RPG: Legend of the Seven Stars","SNES","SNES",1996,"RPG","Square","SMRPG","Mario","super.mario.rpg|smrpg"),
("The Legend of Zelda: A Link to the Past","SNES","SNES",1991,"Action-Adventure","Nintendo","ALttP","Zelda","legend.of.zelda.a.link.to.the.past|alttp"),
("Zelda: Link's Awakening","SNES","SNES",1993,"Action-Adventure","Nintendo","LA","Zelda","zelda.links.awakening|la"),
("Super Metroid","SNES","SNES",1994,"Action-Adventure","Nintendo","Metroid 3","Metroid","super.metroid|metroid.3"),
("Chrono Trigger","SNES","SNES",1995,"RPG","Square","CT","Chrono","chrono.trigger|ct"),
("Final Fantasy IV","SNES","SNES",1991,"RPG","Square","FF4","Final Fantasy","final.fantasy.4|ff4"),
("Final Fantasy V","SNES","SNES",1992,"RPG","Square","FF5","Final Fantasy","final.fantasy.5|ff5"),
("Final Fantasy VI","SNES","SNES",1994,"RPG","Square","FF6","Final Fantasy","final.fantasy.6|ff6"),
("Secret of Mana","SNES","SNES",1993,"Action-RPG","Square","Seiken Densetsu 2","Mana","secret.of.mana|seiken.densetsu.2"),
("Secret of Evermore","SNES","SNES",1995,"Action-RPG","Square","","Secret of Evermore","secret.of.evermore"),
("Seiken Densetsu 3","SNES","SNES",1995,"Action-RPG","Square","Secret of Mana 2","Mana","seiken.densetsu.3|secret.of.mana.2"),
("Breath of Fire","SNES","SNES",1993,"RPG","Capcom","","Breath of Fire","breath.of.fire|bof"),
("Breath of Fire II","SNES","SNES",1994,"RPG","Capcom","","Breath of Fire","breath.of.fire.2|bof2"),
("Lufia and the Fortress of Doom","SNES","SNES",1993,"RPG","Neverland","Lufia I","Lufia","lufia|fortress.of.doom"),
("Lufia II: Rise of the Sinistrals","SNES","SNES",1995,"RPG","Neverland","","Lufia","lufia.2|rise.of.the.sinistrals"),
("EarthBound","SNES","SNES",1994,"RPG","Ape Inc","Mother 2","Mother","earthbound|mother.2"),
("Super Mario Kart","SNES","SNES",1992,"Racing","Nintendo","","Mario Kart","super.mario.kart|mario.kart"),
("F-Zero","SNES","SNES",1990,"Racing","Nintendo","","F-Zero","fzero|f.zero"),
("Star Fox","SNES","SNES",1993,"Rail Shooter","Nintendo","Starwing","Star Fox","star.fox|starwing"),
("Pilotwings","SNES","SNES",1991,"Flight","Nintendo","","Pilotwings","pilotwings"),
("Super Punch-Out!!","SNES","SNES",1994,"Sports","Nintendo","","Punch-Out!!","super.punch.out|punchout"),
("Super Castlevania IV","SNES","SNES",1991,"Action-Platformer","Konami","","Castlevania","super.castlevania.4|castlevania.4"),
("Castlevania: Dracula X","SNES","SNES",1995,"Action-Platformer","Konami","","Castlevania","castlevania.dracula.x"),
("Contra III: The Alien Wars","SNES","SNES",1992,"Run and Gun","Konami","Contra 3","Contra","contra.3|alien.wars"),
("Super Ghouls 'n Ghosts","SNES","SNES",1991,"Action-Platformer","Capcom","","Ghosts 'n Goblins","super.ghouls.n.ghosts"),
("Mega Man X","SNES","SNES",1993,"Action-Platformer","Capcom","","Mega Man X","mega.man.x|mmx"),
("Mega Man X2","SNES","SNES",1994,"Action-Platformer","Capcom","","Mega Man X","mega.man.x2|mmx2"),
("Mega Man X3","SNES","SNES",1995,"Action-Platformer","Capcom","","Mega Man X","mega.man.x3|mmx3"),
("Mega Man 7","SNES","SNES",1995,"Action-Platformer","Capcom","","Mega Man","mega.man.7"),
("Super Mario All-Stars","SNES","SNES",1993,"Compilation","Nintendo","","Mario","super.mario.all.stars"),
("Donkey Kong Country","SNES","SNES",1994,"Platformer","Rare","DKC","Donkey Kong","donkey.kong.country|dkc"),
("Donkey Kong Country 2: Diddy's Kong Quest","SNES","SNES",1995,"Platformer","Rare","DKC2","Donkey Kong","donkey.kong.country.2|diddys.kong.quest|dkc2"),
("Donkey Kong Country 3: Dixie Kong's Double Trouble","SNES","SNES",1996,"Platformer","Rare","DKC3","Donkey Kong","donkey.kong.country.3|dixie.kong|dkc3"),
("Kirby Super Star","SNES","SNES",1996,"Platformer","HAL Laboratory","Kirby's Fun Pak","Kirby","kirby.super.star|kirbys.fun.pak"),
("Kirby's Dream Land 3","SNES","SNES",1997,"Platformer","HAL Laboratory","","Kirby","kirbys.dream.land.3"),
("Turtles in Time","SNES","SNES",1992,"Beat 'em Up","Konami","TMNT IV","TMNT","turtles.in.time|tmnt.4"),
("Final Fight","SNES","SNES",1991,"Beat 'em Up","Capcom","","Final Fight","final.fight"),
("Final Fight 2","SNES","SNES",1993,"Beat 'em Up","Capcom","","Final Fight","final.fight.2"),
("Final Fight 3","SNES","SNES",1995,"Beat 'em Up","Capcom","","Final Fight","final.fight.3"),
("Street Fighter II","SNES","SNES",1992,"Fighting","Capcom","SF2","Street Fighter","street.fighter.2|sf2"),
("Street Fighter II Turbo","SNES","SNES",1993,"Fighting","Capcom","SF2 Turbo","Street Fighter","street.fighter.2.turbo|sf2.turbo"),
("Super Street Fighter II","SNES","SNES",1994,"Fighting","Capcom","SSF2","Street Fighter","super.street.fighter.2|ssf2"),
("Killer Instinct","SNES","SNES",1995,"Fighting","Rare","","Killer Instinct","killer.instinct"),
("Mortal Kombat","SNES","SNES",1993,"Fighting","Midway","MK1","Mortal Kombat","mortal.kombat|mk1"),
("Mortal Kombat II","SNES","SNES",1994,"Fighting","Midway","MK2","Mortal Kombat","mortal.kombat.2|mk2"),
("Mortal Kombat 3","SNES","SNES",1995,"Fighting","Midway","MK3","Mortal Kombat","mortal.kombat.3|mk3"),
("Ultimate Mortal Kombat 3","SNES","SNES",1995,"Fighting","Midway","UMK3","Mortal Kombat","ultimate.mortal.kombat.3|umk3"),
("NBA Jam","SNES","SNES",1993,"Sports","Midway","","NBA Jam","nba.jam"),
("NBA Jam Tournament Edition","SNES","SNES",1994,"Sports","Midway","","NBA Jam","nba.jam.tournament.edition|nba.jam.te"),
("NHL 94","SNES","SNES",1993,"Sports","Electronic Arts","","NHL","nhl.94"),
("NHL 95","SNES","SNES",1994,"Sports","Electronic Arts","","NHL","nhl.95"),
("NHL 96","SNES","SNES",1995,"Sports","Electronic Arts","","NHL","nhl.96"),
("Madden NFL 94","SNES","SNES",1993,"Sports","Electronic Arts","","Madden NFL","madden.94"),
("Madden NFL 95","SNES","SNES",1994,"Sports","Electronic Arts","","Madden NFL","madden.95"),
("Madden NFL 96","SNES","SNES",1995,"Sports","Electronic Arts","","Madden NFL","madden.96"),
("FIFA International Soccer","SNES","SNES",1993,"Sports","Electronic Arts","FIFA 94","FIFA","fifa.94|fifa.international.soccer"),
("FIFA 95","SNES","SNES",1994,"Sports","Electronic Arts","","FIFA","fifa.95"),
("FIFA 96","SNES","SNES",1995,"Sports","Electronic Arts","","FIFA","fifa.96"),
("FIFA 97","SNES","SNES",1996,"Sports","Electronic Arts","","FIFA","fifa.97"),
("Zombies Ate My Neighbors","SNES","SNES",1993,"Run and Gun","Lucasfilm Games","","Zombies Ate My Neighbors","zombies.ate.my.neighbors"),
("Axelay","SNES","SNES",1992,"Shoot 'em Up","Konami","","Axelay","axelay"),
("Gradius III","SNES","SNES",1990,"Shoot 'em Up","Konami","","Gradius","gradius.3"),
("Super R-Type","SNES","SNES",1991,"Shoot 'em Up","Irem","","R-Type","super.r.type"),
("R-Type III: The Third Lightning","SNES","SNES",1993,"Shoot 'em Up","Irem","","R-Type","r.type.3|r.type.iii"),
("Space Megaforce","SNES","SNES",1992,"Shoot 'em Up","Toei Animation","Super Aleste","Aleste","space.megaforce|super.aleste"),
("U.N. Squadron","SNES","SNES",1991,"Shoot 'em Up","Capcom","Area 88","U.N. Squadron","un.squadron|area.88"),
("Illusion of Gaia","SNES","SNES",1993,"Action-RPG","Quintet","Illusion of Time","Illusion of Gaia","illusion.of.gaia|illusion.of.time"),
("Terranigma","SNES","SNES",1995,"Action-RPG","Quintet","","Terranigma","terranigma"),
("Soul Blazer","SNES","SNES",1992,"Action-RPG","Quintet","","Soul Blazer","soul.blazer"),
("ActRaiser","SNES","SNES",1991,"Action-Platformer","Quintet","","ActRaiser","actraiser"),
("ActRaiser 2","SNES","SNES",1993,"Action-Platformer","Quintet","","ActRaiser","actraiser.2"),
("Ogre Battle: March of the Black Queen","SNES","SNES",1993,"Tactical RPG","Quest","","Ogre Battle","ogre.battle|march.of.the.black.queen"),
("Tactics Ogre: Let Us Cling Together","SNES","SNES",1995,"Tactical RPG","Quest","","Ogre Battle","tactics.ogre|let.us.cling.together"),
("Fire Emblem: Genealogy of the Holy War","SNES","SNES",1996,"Tactical RPG","Intelligent Systems","FE4","Fire Emblem","fire.emblem.4|genealogy.of.the.holy.war"),
("Fire Emblem: Thracia 776","SNES","SNES",1999,"Tactical RPG","Intelligent Systems","FE5","Fire Emblem","fire.emblem.5|thracia.776"),
("Fire Emblem: Mystery of the Emblem","SNES","SNES",1994,"Tactical RPG","Intelligent Systems","FE3","Fire Emblem","fire.emblem.3|mystery.of.the.emblem"),
("Aladdin","SNES","SNES",1993,"Platformer","Capcom","","Aladdin","aladdin"),
("The Lion King","SNES","SNES",1994,"Platformer","Virgin Interactive","","The Lion King","lion.king"),
("Mickey Mania","SNES","SNES",1994,"Platformer","Traveller's Tales","","Mickey Mouse","mickey.mania"),
("Goof Troop","SNES","SNES",1993,"Action-Adventure","Capcom","","Goof Troop","goof.troop"),
("Magical Quest Starring Mickey Mouse","SNES","SNES",1992,"Platformer","Capcom","","Mickey Mouse","magical.quest|mickey.mouse"),
("Magical Quest 2 Starring Mickey Mouse","SNES","SNES",1995,"Platformer","Capcom","The Great Circus Mystery","Mickey Mouse","magical.quest.2|great.circus.mystery"),
("Super Star Wars","SNES","SNES",1992,"Action-Platformer","Lucasfilm Games","","Star Wars","super.star.wars"),
("Super Empire Strikes Back","SNES","SNES",1993,"Action-Platformer","Lucasfilm Games","","Star Wars","super.empire.strikes.back"),
("Super Return of the Jedi","SNES","SNES",1994,"Action-Platformer","Lucasfilm Games","","Star Wars","super.return.of.the.jedi"),
("SimCity","SNES","SNES",1991,"Simulation","Maxis","","SimCity","simcity"),
("SimCity 2000","SNES","SNES",1995,"Simulation","Maxis","","SimCity","simcity.2000"),
("Civilization","SNES","SNES",1993,"Strategy","MicroProse","","Civilization","civilization"),
("Lemmings","SNES","SNES",1992,"Puzzle","DMA Design","","Lemmings","lemmings"),
("The Lost Vikings","SNES","SNES",1992,"Puzzle-Platformer","Blizzard","","The Lost Vikings","lost.vikings"),
("The Lost Vikings 2","SNES","SNES",1996,"Puzzle-Platformer","Blizzard","","The Lost Vikings","lost.vikings.2"),
("Rock 'n Roll Racing","SNES","SNES",1993,"Racing","Blizzard","","Rock 'n Roll Racing","rock.n.roll.racing"),
("Blackthorne","SNES","SNES",1994,"Action-Platformer","Blizzard","","Blackthorne","blackthorne"),
("Demon's Crest","SNES","SNES",1994,"Action-Platformer","Capcom","Gargoyle's Quest III","Gargoyle's Quest","demons.crest|gargoyles.quest.3"),
("Flashback","SNES","SNES",1993,"Action-Platformer","Delphine Software","","Flashback","flashback"),
("Another World","SNES","SNES",1992,"Action-Platformer","Delphine Software","Out of This World","Another World","another.world|out.of.this.world"),
("Prince of Persia","SNES","SNES",1992,"Action-Platformer","Broderbund","","Prince of Persia","prince.of.persia"),
("7th Saga","SNES","SNES",1993,"RPG","Compile","Elnard","7th Saga","7th.saga|elnard"),
("Arcana","SNES","SNES",1992,"RPG","HAL Laboratory","Card Master","Arcana","arcana|card.master"),
("Brain Lord","SNES","SNES",1994,"Action-RPG","Ascii Entertainment","","Brain Lord","brain.lord"),
("Paladin's Quest","SNES","SNES",1993,"RPG","Kemco","Lennus","Lennus","paladins.quest|lennus"),
("Robotrek","SNES","SNES",1994,"RPG","Quintet","Slapstick","Robotrek","robotrek|slapstick"),
("Romancing SaGa","SNES","SNES",1992,"RPG","Square","","SaGa","romancing.saga"),
("Romancing SaGa 2","SNES","SNES",1993,"RPG","Square","","SaGa","romancing.saga.2"),
("Romancing SaGa 3","SNES","SNES",1995,"RPG","Square","","SaGa","romancing.saga.3"),
("Front Mission","SNES","SNES",1995,"Tactical RPG","Square","","Front Mission","front.mission"),
("Star Ocean","SNES","SNES",1996,"RPG","tri-Ace","","Star Ocean","star.ocean"),
("Tales of Phantasia","SNES","SNES",1995,"RPG","Namco","","Tales","tales.of.phantasia"),
("Bahamut Lagoon","SNES","SNES",1996,"Tactical RPG","Square","","Bahamut Lagoon","bahamut.lagoon"),
("Treasure of the Rudras","SNES","SNES",1996,"RPG","Square","","Treasure of the Rudras","treasure.of.the.rudras"),
("Radical Dreamers","SNES","SNES",1996,"Adventure","Square","","Chrono","radical.dreamers"),
("Tetris Attack","SNES","SNES",1996,"Puzzle","Nintendo","Panel de Pon","Tetris","tetris.attack|panel.de.pon"),
("Dr. Mario","SNES","SNES",1993,"Puzzle","Nintendo","","Dr. Mario","dr.mario"),
("Kirby's Dream Course","SNES","SNES",1994,"Puzzle","HAL Laboratory","Kirby Bowl","Kirby","kirbys.dream.course|kirby.bowl"),
("Super Puzzle Fighter II Turbo","SNES","SNES",1996,"Puzzle","Capcom","","Street Fighter","super.puzzle.fighter.2.turbo"),
("Yoshi's Cookie","SNES","SNES",1992,"Puzzle","Nintendo","","Yoshi","yoshis.cookie"),
("Plok!","SNES","SNES",1993,"Platformer","Pickford Bros","","Plok!","plok"),
("Joe & Mac","SNES","SNES",1991,"Platformer","Data East","Caveman Ninja","Joe & Mac","joe.and.mac|caveman.ninja"),
("Joe & Mac 2: Lost in the Tropics","SNES","SNES",1994,"Platformer","Data East","","Joe & Mac","joe.and.mac.2"),
("Super Bonk","SNES","SNES",1994,"Platformer","Red Company","","Bonk","super.bonk|bonks.adventure"),
("Super Bomberman","SNES","SNES",1993,"Action","Hudson Soft","","Bomberman","super.bomberman"),
("Super Bomberman 2","SNES","SNES",1994,"Action","Hudson Soft","","Bomberman","super.bomberman.2"),
("Super Bomberman 3","SNES","SNES",1995,"Action","Hudson Soft","","Bomberman","super.bomberman.3"),
("Super Bomberman 4","SNES","SNES",1996,"Action","Hudson Soft","","Bomberman","super.bomberman.4"),
("Super Bomberman 5","SNES","SNES",1997,"Action","Hudson Soft","","Bomberman","super.bomberman.5"),
("Stunt Race FX","SNES","SNES",1994,"Racing","Nintendo","Wild Trax","Stunt Race FX","stunt.race.fx|wild.trax"),
("Uniracers","SNES","SNES",1994,"Racing","DMA Design","Unirally","Uniracers","uniracers|unirally"),
("Super Off Road","SNES","SNES",1992,"Racing","Virgin Interactive","","Super Off Road","super.off.road"),
("Top Gear","SNES","SNES",1992,"Racing","Gremlin Interactive","","Top Gear","top.gear"),
("Top Gear 2","SNES","SNES",1994,"Racing","Gremlin Interactive","","Top Gear","top.gear.2"),
("Top Gear 3000","SNES","SNES",1995,"Racing","Gremlin Interactive","","Top Gear","top.gear.3000"),
("Doom","SNES","SNES",1995,"FPS","id Software","","Doom","doom"),
("Wolfenstein 3D","SNES","SNES",1994,"FPS","id Software","","Wolfenstein","wolfenstein.3d"),
("Ghoul Patrol","SNES","SNES",1994,"Run and Gun","Lucasfilm Games","","Zombies Ate My Neighbors","ghoul.patrol"),
("Jurassic Park","SNES","SNES",1993,"Action","Ocean Software","","Jurassic Park","jurassic.park"),
("Jurassic Park 2: The Chaos Continues","SNES","SNES",1994,"Action","Ocean Software","","Jurassic Park","jurassic.park.2|chaos.continues"),
("Indiana Jones Greatest Adventures","SNES","SNES",1994,"Action-Platformer","Lucasfilm Games","","Indiana Jones","indiana.jones.greatest.adventures"),
("The Addams Family","SNES","SNES",1992,"Platformer","Ocean Software","","The Addams Family","addams.family"),
("Mario Paint","SNES","SNES",1992,"Creative","Nintendo","","Mario","mario.paint"),
("Wario Land: Super Mario Land 3","SNES","SNES",1994,"Platformer","Nintendo","","Wario","wario.land"),
("Super Double Dragon","SNES","SNES",1992,"Beat 'em Up","Technos Japan","Return of Double Dragon","Double Dragon","super.double.dragon"),
("Maximum Carnage","SNES","SNES",1994,"Beat 'em Up","LJN","","Spider-Man","maximum.carnage"),
("Super Scope 6","SNES","SNES",1992,"Shooter","Nintendo","","Super Scope","super.scope.6"),
("Out Run","SNES","SNES",1991,"Racing","Sega","","Out Run","out.run"),
("Super Hang-On","SNES","SNES",1992,"Racing","Sega","","Hang-On","super.hang.on"),
("Darius Twin","SNES","SNES",1991,"Shoot 'em Up","Taito","","Darius","darius.twin"),
("Popful Mail","SNES","SNES",1994,"Action-RPG","Falcom","","Popful Mail","popful.mail"),
("Mighty Morphin Power Rangers","SNES","SNES",1994,"Beat 'em Up","Bandai","","Power Rangers","mighty.morphin.power.rangers"),
("Mighty Morphin Power Rangers: The Fighting Edition","SNES","SNES",1995,"Fighting","Bandai","","Power Rangers","power.rangers.fighting.edition"),
("Batman Returns","SNES","SNES",1993,"Beat 'em Up","Konami","","Batman","batman.returns"),
("Batman Forever","SNES","SNES",1995,"Beat 'em Up","Acclaim","","Batman","batman.forever"),
("Spider-Man and Venom: Separation Anxiety","SNES","SNES",1995,"Beat 'em Up","LJN","","Spider-Man","spider.man.separation.anxiety"),
("Battletoads in Battlemaniacs","SNES","SNES",1993,"Beat 'em Up","Rare","","Battletoads","battletoads.in.battlemaniacs"),
("Diddy Kong Racing","SNES","SNES",1997,"Racing","Rare","","Diddy Kong","diddy.kong.racing"),
("Yoshi's Story","SNES","SNES",1998,"Platformer","Nintendo","","Yoshi","yoshis.story"),
("Paper Mario","SNES","SNES",2000,"RPG","Intelligent Systems","Mario Story","Mario","paper.mario|mario.story"),
("Blast Corps","SNES","SNES",1997,"Action","Rare","","Blast Corps","blast.corps"),
("GoldenEye 007","SNES","SNES",1997,"FPS","Rare","","James Bond","goldeneye.007|goldeneye"),
("1080 Snowboarding","SNES","SNES",1998,"Sports","Nintendo","","1080 Snowboarding","1080.snowboarding"),
("Mario Tennis","SNES","SNES",2000,"Sports","Camelot Software","","Mario","mario.tennis"),
("Mario Golf","SNES","SNES",1999,"Sports","Camelot Software","","Mario","mario.golf"),
("F1 World Grand Prix","SNES","SNES",1998,"Racing","Paradigm Entertainment","","F1","f1.world.grand.prix"),
("LEGO Racers","SNES","SNES",1999,"Racing","Lego Media","","LEGO","lego.racers"),
("Rayman 2: The Great Escape","SNES","SNES",1999,"Platformer","Ubisoft","","Rayman","rayman.2|great.escape"),
("WeaponLord","SNES","SNES",1995,"Fighting","Visual Concepts","","WeaponLord","weaponlord"),
("Eek! The Cat","SNES","SNES",1994,"Platformer","Ocean Software","","Eek! The Cat","eek.the.cat"),
("Beavis and Butt-Head","SNES","SNES",1994,"Adventure","Viacom New Media","","Beavis and Butt-Head","beavis.and.butt.head"),
("Super Mario World 2: Yoshi's Island","SNES","SNES",1995,"Platformer","Nintendo","","Mario","super.mario.world.2|yoshis.island"),
("Star Fox 2","SNES","SNES",1995,"Rail Shooter","Nintendo","","Star Fox","star.fox.2"),
("Mystic Quest Legend","SNES","SNES",1993,"RPG","Square","Final Fantasy Mystic Quest","Final Fantasy","mystic.quest.legend|final.fantasy.mystic.quest"),
("Secret of Stars","SNES","SNES",1993,"RPG","Tecmo","","Secret of Stars","secret.of.stars"),
("Inindo: Way of the Ninja","SNES","SNES",1993,"RPG","Koei","","Inindo","inindo"),
("Dragon Quest V: Hand of the Heavenly Bride","SNES","SNES",1992,"RPG","Chunsoft","","Dragon Quest","dragon.quest.5"),
("Dragon Quest VI: Realms of Revelation","SNES","SNES",1995,"RPG","Chunsoft","","Dragon Quest","dragon.quest.6"),
("SimAnt","SNES","SNES",1992,"Simulation","Maxis","","Sim","simant"),
("SimEarth","SNES","SNES",1992,"Simulation","Maxis","","Sim","simearth"),
("SimFarm","SNES","SNES",1993,"Simulation","Maxis","","Sim","simfarm"),
("Oh No! More Lemmings","SNES","SNES",1993,"Puzzle","DMA Design","","Lemmings","oh.no.more.lemmings"),
("Scooby-Doo Mystery","SNES","SNES",1995,"Adventure","Acclaim","","Scooby-Doo","scooby.doo.mystery"),
("Wayne's World","SNES","SNES",1993,"Platformer","THQ","","Wayne's World","waynes.world"),
("TaleSpin","SNES","SNES",1992,"Platformer","Capcom","","TaleSpin","talespin"),
("DuckTales","SNES","SNES",1993,"Platformer","Capcom","","DuckTales","ducktales"),
("Darkwing Duck","SNES","SNES",1992,"Platformer","Capcom","","Darkwing Duck","darkwing.duck"),
("Chip 'n Dale: Rescue Rangers 2","SNES","SNES",1994,"Platformer","Capcom","","Chip 'n Dale","chip.n.dale.rescue.rangers.2"),
("Space Station Silicon Valley","SNES","SNES",1998,"Action-Adventure","DMA Design","","Space Station Silicon Valley","space.station.silicon.valley"),
("Pugsley's Scavenger Hunt","SNES","SNES",1993,"Platformer","Ocean Software","","The Addams Family","pugsleys.scavenger.hunt"),
("Doom 2","SNES","SNES",1995,"FPS","id Software","","Doom","doom.2"),
("Thunder Spirits","SNES","SNES",1993,"Shoot 'em Up","Tecmo","","Thunder Force","thunder.spirits"),
("Super Smash Bros.","SNES","SNES",1999,"Fighting","HAL Laboratory","","Super Smash Bros.","super.smash.bros|ssb"),
("Mario Party","SNES","SNES",1998,"Party","Hudson Soft","","Mario Party","mario.party"),
("Mario Party 2","SNES","SNES",1999,"Party","Hudson Soft","","Mario Party","mario.party.2"),
("Mario Party 3","SNES","SNES",2000,"Party","Hudson Soft","","Mario Party","mario.party.3"),
("Excitebike 64","SNES","SNES",2000,"Racing","Left Field","","Excitebike","excitebike.64"),
("Kirby 64: The Crystal Shards","SNES","SNES",2000,"Platformer","HAL Laboratory","","Kirby","kirby.64|crystal.shards"),
("Banjo-Kazooie","SNES","SNES",1998,"Platformer","Rare","","Banjo-Kazooie","banjo.kazooie"),
("Banjo-Tooie","SNES","SNES",2000,"Platformer","Rare","","Banjo-Kazooie","banjo.tooie"),
("Donkey Kong 64","SNES","SNES",1999,"Platformer","Rare","","Donkey Kong","donkey.kong.64|dk64"),
("Perfect Dark","SNES","SNES",2000,"FPS","Rare","","Perfect Dark","perfect.dark"),
("Star Fox 64","SNES","SNES",1997,"Rail Shooter","Nintendo","Lylat Wars","Star Fox","star.fox.64|lylat.wars"),
("Pokemon Snap","SNES","SNES",1999,"Simulation","HAL Laboratory","","Pokemon","pokemon.snap"),
("Pokemon Stadium","SNES","SNES",1998,"Strategy","Nintendo","","Pokemon","pokemon.stadium"),
("Pokemon Stadium 2","SNES","SNES",2000,"Strategy","Nintendo","","Pokemon","pokemon.stadium.2"),
("Harvest Moon 64","SNES","SNES",1999,"Simulation","Natsume","","Harvest Moon","harvest.moon.64"),
("Jet Force Gemini","SNES","SNES",1999,"Third-Person Shooter","Rare","","Jet Force Gemini","jet.force.gemini"),
("Conker's Bad Fur Day","SNES","SNES",2001,"Platformer","Rare","","Conker","conkers.bad.fur.day"),
("Turok: Dinosaur Hunter","SNES","SNES",1997,"FPS","Iguana Entertainment","","Turok","turok|dinosaur.hunter"),
("Turok 2: Seeds of Evil","SNES","SNES",1998,"FPS","Iguana Entertainment","","Turok","turok.2|seeds.of.evil"),
("Turok 3: Shadow of Oblivion","SNES","SNES",2000,"FPS","Iguana Entertainment","","Turok","turok.3|shadow.of.oblivion"),
("Doom 64","SNES","SNES",1997,"FPS","Midway","","Doom","doom.64"),
("Quake 64","SNES","SNES",1998,"FPS","Midway","","Quake","quake.64"),
("Star Wars: Shadows of the Empire","SNES","SNES",1996,"Action-Adventure","LucasArts","","Star Wars","star.wars.shadows.of.the.empire"),
("Star Wars: Rogue Squadron","SNES","SNES",1998,"Flight","Factor 5","","Star Wars","star.wars.rogue.squadron"),
("Star Wars: Episode I Racer","SNES","SNES",1999,"Racing","LucasArts","","Star Wars","star.wars.episode.1.racer"),
("Mega Man Soccer","SNES","SNES",1994,"Sports","Capcom","","Mega Man","mega.man.soccer"),
("Super Soccer","SNES","SNES",1992,"Sports","Nintendo","","Super Soccer","super.soccer"),
("Super Tennis","SNES","SNES",1991,"Sports","Nintendo","","Super Tennis","super.tennis"),
("Ken Griffey Jr. Presents Major League Baseball","SNES","SNES",1994,"Sports","Software Creations","","MLB","ken.griffey.jr.baseball"),
("Super Baseball Simulator 1.000","SNES","SNES",1991,"Sports","Culture Brain","","Super Baseball Simulator","super.baseball.simulator"),
("NBA Live 95","SNES","SNES",1994,"Sports","Electronic Arts","","NBA Live","nba.live.95"),
("NBA Live 96","SNES","SNES",1995,"Sports","Electronic Arts","","NBA Live","nba.live.96"),
("NBA Live 97","SNES","SNES",1996,"Sports","Electronic Arts","","NBA Live","nba.live.97"),
("The Adventures of Mighty Max","SNES","SNES",1995,"Platformer","Ocean Software","","Mighty Max","mighty.max"),
("Animaniacs","SNES","SNES",1995,"Platformer","","Animaniacs","animaniacs"),
("Earthworm Jim","SNES","SNES",1994,"Platformer","Shiny Entertainment","","Earthworm Jim","earthworm.jim"),
("Earthworm Jim 2","SNES","SNES",1995,"Platformer","Shiny Entertainment","","Earthworm Jim","earthworm.jim.2"),
("Shining Force II","SNES","SNES",1994,"Tactical RPG","Sega","","Shining Force","shining.force.2"),
]
for g in snes_games:
    a(*g)

print(f"SNES: {len(snes_games)}")
snes_count = len(rows)

# ===================== N64 (220 games) =====================
n64_games = [
("Super Mario 64","N64","N64",1996,"Platformer","Nintendo","","Mario","super.mario.64|sm64"),
("The Legend of Zelda: Ocarina of Time","N64","N64",1998,"Action-Adventure","Nintendo","OoT","Zelda","legend.of.zelda.ocarina.of.time|oot"),
("The Legend of Zelda: Majora's Mask","N64","N64",2000,"Action-Adventure","Nintendo","MM","Zelda","legend.of.zelda.majoras.mask|mm"),
("Mario Kart 64","N64","N64",1996,"Racing","Nintendo","","Mario Kart","mario.kart.64"),
("GoldenEye 007","N64","N64",1997,"FPS","Rare","","James Bond","goldeneye.007|goldeneye"),
("Perfect Dark","N64","N64",2000,"FPS","Rare","","Perfect Dark","perfect.dark"),
("Banjo-Kazooie","N64","N64",1998,"Platformer","Rare","","Banjo-Kazooie","banjo.kazooie"),
("Banjo-Tooie","N64","N64",2000,"Platformer","Rare","","Banjo-Kazooie","banjo.tooie"),
("Donkey Kong 64","N64","N64",1999,"Platformer","Rare","","Donkey Kong","donkey.kong.64|dk64"),
("Star Fox 64","N64","N64",1997,"Rail Shooter","Nintendo","Lylat Wars","Star Fox","star.fox.64|lylat.wars"),
("Super Smash Bros.","N64","N64",1999,"Fighting","HAL Laboratory","","Super Smash Bros.","super.smash.bros|ssb"),
("Paper Mario","N64","N64",2000,"RPG","Intelligent Systems","Mario Story","Mario","paper.mario|mario.story"),
("Mario Party","N64","N64",1998,"Party","Hudson Soft","","Mario Party","mario.party"),
("Mario Party 2","N64","N64",1999,"Party","Hudson Soft","","Mario Party","mario.party.2"),
("Mario Party 3","N64","N64",2000,"Party","Hudson Soft","","Mario Party","mario.party.3"),
("Diddy Kong Racing","N64","N64",1997,"Racing","Rare","","Diddy Kong","diddy.kong.racing"),
("F-Zero X","N64","N64",1998,"Racing","Nintendo","","F-Zero","fzero.x|f.zero.x"),
("Wave Race 64","N64","N64",1996,"Racing","Nintendo","","Wave Race","wave.race.64"),
("1080 Snowboarding","N64","N64",1998,"Sports","Nintendo","","1080 Snowboarding","1080.snowboarding"),
("Excitebike 64","N64","N64",2000,"Racing","Left Field","","Excitebike","excitebike.64"),
("Mario Tennis","N64","N64",2000,"Sports","Camelot Software","","Mario","mario.tennis"),
("Mario Golf","N64","N64",1999,"Sports","Camelot Software","","Mario","mario.golf"),
("Kirby 64: The Crystal Shards","N64","N64",2000,"Platformer","HAL Laboratory","","Kirby","kirby.64|crystal.shards"),
("Pokemon Snap","N64","N64",1999,"Simulation","HAL Laboratory","","Pokemon","pokemon.snap"),
("Pokemon Stadium","N64","N64",1998,"Strategy","Nintendo","","Pokemon","pokemon.stadium"),
("Pokemon Stadium 2","N64","N64",2000,"Strategy","Nintendo","","Pokemon","pokemon.stadium.2"),
("Hey You, Pikachu!","N64","N64",1998,"Simulation","Nintendo","","Pokemon","hey.you.pikachu"),
("Blast Corps","N64","N64",1997,"Action","Rare","","Blast Corps","blast.corps"),
("Jet Force Gemini","N64","N64",1999,"Third-Person Shooter","Rare","","Jet Force Gemini","jet.force.gemini"),
("Killer Instinct Gold","N64","N64",1996,"Fighting","Rare","","Killer Instinct","killer.instinct.gold"),
("Mortal Kombat Trilogy","N64","N64",1996,"Fighting","Midway","","Mortal Kombat","mortal.kombat.trilogy"),
("Mortal Kombat 4","N64","N64",1997,"Fighting","Midway","","Mortal Kombat","mortal.kombat.4"),
("Cruis'n USA","N64","N64",1996,"Racing","Midway","","Cruis'n","cruisn.usa"),
("Cruis'n World","N64","N64",1998,"Racing","Midway","","Cruis'n","cruisn.world"),
("Cruis'n Exotica","N64","N64",1999,"Racing","Midway","","Cruis'n","cruisn.exotica"),
("San Francisco Rush: Extreme Racing","N64","N64",1997,"Racing","Midway","","Rush","san.francisco.rush"),
("San Francisco Rush 2049","N64","N64",1999,"Racing","Midway","","Rush","rush.2049"),
("Hydro Thunder","N64","N64",1999,"Racing","Midway","","Hydro Thunder","hydro.thunder"),
("Top Gear Overdrive","N64","N64",1998,"Racing","Kemco","","Top Gear","top.gear.overdrive"),
("Top Gear Rally","N64","N64",1997,"Racing","Kemco","","Top Gear","top.gear.rally"),
("Top Gear Rally 2","N64","N64",1999,"Racing","Kemco","","Top Gear","top.gear.rally.2"),
("Beetle Adventure Racing","N64","N64",1999,"Racing","Paradigm Entertainment","","Beetle Adventure Racing","beetle.adventure.racing"),
("LEGO Racers","N64","N64",1999,"Racing","Lego Media","","LEGO","lego.racers"),
("Micro Machines 64 Turbo","N64","N64",1999,"Racing","Codemasters","","Micro Machines","micro.machines.64"),
("Rayman 2: The Great Escape","N64","N64",1999,"Platformer","Ubisoft","","Rayman","rayman.2|great.escape"),
("Conker's Bad Fur Day","N64","N64",2001,"Platformer","Rare","","Conker","conkers.bad.fur.day"),
("Body Harvest","N64","N64",1998,"Action-Adventure","DMA Design","","Body Harvest","body.harvest"),
("Space Station Silicon Valley","N64","N64",1998,"Action-Adventure","DMA Design","","Space Station Silicon Valley","space.station.silicon.valley"),
("Rocket: Robot on Wheels","N64","N64",1999,"Platformer","Sucker Punch","","Rocket","rocket.robot.on.wheels"),
("Gex 64: Enter the Gecko","N64","N64",1998,"Platformer","Crystal Dynamics","","Gex","gex.64|enter.the.gecko"),
("Gex 3: Deep Cover Gecko","N64","N64",1999,"Platformer","Crystal Dynamics","","Gex","gex.3|deep.cover.gecko"),
("Bomberman 64","N64","N64",1997,"Action","Hudson Soft","Baku Bomberman","Bomberman","bomberman.64|baku.bomberman"),
("Bomberman 64: The Second Attack","N64","N64",1999,"Action","Hudson Soft","","Bomberman","bomberman.64.2|second.attack"),
("Chameleon Twist","N64","N64",1997,"Platformer","Japan System Supply","","Chameleon Twist","chameleon.twist"),
("Chameleon Twist 2","N64","N64",1999,"Platformer","Japan System Supply","","Chameleon Twist","chameleon.twist.2"),
("Yoshi's Story","N64","N64",1998,"Platformer","Nintendo","","Yoshi","yoshis.story"),
("Glover","N64","N64",1998,"Platformer","Interactive Studios","","Glover","glover"),
("Buck Bumble","N64","N64",1998,"Shooter","Argonaut Games","","Buck Bumble","buck.bumble"),
("Quest 64","N64","N64",1998,"RPG","Imagineer","Holy Magic Century","Quest 64","quest.64|holy.magic.century"),
("Ogre Battle 64: Person of Lordly Caliber","N64","N64",2000,"Tactical RPG","Quest","","Ogre Battle","ogre.battle.64"),
("Harvest Moon 64","N64","N64",1999,"Simulation","Natsume","","Harvest Moon","harvest.moon.64"),
("Shadow Man","N64","N64",1999,"Action-Adventure","Acclaim","","Shadow Man","shadow.man"),
("Turok: Dinosaur Hunter","N64","N64",1997,"FPS","Iguana Entertainment","","Turok","turok|dinosaur.hunter"),
("Turok 2: Seeds of Evil","N64","N64",1998,"FPS","Iguana Entertainment","","Turok","turok.2|seeds.of.evil"),
("Turok 3: Shadow of Oblivion","N64","N64",2000,"FPS","Iguana Entertainment","","Turok","turok.3|shadow.of.oblivion"),
("Turok: Rage Wars","N64","N64",1999,"FPS","Iguana Entertainment","","Turok","turok.rage.wars"),
("Doom 64","N64","N64",1997,"FPS","Midway","","Doom","doom.64"),
("Quake 64","N64","N64",1998,"FPS","Midway","","Quake","quake.64"),
("Quake II","N64","N64",1999,"FPS","Midway","","Quake","quake.2|quake.ii"),
("Duke Nukem 64","N64","N64",1997,"FPS","3D Realms","","Duke Nukem","duke.nukem.64"),
("Duke Nukem: Zero Hour","N64","N64",1999,"FPS","3D Realms","","Duke Nukem","duke.nukem.zero.hour"),
("South Park","N64","N64",1998,"FPS","Acclaim","","South Park","south.park"),
("WinBack: Covert Operations","N64","N64",1999,"Third-Person Shooter","Koei","","WinBack","winback"),
("Star Wars: Shadows of the Empire","N64","N64",1996,"Action-Adventure","LucasArts","","Star Wars","star.wars.shadows.of.the.empire"),
("Star Wars: Rogue Squadron","N64","N64",1998,"Flight","Factor 5","","Star Wars","star.wars.rogue.squadron"),
("Star Wars: Episode I Racer","N64","N64",1999,"Racing","LucasArts","","Star Wars","star.wars.episode.1.racer"),
("Star Wars: Battle for Naboo","N64","N64",2000,"Flight","Factor 5","","Star Wars","star.wars.battle.for.naboo"),
("Indiana Jones and the Infernal Machine","N64","N64",1999,"Action-Adventure","LucasArts","","Indiana Jones","indiana.jones.infernal.machine"),
("Resident Evil 2","N64","N64",1999,"Survival Horror","Capcom","","Resident Evil","resident.evil.2"),
("A Bug's Life","N64","N64",1999,"Platformer","Treyarch","","A Bug's Life","a.bugs.life"),
("Toy Story 2: Buzz Lightyear to the Rescue","N64","N64",1999,"Platformer","Traveller's Tales","","Toy Story","toy.story.2|buzz.lightyear.to.the.rescue"),
("Tarzan","N64","N64",1999,"Platformer","Eurocom","","Tarzan","tarzan"),
("Disney's Donald Duck: Goin' Quackers","N64","N64",2000,"Platformer","Ubisoft","Donald Duck: Quack Attack","Donald Duck","donald.duck.goin.quackers|quack.attack"),
("Madden NFL 2000","N64","N64",1999,"Sports","Electronic Arts","","Madden NFL","madden.2000"),
("Madden NFL 2001","N64","N64",2000,"Sports","Electronic Arts","","Madden NFL","madden.2001"),
("Madden NFL 2002","N64","N64",2001,"Sports","Electronic Arts","","Madden NFL","madden.2002"),
("Madden NFL 2003","N64","N64",2002,"Sports","Electronic Arts","","Madden NFL","madden.2003"),
("NBA Jam 99","N64","N64",1998,"Sports","Acclaim","","NBA Jam","nba.jam.99"),
("NBA Jam 2000","N64","N64",1999,"Sports","Acclaim","","NBA Jam","nba.jam.2000"),
("NBA Courtside","N64","N64",1998,"Sports","Left Field","","NBA Courtside","nba.courtside"),
("NBA Courtside 2: Featuring Kobe Bryant","N64","N64",1999,"Sports","Left Field","","NBA Courtside","nba.courtside.2"),
("NFL Blitz","N64","N64",1998,"Sports","Midway","","NFL Blitz","nfl.blitz"),
("NFL Blitz 2000","N64","N64",1999,"Sports","Midway","","NFL Blitz","nfl.blitz.2000"),
("NFL Blitz 2001","N64","N64",2000,"Sports","Midway","","NFL Blitz","nfl.blitz.2001"),
("All-Star Baseball 2000","N64","N64",1999,"Sports","Acclaim","","All-Star Baseball","all.star.baseball.2000"),
("All-Star Baseball 2001","N64","N64",2000,"Sports","Acclaim","","All-Star Baseball","all.star.baseball.2001"),
("Wayne Gretzky's 3D Hockey","N64","N64",1996,"Sports","Midway","","Wayne Gretzky","wayne.gretzkys.3d.hockey"),
("Vigilante 8","N64","N64",1998,"Vehicular Combat","Luxoflux","","Vigilante 8","vigilante.8"),
("Vigilante 8: 2nd Offense","N64","N64",1999,"Vehicular Combat","Luxoflux","","Vigilante 8","vigilante.8.2nd.offense"),
("ISS 64","N64","N64",1997,"Sports","Konami","","ISS","iss.64"),
("ISS 98","N64","N64",1998,"Sports","Konami","","ISS","iss.98"),
("World Cup 98","N64","N64",1998,"Sports","Electronic Arts","","FIFA","world.cup.98"),
("FIFA 99","N64","N64",1998,"Sports","Electronic Arts","","FIFA","fifa.99"),
("FIFA: Road to World Cup 98","N64","N64",1997,"Sports","Electronic Arts","","FIFA","fifa.road.to.world.cup.98"),
("FIFA 2000","N64","N64",1999,"Sports","Electronic Arts","","FIFA","fifa.2000"),
("Snowboard Kids","N64","N64",1997,"Sports","Atlus","","Snowboard Kids","snowboard.kids"),
("Snowboard Kids 2","N64","N64",1999,"Sports","Atlus","","Snowboard Kids","snowboard.kids.2"),
("WCW vs. nWo: World Tour","N64","N64",1997,"Fighting","AKI","","WCW","wcw.vs.nwo|world.tour"),
("WCW/nWo Revenge","N64","N64",1998,"Fighting","AKI","","WCW","wcw.nwo.revenge"),
("WWF WrestleMania 2000","N64","N64",1999,"Fighting","AKI","","WWE","wwf.wrestlemania.2000"),
("WWF No Mercy","N64","N64",2000,"Fighting","AKI","","WWE","wwf.no.mercy"),
("Virtual Pro Wrestling 64","N64","N64",1997,"Fighting","AKI","","Virtual Pro Wrestling","virtual.pro.wrestling.64"),
("Mischief Makers","N64","N64",1997,"Platformer","Treasure","Yuke Yuke!! Trouble Makers","Mischief Makers","mischief.makers|trouble.makers"),
("Bangai-O","N64","N64",1999,"Shoot 'em Up","Treasure","","Bangai-O","bangai.o"),
("Puzzle Bobble 64","N64","N64",1999,"Puzzle","Taito","","Puzzle Bobble","puzzle.bobble.64"),
("SimCity 64","N64","N64",2000,"Simulation","Nintendo","","SimCity","simcity.64"),
("Hexen","N64","N64",1997,"FPS","id Software","","Hexen","hexen"),
("Army Men: Sarge's Heroes","N64","N64",1999,"Third-Person Shooter","3DO","","Army Men","army.men.sarges.heroes"),
("Army Men: Air Combat","N64","N64",2000,"Action","3DO","","Army Men","army.men.air.combat"),
("Gauntlet Legends","N64","N64",1999,"Action","Midway","","Gauntlet","gauntlet.legends"),
("Gauntlet Dark Legacy","N64","N64",2001,"Action","Midway","","Gauntlet","gauntlet.dark.legacy"),
("Shadowgate 64","N64","N64",1999,"Adventure","Kemco","","Shadowgate","shadowgate.64"),
("Armorines: Project S.W.A.R.M.","N64","N64",1999,"FPS","Acclaim","","Armorines","armorines|project.swarm"),
("Daikatana","N64","N64",2000,"FPS","Ion Storm","","Daikatana","daikatana"),
("Mortal Kombat Mythologies: Sub-Zero","N64","N64",1997,"Action-Adventure","Midway","","Mortal Kombat","mortal.kombat.mythologies.sub.zero"),
("Fighter's Destiny","N64","N64",1998,"Fighting","Ocean Software","","Fighter's Destiny","fighters.destiny"),
("Fighter's Destiny 2","N64","N64",1999,"Fighting","Ocean Software","","Fighter's Destiny","fighters.destiny.2"),
("Rakugakids","N64","N64",1998,"Fighting","Eternal Entertainment","","Rakugakids","rakugakids"),
("War Gods","N64","N64",1996,"Fighting","Midway","","War Gods","war.gods"),
("F1 World Grand Prix","N64","N64",1998,"Racing","Paradigm Entertainment","","F1","f1.world.grand.prix"),
("F1 World Grand Prix II","N64","N64",1999,"Racing","Paradigm Entertainment","","F1","f1.world.grand.prix.2"),
("Roadster's Trophy","N64","N64",1998,"Racing","Titus Interactive","","Roadster's Trophy","roadsters.trophy"),
("Pilotwings 64","N64","N64",1996,"Flight","Nintendo","","Pilotwings","pilotwings.64"),
("Mario Artist: Paint Studio","N64","N64",1999,"Creative","Nintendo","","Mario Artist","mario.artist.paint.studio"),
("Mario Artist: Talent Studio","N64","N64",2000,"Creative","Nintendo","","Mario Artist","mario.artist.talent.studio"),
("Transformers: Beast Wars","N64","N64",1999,"Action","Hasbro Interactive","","Transformers","transformers.beast.wars"),
("Supercross 2000","N64","N64",1999,"Sports","Acclaim","","Supercross","supercross.2000"),
("Nascar 99","N64","N64",1998,"Racing","Electronic Arts","","NASCAR","nascar.99"),
("Nascar 2000","N64","N64",1999,"Racing","Electronic Arts","","NASCAR","nascar.2000"),
("Major League Baseball Featuring Ken Griffey Jr.","N64","N64",1998,"Sports","Nintendo","","MLB","mlb.ken.griffey.jr"),
("Mike Piazza's Strike Zone","N64","N64",1998,"Sports","Kemco","","Mike Piazza","mike.piazzas.strike.zone"),
("Mia Hamm Soccer 64","N64","N64",2000,"Sports","SouthPeak Games","","Mia Hamm Soccer","mia.hamm.soccer.64"),
("Monopoly","N64","N64",1999,"Board Game","Hasbro Interactive","","Monopoly","monopoly"),
("Wheel of Fortune","N64","N64",1999,"Trivia","Hasbro Interactive","","Wheel of Fortune","wheel.of.fortune"),
("Jeopardy!","N64","N64",1999,"Trivia","Hasbro Interactive","","Jeopardy!","jeopardy"),
("Risk","N64","N64",1999,"Strategy","Hasbro Interactive","","Risk","risk"),
("Clue","N64","N64",1999,"Party","Hasbro Interactive","","Clue","clue"),
("Elmo's Letter Adventure","N64","N64",1999,"Educational","NewKidCo","","Sesame Street","elmos.letter.adventure"),
("Rugrats: Scavenger Hunt","N64","N64",1999,"Party","THQ","","Rugrats","rugrats.scavenger.hunt"),
("Charlie Blast's Territory","N64","N64",1999,"Puzzle","Realtime Associates","","Charlie Blast","charlie.blasts.territory"),
("Big Mountain 2000","N64","N64",1998,"Sports","SouthPeak Games","","Big Mountain 2000","big.mountain.2000"),
("Wonder Project J2","N64","N64",1996,"Simulation","Givro","","Wonder Project J","wonder.project.j2"),
("Flying Dragon","N64","N64",1998,"Fighting","Culture Brain","","Flying Dragon","flying.dragon"),
("Centerfold Squares","N64","N64",1998,"Party","Spectrum HoloByte","","Centerfold Squares","centerfold.squares"),
("Robotron 64","N64","N64",1998,"Twin-Stick Shooter","Midway","","Robotron","robotron.64"),
("Dance Dance Revolution: Disney Mix","N64","N64",2001,"Rhythm","Konami","","Dance Dance Revolution","ddr.disney.mix"),
("Heretic II","N64","N64",1999,"Action","Raven Software","","Heretic","heretic.2|heretic.ii"),
("Mega Man 64","N64","N64",2000,"Action-RPG","Capcom","Mega Man Legends","Mega Man","mega.man.64"),
]
for g in n64_games:
    a(*g)

print(f"N64: {len(n64_games)}")
n64_count = len(rows)

print(f"Total so far: {len(rows)}")
print("Continuing with remaining sections...")
