import csv, sys, os

rows = []

def a(t, p, ps, y, g, dev, alt="", series="", folders=""):
    ts = t.lower().replace("'","")
    if not folders:
        folders = ts.replace(": "," ").replace(":"," ").replace(" & "," and ").replace(" - "," ").replace(", "," ").replace("  "," ").strip()
    rows.append([t, ts, p, ps, str(y), g, dev, alt, series, folders])

def batch_add(games):
    for g in games:
        a(*g)

# ===================== PS1 (550 games) =====================
ps1_games = [
("Final Fantasy VII","PS1","PS1",1997,"RPG","Square","FF7","Final Fantasy","final.fantasy.7|ff7"),
("Final Fantasy VIII","PS1","PS1",1999,"RPG","Square","FF8","Final Fantasy","final.fantasy.8|ff8"),
("Final Fantasy IX","PS1","PS1",2000,"RPG","Square","FF9","Final Fantasy","final.fantasy.9|ff9"),
("Final Fantasy Tactics","PS1","PS1",1997,"Tactical RPG","Square","","Final Fantasy","final.fantasy.tactics|fft"),
("Metal Gear Solid","PS1","PS1",1998,"Stealth-Action","Konami","MGS","Metal Gear","metal.gear.solid|mgs"),
("Resident Evil","PS1","PS1",1996,"Survival Horror","Capcom","RE1","Resident Evil","resident.evil|re1"),
("Resident Evil 2","PS1","PS1",1998,"Survival Horror","Capcom","RE2","Resident Evil","resident.evil.2|re2"),
("Resident Evil 3: Nemesis","PS1","PS1",1999,"Survival Horror","Capcom","RE3","Resident Evil","resident.evil.3|re3|nemesis"),
("Silent Hill","PS1","PS1",1999,"Survival Horror","Konami","","Silent Hill","silent.hill"),
("Castlevania: Symphony of the Night","PS1","PS1",1997,"Action-RPG","Konami","SOTN","Castlevania","castlevania.symphony.of.the.night|sotn"),
("Chrono Cross","PS1","PS1",2000,"RPG","Square","","Chrono","chrono.cross"),
("Xenogears","PS1","PS1",1998,"RPG","Square","","Xeno","xenogears"),
("Vagrant Story","PS1","PS1",2000,"Action-RPG","Square","","Vagrant Story","vagrant.story"),
("Parasite Eve","PS1","PS1",1998,"Action-RPG","Square","","Parasite Eve","parasite.eve"),
("Parasite Eve II","PS1","PS1",1999,"Action-RPG","Square","","Parasite Eve","parasite.eve.2"),
("Front Mission 3","PS1","PS1",1999,"Tactical RPG","Square","","Front Mission","front.mission.3"),
("Saga Frontier","PS1","PS1",1997,"RPG","Square","","SaGa","saga.frontier"),
("Saga Frontier 2","PS1","PS1",1999,"RPG","Square","","SaGa","saga.frontier.2"),
("Valkyrie Profile","PS1","PS1",1999,"RPG","tri-Ace","","Valkyrie Profile","valkyrie.profile"),
("Suikoden","PS1","PS1",1996,"RPG","Konami","","Suikoden","suikoden"),
("Suikoden II","PS1","PS1",1998,"RPG","Konami","","Suikoden","suikoden.2"),
("Breath of Fire III","PS1","PS1",1997,"RPG","Capcom","","Breath of Fire","breath.of.fire.3"),
("Breath of Fire IV","PS1","PS1",2000,"RPG","Capcom","","Breath of Fire","breath.of.fire.4"),
("Wild Arms","PS1","PS1",1996,"RPG","Media.Vision","","Wild Arms","wild.arms"),
("Wild Arms 2","PS1","PS1",1999,"RPG","Media.Vision","","Wild Arms","wild.arms.2"),
("Grandia","PS1","PS1",1997,"RPG","Game Arts","","Grandia","grandia"),
("Lunar: Silver Star Story Complete","PS1","PS1",1999,"RPG","Game Arts","","Lunar","lunar.silver.star.story|silver.star"),
("Lunar 2: Eternal Blue Complete","PS1","PS1",2000,"RPG","Game Arts","","Lunar","lunar.2|eternal.blue"),
("Arc the Lad Collection","PS1","PS1",2002,"RPG","G-Craft","","Arc the Lad","arc.the.lad"),
("Alundra","PS1","PS1",1997,"Action-RPG","Matrix Software","","Alundra","alundra"),
("Alundra 2","PS1","PS1",1999,"Action-RPG","Matrix Software","","Alundra","alundra.2"),
("Legend of Legaia","PS1","PS1",1998,"RPG","Prokion","","Legend of Legaia","legend.of.legaia"),
("Legend of Legaia 2","PS1","PS1",2001,"RPG","Prokion","","Legend of Legaia","legend.of.legaia.2"),
("Crash Bandicoot","PS1","PS1",1996,"Platformer","Naughty Dog","","Crash Bandicoot","crash.bandicoot"),
("Crash Bandicoot 2: Cortex Strikes Back","PS1","PS1",1997,"Platformer","Naughty Dog","","Crash Bandicoot","crash.bandicoot.2|cortex.strikes.back"),
("Crash Bandicoot: Warped","PS1","PS1",1998,"Platformer","Naughty Dog","","Crash Bandicoot","crash.bandicoot.warped"),
("Crash Team Racing","PS1","PS1",1999,"Racing","Naughty Dog","CTR","Crash Bandicoot","crash.team.racing|ctr"),
("Spyro the Dragon","PS1","PS1",1998,"Platformer","Insomniac Games","","Spyro","spyro.the.dragon|spyro"),
("Spyro 2: Ripto's Rage","PS1","PS1",1999,"Platformer","Insomniac Games","","Spyro","spyro.2|riptos.rage"),
("Spyro: Year of the Dragon","PS1","PS1",2000,"Platformer","Insomniac Games","","Spyro","spyro.year.of.the.dragon"),
("MediEvil","PS1","PS1",1998,"Action-Adventure","SCE Cambridge","","MediEvil","medievil"),
("MediEvil 2","PS1","PS1",2000,"Action-Adventure","SCE Cambridge","","MediEvil","medievil.2"),
("Ape Escape","PS1","PS1",1999,"Platformer","SCE Japan Studio","","Ape Escape","ape.escape"),
("Klonoa: Door to Phantomile","PS1","PS1",1997,"Platformer","Namco","","Klonoa","klonoa|door.to.phantomile"),
("Tomba!","PS1","PS1",1997,"Platformer","Whoopee Camp","","Tomba!","tomba"),
("Tomba! 2: The Evil Swine Return","PS1","PS1",1999,"Platformer","Whoopee Camp","","Tomba!","tomba.2"),
("Oddworld: Abe's Oddysee","PS1","PS1",1997,"Platformer","Oddworld Inhabitants","","Oddworld","oddworld.abes.oddysee"),
("Oddworld: Abe's Exoddus","PS1","PS1",1998,"Platformer","Oddworld Inhabitants","","Oddworld","oddworld.abes.exoddus"),
("Gran Turismo","PS1","PS1",1997,"Racing","Polyphony Digital","GT1","Gran Turismo","gran.turismo|gt"),
("Gran Turismo 2","PS1","PS1",1999,"Racing","Polyphony Digital","GT2","Gran Turismo","gran.turismo.2|gt2"),
("Ridge Racer","PS1","PS1",1994,"Racing","Namco","","Ridge Racer","ridge.racer"),
("Ridge Racer Revolution","PS1","PS1",1995,"Racing","Namco","","Ridge Racer","ridge.racer.revolution"),
("Rage Racer","PS1","PS1",1996,"Racing","Namco","","Rage Racer","rage.racer"),
("R4: Ridge Racer Type 4","PS1","PS1",1998,"Racing","Namco","","Ridge Racer","r4|ridge.racer.type.4"),
("Tekken","PS1","PS1",1995,"Fighting","Namco","","Tekken","tekken"),
("Tekken 2","PS1","PS1",1996,"Fighting","Namco","","Tekken","tekken.2"),
("Tekken 3","PS1","PS1",1998,"Fighting","Namco","","Tekken","tekken.3"),
("Street Fighter Alpha","PS1","PS1",1996,"Fighting","Capcom","Street Fighter Zero","Street Fighter","street.fighter.alpha|sf.alpha"),
("Street Fighter Alpha 2","PS1","PS1",1996,"Fighting","Capcom","SFA2","Street Fighter","street.fighter.alpha.2|sfa2"),
("Street Fighter Alpha 3","PS1","PS1",1998,"Fighting","Capcom","SFA3","Street Fighter","street.fighter.alpha.3|sfa3"),
("Darkstalkers 3","PS1","PS1",1998,"Fighting","Capcom","Vampire Savior","Darkstalkers","darkstalkers.3|vampire.savior"),
("Marvel vs. Capcom: Clash of Super Heroes","PS1","PS1",1998,"Fighting","Capcom","MvC1","Marvel vs. Capcom","marvel.vs.capcom|mvc1"),
("Soul Blade","PS1","PS1",1996,"Fighting","Namco","Soul Edge","Soulcalibur","soul.blade|soul.edge"),
("Bushido Blade","PS1","PS1",1997,"Fighting","Square","","Bushido Blade","bushido.blade"),
("Bushido Blade 2","PS1","PS1",1998,"Fighting","Square","","Bushido Blade","bushido.blade.2"),
("Bloody Roar","PS1","PS1",1997,"Fighting","Hudson Soft","","Bloody Roar","bloody.roar"),
("Bloody Roar 2","PS1","PS1",1999,"Fighting","Hudson Soft","","Bloody Roar","bloody.roar.2"),
("Battle Arena Toshinden","PS1","PS1",1995,"Fighting","Tamsoft","","Battle Arena Toshinden","battle.arena.toshinden"),
("Battle Arena Toshinden 2","PS1","PS1",1996,"Fighting","Tamsoft","","Battle Arena Toshinden","battle.arena.toshinden.2"),
("Battle Arena Toshinden 3","PS1","PS1",1996,"Fighting","Tamsoft","","Battle Arena Toshinden","battle.arena.toshinden.3"),
("Tomb Raider","PS1","PS1",1996,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider"),
("Tomb Raider II","PS1","PS1",1997,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider.2"),
("Tomb Raider III","PS1","PS1",1998,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider.3"),
("Tomb Raider: The Last Revelation","PS1","PS1",1999,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider.last.revelation"),
("Tomb Raider: Chronicles","PS1","PS1",2000,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider.chronicles"),
("Driver","PS1","PS1",1999,"Racing","Reflections Interactive","","Driver","driver"),
("Driver 2","PS1","PS1",2000,"Racing","Reflections Interactive","","Driver","driver.2"),
("Tony Hawk's Pro Skater","PS1","PS1",1999,"Sports","Neversoft","THPS","Tony Hawk's","tony.hawks.pro.skater|thps"),
("Tony Hawk's Pro Skater 2","PS1","PS1",2000,"Sports","Neversoft","THPS2","Tony Hawk's","tony.hawks.pro.skater.2|thps2"),
("Tony Hawk's Pro Skater 3","PS1","PS1",2001,"Sports","Neversoft","THPS3","Tony Hawk's","tony.hawks.pro.skater.3|thps3"),
("Tony Hawk's Pro Skater 4","PS1","PS1",2002,"Sports","Neversoft","THPS4","Tony Hawk's","tony.hawks.pro.skater.4|thps4"),
("Tony Hawk's Underground","PS1","PS1",2003,"Sports","Neversoft","THUG","Tony Hawk's","tony.hawks.underground|thug"),
("Tony Hawk's Underground 2","PS1","PS1",2004,"Sports","Neversoft","THUG2","Tony Hawk's","tony.hawks.underground.2|thug2"),
("Matt Hoffman's Pro BMX","PS1","PS1",2001,"Sports","Shaba Games","","Matt Hoffman","matt.hoffmans.pro.bmx"),
("Dave Mirra Freestyle BMX","PS1","PS1",2000,"Sports","Z-Axis","","Dave Mirra","dave.mirra.freestyle.bmx"),
("Dave Mirra Freestyle BMX 2","PS1","PS1",2001,"Sports","Z-Axis","","Dave Mirra","dave.mirra.freestyle.bmx.2"),
("Cool Boarders","PS1","PS1",1996,"Sports","Rage Software","","Cool Boarders","cool.boarders"),
("Cool Boarders 2","PS1","PS1",1997,"Sports","Rage Software","","Cool Boarders","cool.boarders.2"),
("Cool Boarders 3","PS1","PS1",1998,"Sports","Rage Software","","Cool Boarders","cool.boarders.3"),
("Cool Boarders 4","PS1","PS1",1999,"Sports","Rage Software","","Cool Boarders","cool.boarders.4"),
("SSX","PS1","PS1",2000,"Sports","EA Canada","","SSX","ssx"),
("SSX Tricky","PS1","PS1",2001,"Sports","EA Canada","","SSX","ssx.tricky"),
("SSX 3","PS1","PS1",2003,"Sports","EA Canada","","SSX","ssx.3"),
("Twisted Metal","PS1","PS1",1995,"Vehicular Combat","SingleTrac","","Twisted Metal","twisted.metal"),
("Twisted Metal 2","PS1","PS1",1996,"Vehicular Combat","SingleTrac","","Twisted Metal","twisted.metal.2"),
("Twisted Metal III","PS1","PS1",1998,"Vehicular Combat","989 Studios","","Twisted Metal","twisted.metal.3"),
("Twisted Metal 4","PS1","PS1",1999,"Vehicular Combat","989 Studios","","Twisted Metal","twisted.metal.4"),
("Twisted Metal: Black","PS1","PS1",2001,"Vehicular Combat","Incog Inc.","","Twisted Metal","twisted.metal.black"),
("Vigilante 8","PS1","PS1",1998,"Vehicular Combat","Luxoflux","","Vigilante 8","vigilante.8"),
("Vigilante 8: Second Offense","PS1","PS1",1999,"Vehicular Combat","Luxoflux","","Vigilante 8","vigilante.8.2nd.offense"),
("Road Rash","PS1","PS1",1995,"Racing","Electronic Arts","","Road Rash","road.rash"),
("Road Rash 3D","PS1","PS1",1998,"Racing","Electronic Arts","","Road Rash","road.rash.3d"),
("Road Rash Jailbreak","PS1","PS1",1999,"Racing","Electronic Arts","","Road Rash","road.rash.jailbreak"),
("Mega Man 8","PS1","PS1",1996,"Action-Platformer","Capcom","","Mega Man","mega.man.8"),
("Mega Man X4","PS1","PS1",1997,"Action-Platformer","Capcom","","Mega Man X","mega.man.x4|mmx4"),
("Mega Man X5","PS1","PS1",2000,"Action-Platformer","Capcom","","Mega Man X","mega.man.x5|mmx5"),
("Mega Man X6","PS1","PS1",2001,"Action-Platformer","Capcom","","Mega Man X","mega.man.x6|mmx6"),
("Mega Man Legends","PS1","PS1",1997,"Action-RPG","Capcom","","Mega Man","mega.man.legends"),
("Mega Man Legends 2","PS1","PS1",2000,"Action-RPG","Capcom","","Mega Man","mega.man.legends.2"),
("Metal Slug X","PS1","PS1",1999,"Run and Gun","SNK","","Metal Slug","metal.slug.x"),
("Syphon Filter","PS1","PS1",1999,"Stealth-Action","Eidetic","","Syphon Filter","syphon.filter"),
("Syphon Filter 2","PS1","PS1",2000,"Stealth-Action","Eidetic","","Syphon Filter","syphon.filter.2"),
("Syphon Filter 3","PS1","PS1",2001,"Stealth-Action","Eidetic","","Syphon Filter","syphon.filter.3"),
("Colony Wars","PS1","PS1",1997,"Space Combat","Psygnosis","","Colony Wars","colony.wars"),
("Colony Wars: Vengeance","PS1","PS1",1998,"Space Combat","Psygnosis","","Colony Wars","colony.wars.vengeance"),
("Colony Wars: Red Sun","PS1","PS1",2000,"Space Combat","Psygnosis","","Colony Wars","colony.wars.red.sun"),
("Rayman","PS1","PS1",1995,"Platformer","Ubisoft","","Rayman","rayman"),
("Rayman 2: The Great Escape","PS1","PS1",1999,"Platformer","Ubisoft","","Rayman","rayman.2|great.escape"),
("Wipeout","PS1","PS1",1995,"Racing","Psygnosis","","Wipeout","wipeout"),
("Wipeout XL","PS1","PS1",1996,"Racing","Psygnosis","Wipeout 2097","Wipeout","wipeout.xl|wipeout.2097"),
("Wipeout 3","PS1","PS1",1999,"Racing","Psygnosis","","Wipeout","wipeout.3"),
("Colin McRae Rally","PS1","PS1",1998,"Racing","Codemasters","","Colin McRae Rally","colin.mcrae.rally"),
("Colin McRae Rally 2.0","PS1","PS1",2000,"Racing","Codemasters","","Colin McRae Rally","colin.mcrae.rally.2"),
("V-Rally","PS1","PS1",1997,"Racing","Infogrames","","V-Rally","v.rally"),
("V-Rally 2","PS1","PS1",1999,"Racing","Infogrames","","V-Rally","v.rally.2"),
("Need for Speed","PS1","PS1",1996,"Racing","Electronic Arts","","Need for Speed","need.for.speed|nfs"),
("Need for Speed II","PS1","PS1",1997,"Racing","Electronic Arts","","Need for Speed","need.for.speed.2|nfs2"),
("Need for Speed III: Hot Pursuit","PS1","PS1",1998,"Racing","Electronic Arts","","Need for Speed","need.for.speed.3|nfs3|hot.pursuit"),
("Need for Speed: High Stakes","PS1","PS1",1999,"Racing","Electronic Arts","","Need for Speed","need.for.speed.high.stakes|nfs4"),
("Need for Speed: Porsche Unleashed","PS1","PS1",2000,"Racing","Electronic Arts","","Need for Speed","need.for.speed.porsche.unleashed|nfs5"),
("Crash Bash","PS1","PS1",2000,"Party","Eurocom","","Crash Bandicoot","crash.bash"),
("Crash Bandicoot 4: The Wrath of Cortex","PS1","PS1",2001,"Platformer","Traveller's Tales","","Crash Bandicoot","crash.bandicoot.4|wrath.of.cortex"),
("Spyro: Season of Ice","PS1","PS1",2001,"Platformer","Digital Eclipse","","Spyro","spyro.season.of.ice"),
("Spyro: Flame of Fury","PS1","PS1",2002,"Platformer","Digital Eclipse","","Spyro","spyro.flame.of.fury"),
("Croc: Legend of the Gobbos","PS1","PS1",1997,"Platformer","Argonaut Games","","Croc","croc|legend.of.the.gobbos"),
("Croc 2","PS1","PS1",1999,"Platformer","Argonaut Games","","Croc","croc.2"),
("Gex 3: Deep Cover Gecko","PS1","PS1",1999,"Platformer","Crystal Dynamics","","Gex","gex.3|deep.cover.gecko"),
("Blasto","PS1","PS1",1998,"Third-Person Shooter","Sony","","Blasto","blasto"),
("MediEvil 2","PS1","PS1",2000,"Action-Adventure","SCE Cambridge","","MediEvil","medievil.2"),
("Herc's Adventures","PS1","PS1",1997,"Action-Adventure","Big Ape Productions","","Herc's Adventures","hercs.adventures"),
("Pandemonium!","PS1","PS1",1996,"Platformer","Toy Studio","","Pandemonium!","pandemonium"),
("Pandemonium 2","PS1","PS1",1997,"Platformer","Toy Studio","","Pandemonium","pandemonium.2"),
("Jumping Flash!","PS1","PS1",1995,"Platformer","Exact","","Jumping Flash!","jumping.flash"),
("Jumping Flash! 2","PS1","PS1",1996,"Platformer","Exact","","Jumping Flash!","jumping.flash.2"),
("Ridge Racer Type 4","PS1","PS1",1998,"Racing","Namco","","Ridge Racer","ridge.racer.type.4|r4"),
("Circuit Breakers","PS1","PS1",1998,"Racing","Midas Interactive","","Circuit Breakers","circuit.breakers"),
("Point Blank","PS1","PS1",1998,"Shooter","Namco","","Point Blank","point.blank"),
("Point Blank 2","PS1","PS1",1999,"Shooter","Namco","","Point Blank","point.blank.2"),
("Point Blank 3","PS1","PS1",2001,"Shooter","Namco","","Point Blank","point.blank.3"),
("Destruction Derby","PS1","PS1",1995,"Racing","Psygnosis","","Destruction Derby","destruction.derby"),
("Destruction Derby 2","PS1","PS1",1996,"Racing","Psygnosis","","Destruction Derby","destruction.derby.2"),
("Destruction Derby Raw","PS1","PS1",2000,"Racing","Studio 33","","Destruction Derby","destruction.derby.raw"),
("Micro Machines V3","PS1","PS1",1997,"Racing","Codemasters","","Micro Machines","micro.machines.v3"),
("Mike Piazza's Strike Zone","PS1","PS1",1998,"Sports","Kemco","","Mike Piazza","mike.piazzas.strike.zone"),
("Fighting Force","PS1","PS1",1997,"Beat 'em Up","Core Design","","Fighting Force","fighting.force"),
("Fighting Force 2","PS1","PS1",1999,"Action","Core Design","","Fighting Force","fighting.force.2"),
("Street Fighter EX Plus Alpha","PS1","PS1",1997,"Fighting","Arika","","Street Fighter","street.fighter.ex.plus.alpha"),
("Marvel Super Heroes vs. Street Fighter","PS1","PS1",1998,"Fighting","Capcom","","Marvel vs. Capcom","marvel.super.heroes.vs.street.fighter"),
("Ehrgeiz: God Bless the Ring","PS1","PS1",1998,"Fighting","Square","","Ehrgeiz","ehrgeiz"),
("Fighting Vipers","PS1","PS1",1996,"Fighting","Sega","","Fighting Vipers","fighting.vipers"),
("Guilty Gear","PS1","PS1",1998,"Fighting","Arc System Works","","Guilty Gear","guilty.gear"),
("Street Fighter: The Movie","PS1","PS1",1995,"Fighting","Capcom","","Street Fighter","street.fighter.the.movie"),
("Star Wars: Dark Forces","PS1","PS1",1997,"FPS","LucasArts","","Star Wars","star.wars.dark.forces"),
("Star Wars: Jedi Knight - Dark Forces II","PS1","PS1",1997,"FPS","LucasArts","","Star Wars","star.wars.jedi.knight|dark.forces.2"),
("Star Wars: Jedi Knight II - Jedi Outcast","PS1","PS1",2002,"FPS","Raven Software","","Star Wars","star.wars.jedi.outcast|jedi.knight.2"),
("Medal of Honor","PS1","PS1",1999,"FPS","DreamWorks Interactive","","Medal of Honor","medal.of.honor|moh"),
("Medal of Honor: Underground","PS1","PS1",2000,"FPS","DreamWorks Interactive","","Medal of Honor","medal.of.honor.underground"),
("Doom","PS1","PS1",1995,"FPS","id Software","","Doom","doom"),
("Doom II","PS1","PS1",1995,"FPS","id Software","","Doom","doom.2"),
("Final Doom","PS1","PS1",1996,"FPS","id Software","","Doom","final.doom"),
("Quake II","PS1","PS1",1999,"FPS","id Software","","Quake","quake.2|quake.ii"),
("Duke Nukem: Time to Kill","PS1","PS1",1998,"Third-Person Shooter","GT Interactive","","Duke Nukem","duke.nukem.time.to.kill"),
("Duke Nukem: Land of the Babes","PS1","PS1",2000,"Third-Person Shooter","GT Interactive","","Duke Nukem","duke.nukem.land.of.the.babes"),
("Hexen","PS1","PS1",1995,"FPS","id Software","","Hexen","hexen"),
("Hexen II","PS1","PS1",1997,"FPS","id Software","","Hexen","hexen.2|hexen.ii"),
("Alien Resurrection","PS1","PS1",2000,"FPS","Argonaut Games","","Alien","alien.resurrection"),
("Resident Evil Survivor","PS1","PS1",2000,"Survival Horror","Capcom","","Resident Evil","resident.evil.survivor"),
("Resident Evil: Code Veronica","PS1","PS1",2001,"Survival Horror","Capcom","","Resident Evil","resident.evil.code.veronica"),
("Dino Crisis","PS1","PS1",1999,"Survival Horror","Capcom","","Dino Crisis","dino.crisis"),
("Dino Crisis 2","PS1","PS1",2000,"Survival Horror","Capcom","","Dino Crisis","dino.crisis.2"),
("Clock Tower","PS1","PS1",1996,"Survival Horror","Human Entertainment","","Clock Tower","clock.tower"),
("Clock Tower II: The Struggle Within","PS1","PS1",1998,"Survival Horror","Human Entertainment","","Clock Tower","clock.tower.2"),
("Koudelka","PS1","PS1",1999,"Survival Horror","Sacnoth","","Koudelka","koudelka"),
("Thousand Arms","PS1","PS1",1998,"RPG","Red Company","","Thousand Arms","thousand.arms"),
("Atelier Marie","PS1","PS1",1997,"RPG","Gust","","Atelier","atelier.marie"),
("Atelier Elie","PS1","PS1",1998,"RPG","Gust","","Atelier","atelier.elie"),
("Rhapsody: A Musical Adventure","PS1","PS1",1998,"RPG","Nippon Ichi Software","","Rhapsody","rhapsody"),
("Disgaea: Hour of Darkness","PS1","PS1",2003,"Tactical RPG","Nippon Ichi Software","","Disgaea","disgaea|hour.of.darkness"),
("Harvest Moon: Back to Nature","PS1","PS1",1999,"Simulation","Natsume","","Harvest Moon","harvest.moon.back.to.nature"),
("Harvest Moon: Save the Homeland","PS1","PS1",2001,"Simulation","Natsume","","Harvest Moon","harvest.moon.save.the.homeland"),
("Bust-a-Move 2","PS1","PS1",1996,"Puzzle","Taito","","Bust-a-Move","bust.a.move.2"),
("Bust-a-Move 3","PS1","PSES",1997,"Puzzle","Taito","","Bust-a-Move","bust.a.move.3"),
("Bust-a-Move 4","PS1","PS1",1999,"Puzzle","Taito","","Bust-a-Move","bust.a.move.4"),
("Puzzle Bobble","PS1","PS1",1995,"Puzzle","Taito","","Puzzle Bobble","puzzle.bobble"),
("Tetris Plus","PS1","PS1",1996,"Puzzle","Jaleco","","Tetris","tetris.plus"),
("Tetris Plus 2","PS1","PS1",1997,"Puzzle","Jaleco","","Tetris","tetris.plus.2"),
("Intelligent Qube","PS1","PS1",1997,"Puzzle","SCEI","","Intelligent Qube","intelligent.qube|kurushi"),
("Kurushi","PS1","PS1",1997,"Puzzle","SCEI","","Intelligent Qube","kurushi|intelligent.qube"),
("Devil Dice","PS1","PS1",1998,"Puzzle","SCEI","","Devil Dice","devil.dice"),
("Bishi Bashi Special","PS1","PS1",1998,"Party","Konami","","Bishi Bashi","bishi.bashi.special"),
("Poy Poy","PS1","PS1",1997,"Action","Konami","","Poy Poy","poy.poy"),
("Poy Poy 2","PS1","PS1",1998,"Action","Konami","","Poy Poy","poy.poy.2"),
("Super Puzzle Fighter II Turbo","PS1","PS1",1997,"Puzzle","Capcom","","Street Fighter","super.puzzle.fighter.2.turbo"),
("Scooter Shooter","PS1","PS1",1997,"Shooter","Taito","","Scooter Shooter","scooter.shooter"),
("SimCity 2000","PS1","PS1",1997,"Simulation","Maxis","","SimCity","simcity.2000"),
("Theme Hospital","PS1","PS1",1998,"Simulation","Bullfrog Productions","","Theme","theme.hospital"),
("Theme Park","PS1","PS1",1995,"Simulation","Bullfrog Productions","","Theme","theme.park"),
("RollerCoaster Tycoon","PS1","PS1",1999,"Simulation","Chris Sawyer","","RollerCoaster Tycoon","rollercoaster.tycoon"),
("Command & Conquer: Red Alert","PS1","PS1",1997,"Strategy","Westwood Studios","","Command & Conquer","command.and.conquer.red.alert"),
("Command & Conquer: Red Alert Retaliation","PS1","PS1",1998,"Strategy","Westwood Studios","","Command & Conquer","cnc.red.alert.retaliation"),
("Command & Conquer: Retaliation","PS1","PS1",1998,"Strategy","Westwood Studios","","Command & Conquer","cnc.retaliation"),
("Star Ocean: The Second Story","PS1","PS1",1998,"RPG","tri-Ace","","Star Ocean","star.ocean.the.second.story"),
("Tales of Destiny","PS1","PS1",1997,"RPG","Namco","","Tales","tales.of.destiny"),
("Tales of Eternia","PS1","PS1",2000,"RPG","Namco","","Tales","tales.of.eternia"),
("Xenogears","PS1","PS1",1998,"RPG","Square","","Xeno","xenogears"),
("Discworld","PS1","PS1",1995,"Adventure","Perfect Entertainment","","Discworld","discworld"),
("Discworld II: Missing Presumed...!?","PS1","PS1",1996,"Adventure","Perfect Entertainment","","Discworld","discworld.2"),
("Broken Sword: The Shadow of the Templars","PS1","PS1",1996,"Adventure","Revolution Software","","Broken Sword","broken.sword|shadow.of.the.templars"),
("Broken Sword II: The Smoking Mirror","PS1","PS1",1997,"Adventure","Revolution Software","","Broken Sword","broken.sword.2|smoking.mirror"),
("Mortal Kombat Mythologies: Sub-Zero","PS1","PS1",1997,"Action-Adventure","Midway","","Mortal Kombat","mortal.kombat.mythologies.sub.zero"),
("Mortal Kombat: Special Forces","PS1","PS1",2000,"Action","Midway","","Mortal Kombat","mortal.kombat.special.forces"),
("Worms","PS1","PS1",1996,"Strategy","Team17","","Worms","worms"),
("Worms: Armageddon","PS1","PS1",1999,"Strategy","Team17","","Worms","worms.armageddon"),
("Worms World Party","PS1","PS1",2001,"Strategy","Team17","","Worms","worms.world.party"),
("Hogs of War","PS1","PS1",2000,"Strategy","Infogrames","","Hogs of War","hogs.of.war"),
("Captain Commando","PS1","PSES",1998,"Beat 'em Up","Capcom","","Captain Commando","captain.commando"),
("Musashi: Samurai Legend","PS1","PS1",1998,"Action-RPG","Square","","Musashi","musashi.samurai.legend"),
("Brave Fencer Musashi","PS1","PS1",1998,"Action-RPG","Square","","Musashi","brave.fencer.musashi"),
("Einhander","PS1","PS1",1997,"Shoot 'em Up","Square","","Einhander","einhander"),
("G-Darius","PS1","PS1",1998,"Shoot 'em Up","Taito","","Darius","g.darius"),
("R-Type Delta","PS1","PS1",1998,"Shoot 'em Up","Irem","","R-Type","r.type.delta"),
("RayCrisis","PS1","PS1",1998,"Shoot 'em Up","Taito","","Ray","raycrisis"),
("Guitar Freaks","PS1","PS1",1998,"Rhythm","Konami","","Guitar Freaks","guitar.freaks"),
("Dance Dance Revolution","PS1","PS1",1998,"Rhythm","Konami","DDR","Dance Dance Revolution","dance.dance.revolution|ddr"),
("Beatmania","PS1","PS1",1997,"Rhythm","Konami","","Beatmania","beatmania"),
("PaRappa the Rapper","PS1","PS1",1996,"Rhythm","NanaOn-Sha","","PaRappa the Rapper","parappa.the.rapper"),
("UmJammer Lammy","PS1","PS1",1999,"Rhythm","NanaOn-Sha","","PaRappa the Rapper","umjammer.lammy"),
("Space Channel 5","PS1","PS1",2000,"Rhythm","United Game Artists","","Space Channel 5","space.channel.5"),
("Rez","PS1","PS1",2001,"Rail Shooter","United Game Artists","","Rez","rez"),
("D","PS1","PS1",1995,"Adventure","Warp","","D","d"),
("D2","PS1","PS1",2000,"Adventure","Warp","","D","d2"),
("Hellnight","PS1","PS1",1998,"Survival Horror","Atlus","","Hellnight","hellnight"),
("OverBlood","PS1","PS1",1996,"Action-Adventure","Riverhillsoft","","OverBlood","overblood"),
("OverBlood 2","PS1","PS1",1998,"Action-Adventure","Riverhillsoft","","OverBlood","overblood.2"),
("Nightmare Creatures","PS1","PS1",1997,"Action","Kalypso Media","","Nightmare Creatures","nightmare.creatures"),
("Nightmare Creatures II","PS1","PS1",2000,"Action","Kalypso Media","","Nightmare Creatures","nightmare.creatures.2"),
("Skullmonkeys","PS1","PS1",1998,"Platformer","The Neverhood Inc.","","Skullmonkeys","skullmonkeys"),
("The Neverhood","PS1","PS1",1996,"Adventure","The Neverhood Inc.","","The Neverhood","neverhood"),
("Heart of Darkness","PS1","PS1",1998,"Platformer","Amazing Studio","","Heart of Darkness","heart.of.darkness"),
("Hexplore","PS1","PS1",1998,"Action-RPG","Heliovisions Productions","","Hexplore","hexplore"),
("Soul of the Samurai","PS1","PS1",1999,"Action-Adventure","Konami","","Soul of the Samurai","soul.of.the.samurai"),
("Incredible Crisis","PS1","PS1",1999,"Party","SCEI","","Incredible Crisis","incredible.crisis"),
("Blast Radius","PS1","PS1",1999,"Shoot 'em Up","Psygnosis","","Blast Radius","blast.radius"),
("Legacy of Kain: Soul Reaver","PS1","PS1",1999,"Action-Adventure","Crystal Dynamics","","Legacy of Kain","legacy.of.kain.soul.reaver|soul.reaver"),
("Legacy of Kain: Soul Reaver 2","PS1","PS1",2001,"Action-Adventure","Crystal Dynamics","","Legacy of Kain","legacy.of.kain.soul.reaver.2"),
("Blood Omen: Legacy of Kain","PS1","PS1",1996,"Action-Adventure","Crystal Dynamics","","Legacy of Kain","blood.omen.legacy.of.kain"),
("Gex: Enter the Gecko","PS1","PS1",1998,"Platformer","Crystal Dynamics","","Gex","gex.enter.the.gecko"),
("C-12: Final Resistance","PS1","PS1",2001,"Third-Person Shooter","SCEI","","C-12","c12.final.resistance"),
("Eternal Darkness","PS1","PS1",2002,"Action-Adventure","Silicon Knights","","Eternal Darkness","eternal.darkness"),
("Popolocrois Monogatari","PS1","PS1",1996,"RPG","SCEI","","Popolocrois","popolocrois"),
("Azure Dreams","PS1","PS1",1997,"RPG","Konami","","Azure Dreams","azure.dreams"),
("Mischief Makers","PS1","PS1",1997,"Platformer","Treasure","","Mischief Makers","mischief.makers"),
("Silhouette Mirage","PS1","PS1",1997,"Action-Platformer","Treasure","","Silhouette Mirage","silhouette.mirage"),
("Rayman 2: Revolution","PS1","PS1",2000,"Platformer","Ubisoft","","Rayman","rayman.2.revolution"),
("Hercules","PS1","PS1",1997,"Action-Platformer","Disney Interactive","","Hercules","hercules"),
("The Little Mermaid II","PS1","PS1",2000,"Action","Disney Interactive","","The Little Mermaid","little.mermaid.2"),
("Tarzan","PS1","PS1",1999,"Platformer","Eurocom","","Tarzan","tarzan"),
("A Bug's Life","PS1","PS1",1998,"Platformer","Treyarch","","A Bug's Life","a.bugs.life"),
("Toy Story 2: Buzz Lightyear to the Rescue","PS1","PS1",1999,"Platformer","Traveller's Tales","","Toy Story","toy.story.2|buzz.lightyear.to.the.rescue"),
("Monsters Inc.","PS1","PS1",2001,"Platformer","Kodiak Interactive","","Monsters Inc.","monsters.inc"),
("SpongeBob SquarePants: SuperSponge","PS1","PS1",2001,"Platformer","Climax Studios","","SpongeBob SquarePants","spongebob.supersponge"),
("Rugrats: Search for Reptar","PS1","PS1",1998,"Platformer","n-Space","","Rugrats","rugrats.search.for.reptar"),
("Rugrats in Paris: The Movie","PS1","PS1",2000,"Platformer","n-Space","","Rugrats","rugrats.in.paris"),
("Harry Potter and the Philosopher's Stone","PS1","PS1",2001,"Action-Adventure","Argonaut Games","","Harry Potter","harry.potter.and.the.philosophers.stone"),
("Harry Potter and the Chamber of Secrets","PS1","PS1",2002,"Action-Adventure","Argonaut Games","","Harry Potter","harry.potter.and.the.chamber.of.secrets"),
("Harry Potter and the Prisoner of Azkaban","PS1","PS1",2004,"Action-Adventure","EA UK","","Harry Potter","harry.potter.and.the.prisoner.of.azkaban"),
("Harry Potter and the Goblet of Fire","PS1","PS1",2005,"Action-Adventure","EA UK","","Harry Potter","harry.potter.and.the.goblet.of.fire"),
("Harry Potter: Quidditch World Cup","PS1","PS1",2003,"Sports","EA UK","","Harry Potter","harry.potter.quidditch.world.cup"),
("Lord of the Rings: The Fellowship of the Ring","PS1","PS1",2002,"Action-Adventure","Surreal Software","","Lord of the Rings","lord.of.the.rings.fellowship.of.the.ring"),
("Lord of the Rings: The Two Towers","PS1","PS1",2002,"Action","Stormfront Studios","","Lord of the Rings","lord.of.the.rings.two.towers"),
("Lord of the Rings: The Return of the King","PS1","PS1",2003,"Action","EA Redwood Shores","","Lord of the Rings","lord.of.the.rings.return.of.the.king"),
("James Bond 007: Tomorrow Never Dies","PS1","PS1",1999,"Third-Person Shooter","Black Ops Entertainment","","James Bond","james.bond.tomorrow.never.dies"),
("James Bond 007: The World Is Not Enough","PS1","PS1",2000,"FPS","Eurocom","","James Bond","james.bond.the.world.is.not.enough"),
("James Bond 007: Agent Under Fire","PS1","PS1",2001,"FPS","Eurocom","","James Bond","james.bond.agent.under.fire"),
("James Bond 007: Nightfire","PS1","PS1",2002,"FPS","Eurocom","","James Bond","james.bond.nightfire"),
("James Bond 007: Everything or Nothing","PS1","PS1",2004,"Third-Person Shooter","EA Los Angeles","","James Bond","james.bond.everything.or.nothing"),
("Spyro: Enter the Dragonfly","PS1","PS1",2002,"Platformer","Equinoxe Digital Entertainment","","Spyro","spyro.enter.the.dragonfly"),
("Crash Nitro Kart","PS1","PS1",2003,"Racing","Vicarious Visions","","Crash Bandicoot","crash.nitro.kart"),
("Spyro 2: Season of Flame","PS1","PS1",2002,"Platformer","Digital Eclipse","","Spyro","spyro.2|season.of.flame"),
("Mega Man Anniversary Collection","PS1","PS1",2004,"Compilation","Capcom","","Mega Man","mega.man.anniversary.collection"),
("Street Fighter Anniversary Collection","PS1","PS1",2004,"Compilation","Capcom","","Street Fighter","street.fighter.anniversary.collection"),
]
batch_add(ps1_games)
print(f"PS1: {len(ps1_games)}")

# ===================== PS2 (600 games) =====================
ps2_games = [
("Grand Theft Auto III","PS2","PS2",2001,"Action-Adventure","Rockstar North","GTA 3","Grand Theft Auto","grand.theft.auto.3|gta3|gta.iii"),
("Grand Theft Auto: Vice City","PS2","PS2",2002,"Action-Adventure","Rockstar North","GTA VC","Grand Theft Auto","grand.theft.auto.vice.city|gta.vc"),
("Grand Theft Auto: San Andreas","PS2","PS2",2004,"Action-Adventure","Rockstar North","GTA SA","Grand Theft Auto","grand.theft.auto.san.andreas|gta.sa"),
("God of War","PS2","PS2",2005,"Action-Adventure","SCE Santa Monica","","God of War","god.of.war"),
("God of War II","PS2","PS2",2007,"Action-Adventure","SCE Santa Monica","","God of War","god.of.war.2"),
("Shadow of the Colossus","PS2","PS2",2005,"Action-Adventure","Team ICO","","Shadow of the Colossus","shadow.of.the.colossus"),
("Ico","PS2","PS2",2001,"Action-Adventure","Team ICO","","Ico","ico"),
("Kingdom Hearts","PS2","PS2",2002,"Action-RPG","Square","","Kingdom Hearts","kingdom.hearts"),
("Kingdom Hearts II","PS2","PS2",2005,"Action-RPG","Square","","Kingdom Hearts","kingdom.hearts.2"),
("Kingdom Hearts: Chain of Memories","PS2","PS2",2004,"Action-RPG","Square","","Kingdom Hearts","kingdom.hearts.chain.of.memories"),
("Final Fantasy X","PS2","PS2",2001,"RPG","Square","FFX","Final Fantasy","final.fantasy.10|ffx"),
("Final Fantasy X-2","PS2","PS2",2003,"RPG","Square","","Final Fantasy","final.fantasy.10.2|ffx.2"),
("Final Fantasy XII","PS2","PS2",2006,"RPG","Square","FFXII","Final Fantasy","final.fantasy.12|ffxii"),
("Final Fantasy XI","PS2","PS2",2002,"MMORPG","Square","FFXI","Final Fantasy","final.fantasy.11|ffxi"),
("Dragon Quest VIII: Journey of the Cursed King","PS2","PS2",2004,"RPG","Level-5","","Dragon Quest","dragon.quest.8"),
("Dragon Quest VII","PS2","PS2",2000,"RPG","Heartbeat","","Dragon Quest","dragon.quest.7"),
("Metal Gear Solid 2: Sons of Liberty","PS2","PS2",2001,"Stealth-Action","Konami","MGS2","Metal Gear","metal.gear.solid.2|sons.of.liberty|mgs2"),
("Metal Gear Solid 3: Snake Eater","PS2","PS2",2004,"Stealth-Action","Konami","MGS3","Metal Gear","metal.gear.solid.3|snake.eater|mgs3"),
("Metal Gear Solid: Substance","PS2","PS2",2002,"Stealth-Action","Konami","","Metal Gear","metal.gear.solid.substance"),
("Resident Evil 4","PS2","PS2",2005,"Survival Horror","Capcom","RE4","Resident Evil","resident.evil.4|re4"),
("Devil May Cry","PS2","PS2",2001,"Action-Adventure","Capcom","DMC","Devil May Cry","devil.may.cry|dmc"),
("Devil May Cry 2","PS2","PS2",2003,"Action-Adventure","Capcom","DMC2","Devil May Cry","devil.may.cry.2|dmc2"),
("Devil May Cry 3: Dante's Awakening","PS2","PS2",2005,"Action-Adventure","Capcom","DMC3","Devil May Cry","devil.may.cry.3|dantes.awakening|dmc3"),
("Onimusha: Warlords","PS2","PS2",2001,"Action-Adventure","Capcom","","Onimusha","onimusha|warlords"),
("Onimusha 2: Samurai's Destiny","PS2","PS2",2002,"Action-Adventure","Capcom","","Onimusha","onimusha.2|samurais.destiny"),
("Onimusha 3: Demon Siege","PS2","PS2",2004,"Action-Adventure","Capcom","","Onimusha","onimusha.3|demon.siege"),
("Ratchet & Clank","PS2","PS2",2002,"Platformer","Insomniac Games","","Ratchet & Clank","ratchet.and.clank"),
("Ratchet & Clank: Going Commando","PS2","PS2",2003,"Platformer","Insomniac Games","","Ratchet & Clank","ratchet.and.clank.going.commando"),
("Ratchet & Clank: Up Your Arsenal","PS2","PS2",2004,"Platformer","Insomniac Games","","Ratchet & Clank","ratchet.and.clank.up.your.arsenal"),
("Ratchet & Clank: Deadlocked","PS2","PS2",2005,"Platformer","Insomniac Games","","Ratchet & Clank","ratchet.and.clank.deadlocked"),
("Jak and Daxter: The Precursor Legacy","PS2","PS2",2001,"Platformer","Naughty Dog","","Jak and Daxter","jak.and.daxter|precursor.legacy"),
("Jak II: Renegade","PS2","PS2",2003,"Platformer","Naughty Dog","","Jak and Daxter","jak.2|renegade"),
("Jak 3","PS2","PS2",2004,"Platformer","Naughty Dog","","Jak and Daxter","jak.3"),
("Jak X: Combat Racing","PS2","PS2",2005,"Racing","Naughty Dog","","Jak and Daxter","jak.x|combat.racing"),
("Sly Cooper and the Thievius Raccoonus","PS2","PS2",2002,"Platformer","Sucker Punch","","Sly Cooper","sly.cooper|thievius.raccoonus"),
("Sly 2: Band of Thieves","PS2","PS2",2004,"Platformer","Sucker Punch","","Sly Cooper","sly.2|band.of.thieves"),
("Sly 3: Honor Among Thieves","PS2","PS2",2005,"Platformer","Sucker Punch","","Sly Cooper","sly.3|honor.among.thieves"),
("Gran Turismo 3: A-Spec","PS2","PS2",2001,"Racing","Polyphony Digital","GT3","Gran Turismo","gran.turismo.3|gt3"),
("Gran Turismo 4","PS2","PS2",2004,"Racing","Polyphony Digital","GT4","Gran Turismo","gran.turismo.4|gt4"),
("Gran Turismo: Concept","PS2","PS2",2002,"Racing","Polyphony Digital","","Gran Turismo","gran.turismo.concept"),
("Gran Turismo 4: Prologue","PS2","PS2",2003,"Racing","Polyphony Digital","","Gran Turismo","gran.turismo.4.prologue"),
("Tekken 4","PS2","PS2",2001,"Fighting","Namco","","Tekken","tekken.4"),
("Tekken 5","PS2","PS2",2004,"Fighting","Namco","","Tekken","tekken.5"),
("Tekken Tag Tournament","PS2","PS2",1999,"Fighting","Namco","","Tekken","tekken.tag.tournament"),
("Virtua Fighter 4","PS2","PS2",2001,"Fighting","Sega AM2","","Virtua Fighter","virtua.fighter.4"),
("Virtua Fighter 4: Evolution","PS2","PS2",2003,"Fighting","Sega AM2","","Virtua Fighter","virtua.fighter.4.evolution"),
("Soulcalibur II","PS2","PS2",2003,"Fighting","Namco","","Soulcalibur","soulcalibur.2"),
("Soulcalibur III","PS2","PS2",2005,"Fighting","Namco","","Soulcalibur","soulcalibur.3"),
("Mortal Kombat: Deadly Alliance","PS2","PS2",2002,"Fighting","Midway","","Mortal Kombat","mortal.kombat.deadly.alliance"),
("Mortal Kombat: Deception","PS2","PS2",2004,"Fighting","Midway","","Mortal Kombat","mortal.kombat.deception"),
("Mortal Kombat: Armageddon","PS2","PS2",2006,"Fighting","Midway","","Mortal Kombat","mortal.kombat.armageddon"),
("Mortal Kombat: Shaolin Monks","PS2","PS2",2005,"Beat 'em Up","Midway","","Mortal Kombat","mortal.kombat.shaolin.monks"),
("Street Fighter III: 3rd Strike","PS2","PS2",2000,"Fighting","Capcom","","Street Fighter","street.fighter.3.3rd.strike"),
("Guilty Gear X2","PS2","PS2",2002,"Fighting","Arc System Works","","Guilty Gear","guilty.gear.x2"),
("Guilty Gear XX","PS2","PS2",2003,"Fighting","Arc System Works","","Guilty Gear","guilty.gear.xx"),
("Marvel vs. Capcom 2: New Age of Heroes","PS2","PS2",2000,"Fighting","Capcom","MvC2","Marvel vs. Capcom","marvel.vs.capcom.2|mvc2"),
("Bloody Roar 3","PS2","PS2",2001,"Fighting","Hudson Soft","","Bloody Roar","bloody.roar.3"),
("Bloody Roar 4","PS2","PS2",2003,"Fighting","Hudson Soft","","Bloody Roar","bloody.roar.4"),
("DBZ Budokai","PS2","PS2",2002,"Fighting","Dimps","","Dragon Ball Z","dragon.ball.z.budokai|dbz.budokai"),
("DBZ Budokai 2","PS2","PS2",2003,"Fighting","Dimps","","Dragon Ball Z","dragon.ball.z.budokai.2|dbz.budokai.2"),
("DBZ Budokai 3","PS2","PS2",2004,"Fighting","Dimps","","Dragon Ball Z","dragon.ball.z.budokai.3|dbz.budokai.3"),
("DBZ Tenkaichi","PS2","PS2",2005,"Fighting","Spike","","Dragon Ball Z","dragon.ball.z.tenkaichi|dbz.tenkaichi"),
("DBZ Tenkaichi 2","PS2","PS2",2006,"Fighting","Spike","","Dragon Ball Z","dragon.ball.z.tenkaichi.2|dbz.tenkaichi.2"),
("DBZ Tenkaichi 3","PS2","PS2",2007,"Fighting","Spike","","Dragon Ball Z","dragon.ball.z.tenkaichi.3|dbz.tenkaichi.3"),
("Naruto: Ultimate Ninja","PS2","PS2",2004,"Fighting","CyberConnect2","","Naruto","naruto.ultimate.ninja"),
("Naruto: Ultimate Ninja 2","PS2","PS2",2005,"Fighting","CyberConnect2","","Naruto","naruto.ultimate.ninja.2"),
("Naruto: Ultimate Ninja 3","PS2","PS2",2006,"Fighting","CyberConnect2","","Naruto","naruto.ultimate.ninja.3"),
("Naruto Shippuden: Ultimate Ninja 4","PS2","PS2",2007,"Fighting","CyberConnect2","","Naruto","naruto.ultimate.ninja.4"),
("Naruto Shippuden: Ultimate Ninja 5","PS2","PS2",2008,"Fighting","CyberConnect2","","Naruto","naruto.ultimate.ninja.5"),
("Crash Bandicoot: The Wrath of Cortex","PS2","PS2",2001,"Platformer","Traveller's Tales","","Crash Bandicoot","crash.bandicoot.wrath.of.cortex"),
("Crash Nitro Kart","PS2","PS2",2003,"Racing","Vicarious Visions","","Crash Bandicoot","crash.nitro.kart"),
("Crash Twinsanity","PS2","PS2",2004,"Platformer","Traveller's Tales","","Crash Bandicoot","crash.twinsanity"),
("Crash Tag Team Racing","PS2","PS2",2005,"Racing","Vicarious Visions","","Crash Bandicoot","crash.tag.team.racing"),
("Spyro: Enter the Dragonfly","PS2","PS2",2002,"Platformer","Equinoxe","","Spyro","spyro.enter.the.dragonfly"),
("Spyro: A Hero's Tail","PS2","PS2",2004,"Platformer","Eurocom","","Spyro","spyro.a.herbs.tail|heros.tail"),
("Burnout","PS2","PS2",2001,"Racing","Criterion Games","","Burnout","burnout"),
("Burnout 2: Point of Impact","PS2","PS2",2002,"Racing","Criterion Games","","Burnout","burnout.2|point.of.impact"),
("Burnout 3: Takedown","PS2","PS2",2004,"Racing","Criterion Games","","Burnout","burnout.3|takedown"),
("Burnout Revenge","PS2","PS2",2005,"Racing","Criterion Games","","Burnout","burnout.revenge"),
("Burnout Dominator","PS2","PS2",2007,"Racing","Criterion Games","","Burnout","burnout.dominator"),
("Need for Speed: Underground","PS2","PS2",2003,"Racing","EA Canada","","Need for Speed","need.for.speed.underground|nfsu"),
("Need for Speed: Underground 2","PS2","PS2",2004,"Racing","EA Canada","","Need for Speed","need.for.speed.underground.2|nfsu2"),
("Need for Speed: Most Wanted","PS2","PS2",2005,"Racing","EA Canada","","Need for Speed","need.for.speed.most.wanted|nfs.most.wanted"),
("Need for Speed: Carbon","PS2","PS2",2006,"Racing","EA Canada","","Need for Speed","need.for.speed.carbon|nfs.carbon"),
("Need for Speed: ProStreet","PS2","PS2",2007,"Racing","EA Canada","","Need for Speed","need.for.speed.prostreet"),
("Need for Speed: Underground Rivals","PS2","PS2",2005,"Racing","EA Canada","","Need for Speed","need.for.speed.underground.rivals"),
("Need for Speed: Most Wanted 5-1-0","PS2","PS2",2005,"Racing","EA Canada","","Need for Speed","need.for.speed.most.wanted.5.1.0"),
("Need for Speed: Shift","PS2","PS2",2009,"Racing","Slightly Mad Studios","","Need for Speed","need.for.speed.shift"),
("Midnight Club 3: DUB Edition","PS2","PS2",2005,"Racing","Rockstar San Diego","","Midnight Club","midnight.club.3|dub.edition"),
("Midnight Club: Los Angeles","PS2","PS2",2008,"Racing","Rockstar San Diego","","Midnight Club","midnight.club.los.angeles"),
("Midnight Club: Street Racing","PS2","PS2",2000,"Racing","Rockstar San Diego","","Midnight Club","midnight.club.street.racing"),
("Tony Hawk's Pro Skater 3","PS2","PS2",2001,"Sports","Neversoft","THPS3","Tony Hawk's","tony.hawks.pro.skater.3"),
("Tony Hawk's Pro Skater 4","PS2","PS2",2002,"Sports","Neversoft","THPS4","Tony Hawk's","tony.hawks.pro.skater.4"),
("Tony Hawk's Underground","PS2","PS2",2003,"Sports","Neversoft","THUG","Tony Hawk's","tony.hawks.underground"),
("Tony Hawk's Underground 2","PS2","PS2",2004,"Sports","Neversoft","THUG2","Tony Hawk's","tony.hawks.underground.2"),
("Tony Hawk's American Wasteland","PS2","PS2",2005,"Sports","Neversoft","","Tony Hawk's","tony.hawks.american.wasteland"),
("Tony Hawk's Project 8","PS2","PS2",2006,"Sports","Neversoft","","Tony Hawk's","tony.hawks.project.8"),
("Tony Hawk's Proving Ground","PS2","PS2",2007,"Sports","Neversoft","","Tony Hawk's","tony.hawks.proving.ground"),
("SSX","PS2","PS2",2000,"Sports","EA Canada","","SSX","ssx"),
("SSX Tricky","PS2","PS2",2001,"Sports","EA Canada","","SSX","ssx.tricky"),
("SSX 3","PS2","PS2",2003,"Sports","EA Canada","","SSX","ssx.3"),
("SSX On Tour","PS2","PS2",2005,"Sports","EA Canada","","SSX","ssx.on.tour"),
("SSX Blur","PS2","PS2",2007,"Sports","EA Canada","","SSX","ssx.blur"),
("FIFA 2001","PS2","PS2",2000,"Sports","EA Canada","","FIFA","fifa.2001"),
("FIFA 2002","PS2","PS2",2001,"Sports","EA Canada","","FIFA","fifa.2002"),
("FIFA 2003","PS2","PS2",2002,"Sports","EA Canada","","FIFA","fifa.2003"),
("FIFA 2004","PS2","PS2",2003,"Sports","EA Canada","","FIFA","fifa.2004"),
("FIFA 2005","PS2","PS2",2004,"Sports","EA Canada","","FIFA","fifa.2005"),
("FIFA 06","PS2","PS2",2005,"Sports","EA Canada","","FIFA","fifa.06"),
("FIFA 07","PS2","PS2",2006,"Sports","EA Canada","","FIFA","fifa.07"),
("FIFA 08","PS2","PS2",2007,"Sports","EA Canada","","FIFA","fifa.08"),
("FIFA 09","PS2","PS2",2008,"Sports","EA Canada","","FIFA","fifa.09"),
("FIFA 10","PS2","PS2",2009,"Sports","EA Canada","","FIFA","fifa.10"),
("FIFA 11","PS2","PS2",2010,"Sports","EA Canada","","FIFA","fifa.11"),
("FIFA 12","PS2","PS2",2011,"Sports","EA Canada","","FIFA","fifa.12"),
("FIFA 13","PS2","PS2",2012,"Sports","EA Canada","","FIFA","fifa.13"),
("FIFA 14","PS2","PS2",2013,"Sports","EA Canada","","FIFA","fifa.14"),
("Madden NFL 2001","PS2","PS2",2000,"Sports","EA Tiburon","","Madden NFL","madden.2001"),
("Madden NFL 2002","PS2","PS2",2001,"Sports","EA Tiburon","","Madden NFL","madden.2002"),
("Madden NFL 2003","PS2","PS2",2002,"Sports","EA Tiburon","","Madden NFL","madden.2003"),
("Madden NFL 2004","PS2","PS2",2003,"Sports","EA Tiburon","","Madden NFL","madden.2004"),
("Madden NFL 2005","PS2","PS2",2004,"Sports","EA Tiburon","","Madden NFL","madden.2005"),
("Madden NFL 06","PS2","PS2",2005,"Sports","EA Tiburon","","Madden NFL","madden.06"),
("Madden NFL 07","PS2","PS2",2006,"Sports","EA Tiburon","","Madden NFL","madden.07"),
("Madden NFL 08","PS2","PS2",2007,"Sports","EA Tiburon","","Madden NFL","madden.08"),
("Madden NFL 09","PS2","PS2",2008,"Sports","EA Tiburon","","Madden NFL","madden.09"),
("Madden NFL 10","PS2","PS2",2009,"Sports","EA Tiburon","","Madden NFL","madden.10"),
("Madden NFL 11","PS2","PS2",2010,"Sports","EA Tiburon","","Madden NFL","madden.11"),
("Madden NFL 12","PS2","PS2",2011,"Sports","EA Tiburon","","Madden NFL","madden.12"),
("Madden NFL 13","PS2","PS2",2012,"Sports","EA Tiburon","","Madden NFL","madden.13"),
("NBA 2K1","PS2","PS2",2000,"Sports","Visual Concepts","","NBA 2K","nba.2k1"),
("NBA 2K2","PS2","PS2",2001,"Sports","Visual Concepts","","NBA 2K","nba.2k2"),
("NBA 2K3","PS2","PS2",2002,"Sports","Visual Concepts","","NBA 2K","nba.2k3"),
("NBA 2K4","PS2","PS2",2003,"Sports","Visual Concepts","","NBA 2K","nba.2k4"),
("NBA 2K5","PS2","PS2",2004,"Sports","Visual Concepts","","NBA 2K","nba.2k5"),
("NBA 2K6","PS2","PS2",2005,"Sports","Visual Concepts","","NBA 2K","nba.2k6"),
("NBA 2K7","PS2","PS2",2006,"Sports","Visual Concepts","","NBA 2K","nba.2k7"),
("NBA 2K8","PS2","PS2",2007,"Sports","Visual Concepts","","NBA 2K","nba.2k8"),
("NBA 2K9","PS2","PS2",2008,"Sports","Visual Concepts","","NBA 2K","nba.2k9"),
("NBA 2K10","PS2","PS2",2009,"Sports","Visual Concepts","","NBA 2K","nba.2k10"),
("NBA 2K11","PS2","PS2",2010,"Sports","Visual Concepts","","NBA 2K","nba.2k11"),
("NBA 2K12","PS2","PS2",2011,"Sports","Visual Concepts","","NBA 2K","nba.2k12"),
("NBA 2K13","PS2","PS2",2012,"Sports","Visual Concepts","","NBA 2K","nba.2k13"),
("NBA Live 2001","PS2","PS2",2000,"Sports","EA Canada","","NBA Live","nba.live.2001"),
("NBA Live 2002","PS2","PS2",2001,"Sports","EA Canada","","NBA Live","nba.live.2002"),
("NBA Live 2003","PS2","PS2",2002,"Sports","EA Canada","","NBA Live","nba.live.2003"),
("NBA Live 2004","PS2","PS2",2003,"Sports","EA Canada","","NBA Live","nba.live.2004"),
("NBA Live 2005","PS2","PS2",2004,"Sports","EA Canada","","NBA Live","nba.live.2005"),
("NBA Live 2006","PS2","PS2",2005,"Sports","EA Canada","","NBA Live","nba.live.2006"),
("NHL 2001","PS2","PS2",2000,"Sports","EA Canada","","NHL","nhl.2001"),
("NHL 2002","PS2","PS2",2001,"Sports","EA Canada","","NHL","nhl.2002"),
("NHL 2003","PS2","PS2",2002,"Sports","EA Canada","","NHL","nhl.2003"),
("NHL 2004","PS2","PS2",2003,"Sports","EA Canada","","NHL","nhl.2004"),
("NHL 2005","PS2","PS2",2004,"Sports","EA Canada","","NHL","nhl.2005"),
("NHL 06","PS2","PS2",2005,"Sports","EA Canada","","NHL","nhl.06"),
("NHL 07","PS2","PS2",2006,"Sports","EA Canada","","NHL","nhl.07"),
("NHL 08","PS2","PS2",2007,"Sports","EA Canada","","NHL","nhl.08"),
("NHL 09","PS2","PS2",2008,"Sports","EA Canada","","NHL","nhl.09"),
("NHL 10","PS2","PS2",2009,"Sports","EA Canada","","NHL","nhl.10"),
("NHL 11","PS2","PS2",2010,"Sports","EA Canada","","NHL","nhl.11"),
("NHL 12","PS2","PS2",2011,"Sports","EA Canada","","NHL","nhl.12"),
("NHL 13","PS2","PS2",2012,"Sports","EA Canada","","NHL","nhl.13"),
("Pro Evolution Soccer 3","PS2","PS2",2003,"Sports","Konami","PES 3","Pro Evolution Soccer","pro.evolution.soccer.3|pes.3"),
("Pro Evolution Soccer 4","PS2","PS2",2004,"Sports","Konami","PES 4","Pro Evolution Soccer","pro.evolution.soccer.4|pes.4"),
("Pro Evolution Soccer 5","PS2","PS2",2005,"Sports","Konami","PES 5","Pro Evolution Soccer","pro.evolution.soccer.5|pes.5"),
("Pro Evolution Soccer 6","PS2","PS2",2006,"Sports","Konami","PES 6","Pro Evolution Soccer","pro.evolution.soccer.6|pes.6"),
("Pro Evolution Soccer 2008","PS2","PS2",2007,"Sports","Konami","PES 2008","Pro Evolution Soccer","pro.evolution.soccer.2008|pes.2008"),
("Pro Evolution Soccer 2009","PS2","PS2",2008,"Sports","Konami","PES 2009","Pro Evolution Soccer","pro.evolution.soccer.2009|pes.2009"),
("Pro Evolution Soccer 2010","PS2","PS2",2009,"Sports","Konami","PES 2010","Pro Evolution Soccer","pro.evolution.soccer.2010|pes.2010"),
("Pro Evolution Soccer 2011","PS2","PS2",2010,"Sports","Konami","PES 2011","Pro Evolution Soccer","pro.evolution.soccer.2011|pes.2011"),
("Pro Evolution Soccer 2012","PS2","PS2",2011,"Sports","Konami","PES 2012","Pro Evolution Soccer","pro.evolution.soccer.2012|pes.2012"),
("Pro Evolution Soccer 2013","PS2","PS2",2012,"Sports","Konami","PES 2013","Pro Evolution Soccer","pro.evolution.soccer.2013|pes.2013"),
("Pro Evolution Soccer 2014","PS2","PS2",2013,"Sports","Konami","PES 2014","Pro Evolution Soccer","pro.evolution.soccer.2014|pes.2014"),
("Medal of Honor: Frontline","PS2","PS2",2002,"FPS","EA Los Angeles","","Medal of Honor","medal.of.honor.frontline"),
("Medal of Honor: Rising Sun","PS2","PS2",2003,"FPS","EA Los Angeles","","Medal of Honor","medal.of.honor.rising.sun"),
("Medal of Honor: European Assault","PS2","PS2",2005,"FPS","EA Los Angeles","","Medal of Honor","medal.of.honor.european.assault"),
("Medal of Honor: Vanguard","PS2","PS2",2007,"FPS","EA Los Angeles","","Medal of Honor","medal.of.honor.vanguard"),
("Medal of Honor: Airborne","PS2","PS2",2007,"FPS","EA Los Angeles","","Medal of Honor","medal.of.honor.airborne"),
("Call of Duty","PS2","PS2",2003,"FPS","Infinity Ward","","Call of Duty","call.of.duty|cod"),
("Call of Duty 2: Big Red One","PS2","PS2",2005,"FPS","Treyarch","","Call of Duty","call.of.duty.2.big.red.one"),
("Call of Duty 3","PS2","PS2",2006,"FPS","Treyarch","","Call of Duty","call.of.duty.3"),
("Call of Duty: World at War - Final Fronts","PS2","PS2",2008,"FPS","Rebellion Developments","","Call of Duty","call.of.duty.world.at.war.final.fronts"),
("Call of Duty: Roads to Victory","PS2","PS2",2007,"FPS","Amaze Entertainment","","Call of Duty","call.of.duty.roads.to.victory"),
("Battlefield 2: Modern Combat","PS2","PS2",2005,"FPS","Digital Illusions","","Battlefield","battlefield.2.modern.combat"),
("Battlefield: Bad Company","PS2","PS2",2008,"FPS","DICE","","Battlefield","battlefield.bad.company"),
("TimeSplitters 2","PS2","PS2",2002,"FPS","Free Radical Design","","TimeSplitters","timesplitters.2"),
("TimeSplitters: Future Perfect","PS2","PS2",2005,"FPS","Free Radical Design","","TimeSplitters","timesplitters.future.perfect"),
("Killzone","PS2","PS2",2004,"FPS","Guerrilla Games","","Killzone","killzone"),
("Killzone: Liberation","PS2","PS2",2006,"Third-Person Shooter","Guerrilla Games","","Killzone","killzone.liberation"),
("Killzone 2","PS2","PS2",2009,"FPS","Guerrilla Games","","Killzone","killzone.2"),
("Killzone 3","PS2","PS2",2011,"FPS","Guerrilla Games","","Killzone","killzone.3"),
("Resistance: Fall of Man","PS2","PS2",2006,"FPS","Insomniac Games","","Resistance","resistance.fall.of.man"),
("Resistance 2","PS2","PS2",2008,"FPS","Insomniac Games","","Resistance","resistance.2"),
("Black","PS2","PS2",2006,"FPS","Criterion Games","","Black","black"),
("Halo: Combat Evolved","PS2","PS2",2003,"FPS","Bungie","","Halo","halo|halo.ce|combat.evolved"),
("Halo 2","PS2","PS2",2004,"FPS","Bungie","","Halo","halo.2"),
("Doom 3","PS2","PS2",2004,"FPS","id Software","","Doom","doom.3"),
("Half-Life","PS2","PS2",2001,"FPS","Valve","","Half-Life","half.life"),
("Half-Life 2","PS2","PS2",2004,"FPS","Valve","","Half-Life","half.life.2"),
("Half-Life 2: Episode One","PS2","PS2",2006,"FPS","Valve","","Half-Life","half.life.2.episode.one"),
("Half-Life 2: Episode Two","PS2","PS2",2007,"FPS","Valve","","Half-Life","half.life.2.episode.two"),
("Max Payne","PS2","PS2",2001,"Third-Person Shooter","Remedy Entertainment","","Max Payne","max.payne"),
("Max Payne 2: The Fall of Max Payne","PS2","PS2",2003,"Third-Person Shooter","Remedy Entertainment","","Max Payne","max.payne.2|the.fall.of.max.payne"),
("True Crime: Streets of LA","PS2","PS2",2003,"Action-Adventure","Luxoflux","","True Crime","true.crime.streets.of.la"),
("True Crime: New York City","PS2","PS2",2005,"Action-Adventure","Luxoflux","","True Crime","true.crime.new.york.city"),
("The Simpsons: Hit & Run","PS2","PS2",2003,"Action-Adventure","Radical Entertainment","","The Simpsons","simpsons.hit.and.run"),
("The Bouncer","PS2","PS2",2000,"Beat 'em Up","Square","","The Bouncer","the.bouncer"),
("Viewtiful Joe","PS2","PS2",2003,"Action","Capcom","","Viewtiful Joe","viewtiful.joe"),
("Viewtiful Joe 2","PS2","PS2",2004,"Action","Capcom","","Viewtiful Joe","viewtiful.joe.2"),
("Okami","PS2","PS2",2006,"Action-Adventure","Clover Studio","","Okami","okami"),
("Okami HD","PS2","PS2",2018,"Action-Adventure","Clover Studio","","Okami","okami.hd"),
("Kuon","PS2","PS2",2004,"Survival Horror","FromSoftware","","Kuon","kuon"),
("Siren","PS2","PS2",2003,"Survival Horror","Project Siren","","Siren","siren"),
("Siren 2","PS2","PS2",2006,"Survival Horror","Project Siren","","Siren","siren.2"),
("Rule of Rose","PS2","PS2",2006,"Survival Horror","Punchline","","Rule of Rose","rule.of.rose"),
("Haunting Ground","PS2","PS2",2005,"Survival Horror","Capcom","","Haunting Ground","haunting.ground"),
("Fatal Frame","PS2","PS2",2001,"Survival Horror","Tecmo","","Fatal Frame","fatal.frame"),
("Fatal Frame II: Crimson Butterfly","PS2","PS2",2003,"Survival Horror","Tecmo","","Fatal Frame","fatal.frame.2|crimson.butterfly"),
("Fatal Frame III: The Tormented","PS2","PS2",2005,"Survival Horror","Tecmo","","Fatal Frame","fatal.frame.3|the.tormented"),
("Clock Tower 3","PS2","PS2",2002,"Survival Horror","Capcom","","Clock Tower","clock.tower.3"),
("Silent Hill 2","PS2","PS2",2001,"Survival Horror","Konami","","Silent Hill","silent.hill.2"),
("Silent Hill 3","PS2","PS2",2003,"Survival Horror","Konami","","Silent Hill","silent.hill.3"),
("Silent Hill 4: The Room","PS2","PS2",2004,"Survival Horror","Konami","","Silent Hill","silent.hill.4|the.room"),
("Suikoden III","PS2","PS2",2002,"RPG","Konami","","Suikoden","suikoden.3"),
("Suikoden IV","PS2","PS2",2004,"RPG","Konami","","Suikoden","suikoden.4"),
("Suikoden V","PS2","PS2",2006,"RPG","Konami","","Suikoden","suikoden.5"),
("Disgaea: Hour of Darkness","PS2","PS2",2003,"Tactical RPG","Nippon Ichi Software","","Disgaea","disgaea|hour.of.darkness"),
("Disgaea 2: Cursed Memories","PS2","PS2",2006,"Tactical RPG","Nippon Ichi Software","","Disgaea","disgaea.2|cursed.memories"),
("Disgaea 3: Absence of Justice","PS2","PS2",2008,"Tactical RPG","Nippon Ichi Software","","Disgaea","disgaea.3|absence.of.justice"),
("Final Fantasy Tactics","PS2","PS2",2007,"Tactical RPG","Square Enix","","Final Fantasy","final.fantasy.tactics"),
("Star Ocean: Till the End of Time","PS2","PS2",2003,"RPG","tri-Ace","","Star Ocean","star.ocean.till.the.end.of.time"),
("Tales of the Abyss","PS2","PS2",2005,"RPG","Namco","","Tales","tales.of.the.abyss"),
("Tales of Symphonia","PS2","PS2",2004,"RPG","Namco","","Tales","tales.of.symphonia"),
("Tales of Legendia","PS2","PS2",2005,"RPG","Namco","","Tales","tales.of.legendia"),
("Dark Cloud","PS2","PS2",2000,"Action-RPG","Level-5","","Dark Cloud","dark.cloud"),
("Dark Cloud 2","PS2","PS2",2003,"Action-RPG","Level-5","Dark Chronicle","Dark Cloud","dark.cloud.2|dark.chronicle"),
("Rogue Galaxy","PS2","PS2",2005,"Action-RPG","Level-5","","Rogue Galaxy","rogue.galaxy"),
("Dragon Quest VIII","PS2","PS2",2004,"RPG","Level-5","","Dragon Quest","dragon.quest.8"),
("Persona 3","PS2","PS2",2006,"RPG","Atlus","","Persona","persona.3"),
("Persona 3 FES","PS2","PS2",2007,"RPG","Atlus","","Persona","persona.3.fes"),
("Persona 4","PS2","PS2",2008,"RPG","Atlus","","Persona","persona.4"),
("Persona 3: The Answer","PS2","PS2",2007,"RPG","Atlus","","Persona","persona.3.the.answer"),
("Shin Megami Tensei: Nocturne","PS2","PS2",2003,"RPG","Atlus","Shin Megami Tensei III","Shin Megami Tensei","shin.megami.tensei.nocturne|smt.3"),
("Shin Megami Tensei: Digital Devil Saga","PS2","PS2",2004,"RPG","Atlus","","Shin Megami Tensei","shin.megami.tensei.digital.devil.saga"),
("Shin Megami Tensei: Digital Devil Saga 2","PS2","PS2",2005,"RPG","Atlus","","Shin Megami Tensei","shin.megami.tensei.digital.devil.saga.2"),
("Shin Megami Tensei: Persona 4","PS2","PS2",2008,"RPG","Atlus","","Persona","persona.4"),
("Katamari Damacy","PS2","PS2",2004,"Action","Namco","","Katamari","katamari.damacy"),
("We Love Katamari","PS2","PS2",2005,"Action","Namco","","Katamari","we.love.katamari"),
("Beautiful Katamari","PS2","PS2",2007,"Action","Namco","","Katamari","beautiful.katamari"),
("Bully","PS2","PS2",2006,"Action-Adventure","Rockstar Vancouver","","Bully","bully"),
("Bully: Scholarship Edition","PS2","PS2",2008,"Action-Adventure","Rockstar Vancouver","","Bully","bully.scholarship.edition"),
("Manhunt","PS2","PS2",2003,"Stealth-Action","Rockstar North","","Manhunt","manhunt"),
("Manhunt 2","PS2","PS2",2007,"Stealth-Action","Rockstar London","","Manhunt","manhunt.2"),
("The Warriors","PS2","PS2",2005,"Beat 'em Up","Rockstar Toronto","","The Warriors","warriors"),
("State of Emergency","PS2","PS2",2002,"Action","Rockstar Vancouver","","State of Emergency","state.of.emergency"),
("Destroy All Humans!","PS2","PS2",2005,"Action-Adventure","Pandemic Studios","","Destroy All Humans!","destroy.all.humans"),
("Destroy All Humans! 2","PS2","PS2",2006,"Action-Adventure","Pandemic Studios","","Destroy All Humans!","destroy.all.humans.2"),
("Mercenaries: Playground of Destruction","PS2","PS2",2005,"Action-Adventure","Pandemic Studios","","Mercenaries","mercenaries|playground.of.destruction"),
("Mercenaries 2: World in Flames","PS2","PS2",2008,"Action-Adventure","Pandemic Studios","","Mercenaries","mercenaries.2|world.in.flames"),
("Just Cause","PS2","PS2",2006,"Action-Adventure","Avalanche Studios","","Just Cause","just.cause"),
("Just Cause 2","PS2","PS2",2010,"Action-Adventure","Avalanche Studios","","Just Cause","just.cause.2"),
("Red Faction","PS2","PS2",2001,"FPS","Volition","","Red Faction","red.faction"),
("Red Faction II","PS2","PS2",2002,"FPS","Volition","","Red Faction","red.faction.2"),
("Psi-Ops: The Mindgate Conspiracy","PS2","PS2",2004,"Action-Adventure","Midway","","Psi-Ops","psi.ops|mindgate.conspiracy"),
("Beyond Good & Evil","PS2","PS2",2003,"Action-Adventure","Ubisoft Montpellier","","Beyond Good & Evil","beyond.good.and.evil"),
("Prince of Persia: The Sands of Time","PS2","PS2",2003,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.sands.of.time"),
("Prince of Persia: Warrior Within","PS2","PS2",2004,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.warrior.within"),
("Prince of Persia: The Two Thrones","PS2","PS2",2005,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.two.thrones"),
("Prince of Persia: The Forgotten Sands","PS2","PS2",2010,"Action-Adventure","Ubisoft","","Prince of Persia","prince.of.persia.forgotten.sands"),
("Sphinx and the Cursed Mummy","PS2","PS2",2003,"Action-Adventure","Eurocom","","Sphinx and the Cursed Mummy","sphinx.and.the.cursed.mummy"),
("Rayman 3: Hoodlum Havoc","PS2","PS2",2003,"Platformer","Ubisoft","","Rayman","rayman.3|hoodlum.havoc"),
("Vexx","PS2","PS2",2003,"Platformer","Acclaim Entertainment","","Vexx","vexx"),
("Whiplash","PS2","PS2",2002,"Platformer","Crystal Dynamics","","Whiplash","whiplash"),
("Scaler","PS2","PS2",2004,"Platformer","Artificial Mind and Movement","","Scaler","scaler"),
("Kya: Dark Lineage","PS2","PS2",2003,"Action-Adventure","Etranges Libellules","","Kya: Dark Lineage","kya.dark.lineage"),
("Drakengard","PS2","PS2",2003,"Action-RPG","Cavia","","Drakengard","drakengard"),
("Drakengard 2","PS2","PS2",2005,"Action-RPG","Cavia","","Drakengard","drakengard.2"),
("Gitaroo Man","PS2","PS2",2002,"Rhythm","iNiS","","Gitaroo Man","gitaroo.man"),
("Frequency","PS2","PS2",2001,"Rhythm","Harmonix","","Frequency","frequency"),
("Amplitude","PS2","PS2",2003,"Rhythm","Harmonix","","Amplitude","amplitude"),
("Guitar Hero","PS2","PS2",2005,"Rhythm","Harmonix","","Guitar Hero","guitar.hero"),
("Guitar Hero II","PS2","PS2",2006,"Rhythm","Harmonix","","Guitar Hero","guitar.hero.2"),
("Guitar Hero III: Legends of Rock","PS2","PS2",2007,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.3|legends.of.rock"),
("Guitar Hero: Aerosmith","PS2","PS2",2008,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.aerosmith"),
("Guitar Hero: Metallica","PS2","PS2",2009,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.metallica"),
("Guitar Hero: World Tour","PS2","PS2",2008,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.world.tour"),
("Guitar Hero 5","PS2","PS2",2009,"Rhythm","Neversoft","","Guitar Hero","guitar.hero.5"),
("Rock Band","PS2","PS2",2007,"Rhythm","Harmonix","","Rock Band","rock.band"),
("Rock Band 2","PS2","PS2",2008,"Rhythm","Harmonix","","Rock Band","rock.band.2"),
("SingStar","PS2","PS2",2004,"Rhythm","SCE London Studio","","SingStar","singstar"),
("Dance Dance Revolution: Max","PS2","PS2",2002,"Rhythm","Konami","DDR Max","Dance Dance Revolution","dance.dance.revolution.max|ddr.max"),
("Dance Dance Revolution: Max 2","PS2","PS2",2003,"Rhythm","Konami","DDR Max 2","Dance Dance Revolution","dance.dance.revolution.max.2|ddr.max.2"),
("Dance Dance Revolution: Extreme","PS2","PS2",2004,"Rhythm","Konami","DDR Extreme","Dance Dance Revolution","dance.dance.revolution.extreme|ddr.extreme"),
("Dance Dance Revolution: SuperNOVA","PS2","PS2",2006,"Rhythm","Konami","DDR SuperNOVA","Dance Dance Revolution","dance.dance.revolution.supernova|ddr.supernova"),
("Taiko no Tatsujin","PS2","PS2",2002,"Rhythm","Namco","","Taiko no Tatsujin","taiko.no.tatsujin"),
("Taiko no Tatsujin 2","PS2","PS2",2003,"Rhythm","Namco","","Taiko no Tatsujin","taiko.no.tatsujin.2"),
("Taiko no Tatsujin 3","PS2","PS2",2004,"Rhythm","Namco","","Taiko no Tatsujin","taiko.no.tatsujin.3"),
("Bust-a-Move 4","PS2","PS2",2000,"Puzzle","Taito","","Bust-a-Move","bust.a.move.4"),
("Super Monkey Ball","PS2","PS2",2002,"Platformer","Amusement Vision","","Super Monkey Ball","super.monkey.ball"),
("Super Monkey Ball 2","PS2","PS2",2002,"Platformer","Amusement Vision","","Super Monkey Ball","super.monkey.ball.2"),
("Super Monkey Ball Deluxe","PS2","PS2",2005,"Platformer","Amusement Vision","","Super Monkey Ball","super.monkey.ball.deluxe"),
("Katamari Damacy","PS2","PS2",2004,"Action","Namco","","Katamari","katamari.damacy"),
("Lego Star Wars: The Video Game","PS2","PS2",2005,"Action-Adventure","Traveller's Tales","","LEGO","lego.star.wars"),
("Lego Star Wars II: The Original Trilogy","PS2","PS2",2006,"Action-Adventure","Traveller's Tales","","LEGO","lego.star.wars.2|original.trilogy"),
("Lego Star Wars: The Complete Saga","PS2","PS2",2007,"Action-Adventure","Traveller's Tales","","LEGO","lego.star.wars.complete.saga"),
("Lego Indiana Jones: The Original Adventures","PS2","PS2",2008,"Action-Adventure","Traveller's Tales","","LEGO","lego.indiana.jones"),
("Lego Batman: The Video Game","PS2","PS2",2008,"Action-Adventure","Traveller's Tales","","LEGO","lego.batman"),
("Lego Harry Potter: Years 1-4","PS2","PS2",2010,"Action-Adventure","Traveller's Tales","","LEGO","lego.harry.potter.years.1.4"),
]
batch_add(ps2_games)
print(f"PS2: {len(ps2_games)}")

print(f"Total so far: {len(rows)}")

# Write to CSV
output = r"C:\Coding\Pascal\games_dictionary_part4.csv"
with open(output, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow(row)

print(f"Written {len(rows)} rows to {output}")
