import csv, os

rows = []

def a(t, p, ps, y, g, dev, alt="", series="", folders=""):
    ts = t.lower().replace("'","")
    if not folders:
        folders = ts.replace(": "," ").replace(":"," ").replace(" & "," and ").replace(" - "," ").replace(", "," ").replace("  "," ").strip()
    rows.append([t, ts, p, ps, str(y), g, dev, alt, series, folders])

def ba(games):
    for g in games:
        a(*g)

# Helper to generate numbered sports games
def sports_series(prefix, sport, dev, years, platform="PS2"):
    result = []
    for y in years:
        a(f"{prefix} {y}",platform,platform,y,sport,dev,"",prefix,f"{prefix.lower()}.{y}|{prefix.lower()}{y}")
    return result

# ===================== SEGA GENESIS (300) =====================
gen_games = [
("Sonic the Hedgehog","GEN","GEN",1991,"Platformer","Sonic Team","","Sonic","sonic.the.hedgehog|sonic.1"),
("Sonic the Hedgehog 2","GEN","GEN",1992,"Platformer","Sonic Team","","Sonic","sonic.the.hedgehog.2|sonic.2"),
("Sonic the Hedgehog 3","GEN","GEN",1994,"Platformer","Sonic Team","","Sonic","sonic.the.hedgehog.3|sonic.3"),
("Sonic & Knuckles","GEN","GEN",1994,"Platformer","Sonic Team","","Sonic","sonic.and.knuckles"),
("Sonic Spinball","GEN","GEN",1993,"Pinball","Sonic Team","","Sonic","sonic.spinball"),
("Sonic 3D Blast","GEN","GEN",1996,"Platformer","Traveller's Tales","","Sonic","sonic.3d.blast"),
("Streets of Rage","GEN","GEN",1991,"Beat 'em Up","Sega","","Streets of Rage","streets.of.rage"),
("Streets of Rage 2","GEN","GEN",1992,"Beat 'em Up","Sega","","Streets of Rage","streets.of.rage.2"),
("Streets of Rage 3","GEN","GEN",1994,"Beat 'em Up","Sega","","Streets of Rage","streets.of.rage.3"),
("Phantasy Star IV","GEN","GEN",1993,"RPG","Sega","","Phantasy Star","phantasy.star.4"),
("Phantasy Star II","GEN","GEN",1989,"RPG","Sega","","Phantasy Star","phantasy.star.2"),
("Phantasy Star III","GEN","GEN",1990,"RPG","Sega","","Phantasy Star","phantasy.star.3"),
("Shining Force","GEN","GEN",1992,"Tactical RPG","Sega","","Shining Force","shining.force"),
("Shining Force II","GEN","GEN",1993,"Tactical RPG","Sega","","Shining Force","shining.force.2"),
("Shining in the Darkness","GEN","GEN",1991,"Dungeon RPG","Sega","","Shining","shining.in.the.darkness"),
("Gunstar Heroes","GEN","GEN",1993,"Run and Gun","Treasure","","Gunstar Heroes","gunstar.heroes"),
("Dynamite Headdy","GEN","GEN",1994,"Platformer","Treasure","","Dynamite Headdy","dynamite.headdy"),
("Beyond Oasis","GEN","GEN",1994,"Action-Adventure","Ancient","","Beyond Oasis","beyond.oasis"),
("Story of Thor","GEN","GEN",1994,"Action-Adventure","Ancient","Beyond Oasis","Beyond Oasis","story.of.thor|beyond.oasis"),
("Landstalker","GEN","GEN",1993,"Action-RPG","Climax Entertainment","","Landstalker","landstalker"),
("Shining Force CD","GEN","GEN",1995,"Tactical RPG","Sega","","Shining Force","shining.force.cd"),
("Altered Beast","GEN","GEN",1988,"Beat 'em Up","Sega","","Altered Beast","altered.beast"),
("Golden Axe","GEN","GEN",1989,"Beat 'em Up","Sega","","Golden Axe","golden.axe"),
("Golden Axe II","GEN","GEN",1991,"Beat 'em Up","Sega","","Golden Axe","golden.axe.2"),
("Golden Axe III","GEN","GEN",1993,"Beat 'em Up","Sega","","Golden Axe","golden.axe.3"),
("Revenge of Shinobi","GEN","GEN",1989,"Action-Platformer","Sega","","Shinobi","revenge.of.shinobi"),
("Shinobi III: Return of the Ninja Master","GEN","GEN",1993,"Action-Platformer","Sega","","Shinobi","shinobi.3|return.of.the.ninja.master"),
("Shadow Dancer: The Secret of Shinobi","GEN","GEN",1990,"Action-Platformer","Sega","","Shinobi","shadow.dancer|secret.of.shinobi"),
("Eternal Champions","GEN","GEN",1993,"Fighting","Sega","","Eternal Champions","eternal.champions"),
("Mortal Kombat","GEN","GEN",1993,"Fighting","Midway","","Mortal Kombat","mortal.kombat.gen"),
("Mortal Kombat II","GEN","GEN",1994,"Fighting","Midway","","Mortal Kombat","mortal.kombat.2.gen"),
("Mortal Kombat 3","GEN","GEN",1995,"Fighting","Midway","","Mortal Kombat","mortal.kombat.3.gen"),
("Street Fighter II: Special Champion Edition","GEN","GEN",1993,"Fighting","Capcom","","Street Fighter","street.fighter.2.sce|sf2"),
("Super Street Fighter II","GEN","GEN",1994,"Fighting","Capcom","","Street Fighter","super.street.fighter.2.gen"),
("ToeJam & Earl","GEN","GEN",1991,"Action","Johnson Voorsanger Productions","","ToeJam & Earl","toejam.and.earl"),
("ToeJam & Earl in Panic on Funkotron","GEN","GEN",1993,"Platformer","Johnson Voorsanger Productions","","ToeJam & Earl","toejam.and.earl.panic.on.funkotron"),
("Ecco the Dolphin","GEN","GEN",1992,"Action-Adventure","Novotrade","","Ecco the Dolphin","ecco.the.dolphin"),
("Ecco: The Tides of Time","GEN","GEN",1994,"Action-Adventure","Novotrade","","Ecco the Dolphin","ecco.tides.of.time"),
("Ecco Jr.","GEN","GEN",1995,"Action-Adventure","Novotrade","","Ecco the Dolphin","ecco.jr"),
("Columns","GEN","GEN",1990,"Puzzle","Sega","","Columns","columns"),
("Columns III","GEN","GEN",1993,"Puzzle","Sega","","Columns","columns.3"),
("Dr. Robotnik's Mean Bean Machine","GEN","GEN",1993,"Puzzle","Compile","","Puyo Puyo","dr.robotniks.mean.bean.machine|puyo.puyo"),
("Sonic the Hedgehog CD","SCD","SCD",1993,"Platformer","Sonic Team","","Sonic","sonic.cd|sonic.the.hedgehog.cd"),
("Sonic the Hedgehog 2 CD","SCD","SCD",1993,"Platformer","Sonic Team","","Sonic","sonic.2.cd"),
("Lunar: The Silver Star","SCD","SCD",1992,"RPG","Game Arts","","Lunar","lunar.silver.star|silver.star"),
("Lunar: Eternal Blue","SCD","SCD",1994,"RPG","Game Arts","","Lunar","lunar.eternal.blue"),
("Shining Force CD","SCD","SCD",1993,"Tactical RPG","Sega","","Shining Force","shining.force.cd.scd"),
("Popful Mail","SCD","SCD",1994,"Action-RPG","Falcom","","Popful Mail","popful.mail.scd"),
("Night Trap","SCD","SCD",1992,"Interactive Movie","Digital Pictures","","Night Trap","night.trap"),
("Sewer Shark","SCD","SCD",1992,"Rail Shooter","Digital Pictures","","Sewer Shark","sewer.shark"),
("The Adventures of Batman & Robin","SCD","SCD",1995,"Action","Konami","","Batman","adventures.of.batman.and.robin.scd"),
("Wonder Boy in Monster World","GEN","GEN",1991,"Action-RPG","Westone","","Wonder Boy","wonder.boy.in.monster.world"),
("Wonder Boy in Monster Land","GEN","GEN",1989,"Action-RPG","Westone","","Wonder Boy","wonder.boy.in.monster.land"),
("Monster World IV","GEN","GEN",1994,"Action-RPG","Westone","","Wonder Boy","monster.world.4"),
("Castle of Illusion Starring Mickey Mouse","GEN","GEN",1990,"Platformer","Sega","","Mickey Mouse","castle.of.illusion|mickey.mouse"),
("World of Illusion Starring Mickey Mouse and Donald Duck","GEN","GEN",1992,"Platformer","Sega","","Mickey Mouse","world.of.illusion|mickey.mouse"),
("QuackShot Starring Donald Duck","GEN","GEN",1991,"Platformer","Sega","","Donald Duck","quackshot|donald.duck"),
("DecapAttack","GEN","GEN",1991,"Platformer","Sega","","DecapAttack","decapattack"),
("Comix Zone","GEN","GEN",1995,"Beat 'em Up","Sega","","Comix Zone","comix.zone"),
("Ristar","GEN","GEN",1995,"Platformer","Sega","","Ristar","ristar"),
("VectorMan","GEN","GEN",1995,"Platformer","Tick-Tock Games","","VectorMan","vectorman"),
("VectorMan 2","GEN","GEN",1996,"Platformer","Tick-Tock Games","","VectorMan","vectorman.2"),
("The Lost World: Jurassic Park","GEN","GEN",1997,"Action","Appaloosa Interactive","","Jurassic Park","lost.world.jurassic.park"),
("Jurassic Park","GEN","GEN",1993,"Action","BlueSky Software","","Jurassic Park","jurassic.park.gen"),
("Jurassic Park: Rampage Edition","GEN","GEN",1994,"Action","BlueSky Software","","Jurassic Park","jurassic.park.rampage.edition"),
("Aladdin","GEN","GEN",1993,"Platformer","Virgin Interactive","","Aladdin","aladdin.gen"),
("The Jungle Book","GEN","GEN",1994,"Platformer","Virgin Interactive","","The Jungle Book","jungle.book.gen"),
("Lion King","GEN","GEN",1994,"Platformer","Virgin Interactive","","The Lion King","lion.king.gen"),
("Mickey Mania","GEN","GEN",1994,"Platformer","Traveller's Tales","","Mickey Mouse","mickey.mania.gen"),
("Earthworm Jim","GEN","GEN",1994,"Platformer","Shiny Entertainment","","Earthworm Jim","earthworm.jim.gen"),
("Earthworm Jim 2","GEN","GEN",1995,"Platformer","Shiny Entertainment","","Earthworm Jim","earthworm.jim.2.gen"),
("Joe & Mac","GEN","GEN",1991,"Platformer","Data East","","Joe & Mac","joe.and.mac.gen"),
("Cool Spot","GEN","GEN",1993,"Platformer","Virgin Interactive","","Cool Spot","cool.spot"),
("McDonald's Treasure Land Adventure","GEN","GEN",1993,"Platformer","Treasure","","McDonald's","mcdonalds.treasure.land"),
("Contra: Hard Corps","GEN","GEN",1994,"Run and Gun","Konami","","Contra","contra.hard.corps"),
("Castlevania: Bloodlines","GEN","GEN",1994,"Action-Platformer","Konami","","Castlevania","castlevania.bloodlines"),
("Crusader of Centauri","GEN","GEN",1991,"Shoot 'em Up","Electronic Arts","","Crusader of Centauri","crusader.of.centauri"),
("MUSHA","GEN","GEN",1990,"Shoot 'em Up","Compile","","MUSHA","musha"),
("Truxton","GEN","GEN",1990,"Shoot 'em Up","Taito","","Truxton","truxton"),
("Thunder Force III","GEN","GEN",1993,"Shoot 'em Up","Technosoft","","Thunder Force","thunder.force.3"),
("Thunder Force IV","GEN","GEN",1994,"Shoot 'em Up","Technosoft","","Thunder Force","thunder.force.4"),
("Lightning Force","GEN","GEN",1994,"Shoot 'em Up","Technosoft","Thunder Force IV","Thunder Force","lightning.force|thunder.force.4"),
("Space Harrier II","GEN","GEN",1988,"Shoot 'em Up","Sega","","Space Harrier","space.harrier.2"),
("After Burner II","GEN","GEN",1989,"Flight","Sega","","After Burner","after.burner.2"),
("G-LOC: Air Battle","GEN","GEN",1990,"Flight","Sega","","G-LOC","g.loc|air.battle"),
("Super Hang-On","GEN","GEN",1989,"Racing","Sega","","Hang-On","super.hang.on.gen"),
("Out Run","GEN","GEN",1990,"Racing","Sega","","Out Run","out.run.gen"),
("Super Monaco GP","GEN","GEN",1990,"Racing","Sega","","Super Monaco GP","super.monaco.gp"),
("Super Sprint","GEN","GEN",1992,"Racing","New Generation Software","","Super Sprint","super.sprint"),
("Micro Machines","GEN","GEN",1993,"Racing","Codemasters","","Micro Machines","micro.machines.gen"),
("Micro Machines 2: Turbo Tournament","GEN","GEN",1994,"Racing","Codemasters","","Micro Machines","micro.machines.2"),
("Road Rash","GEN","GEN",1991,"Racing","Electronic Arts","","Road Rash","road.rash.gen"),
("Road Rash II","GEN","GEN",1992,"Racing","Electronic Arts","","Road Rash","road.rash.2.gen"),
("Road Rash 3","GEN","GEN",1995,"Racing","Electronic Arts","","Road Rash","road.rash.3.gen"),
("Madden NFL 94","GEN","GEN",1993,"Sports","Electronic Arts","","Madden NFL","madden.94.gen"),
("Madden NFL 95","GEN","GEN",1994,"Sports","Electronic Arts","","Madden NFL","madden.95.gen"),
("Madden NFL 96","GEN","GEN",1995,"Sports","Electronic Arts","","Madden NFL","madden.96.gen"),
("Madden NFL 97","GEN","GEN",1996,"Sports","Electronic Arts","","Madden NFL","madden.97.gen"),
("Madden NFL 98","GEN","GEN",1997,"Sports","Electronic Arts","","Madden NFL","madden.98.gen"),
("NBA Jam","GEN","GEN",1993,"Sports","Midway","","NBA Jam","nba.jam.gen"),
("NBA Jam Tournament Edition","GEN","GEN",1994,"Sports","Midway","","NBA Jam","nba.jam.te.gen"),
("NFL Football","GEN","GEN",1990,"Sports","Electronic Arts","","NFL","nfl.football"),
("Joe Montana Football","GEN","GEN",1991,"Sports","Electronic Arts","","Joe Montana","joe.montana.football"),
("FIFA International Soccer","GEN","GEN",1994,"Sports","Electronic Arts","","FIFA","fifa.94.gen"),
("FIFA 95","GEN","GEN",1994,"Sports","Electronic Arts","","FIFA","fifa.95.gen"),
("FIFA 96","GEN","GEN",1995,"Sports","Electronic Arts","","FIFA","fifa.96.gen"),
("FIFA 97","GEN","GEN",1996,"Sports","Electronic Arts","","FIFA","fifa.97.gen"),
("FIFA 98","GEN","GEN",1997,"Sports","Electronic Arts","","FIFA","fifa.98.gen"),
("USS Hockey","GEN","GEN",1995,"Sports","Williams","","USS Hockey","uss.hockey"),
("NHL 94","GEN","GEN",1993,"Sports","Electronic Arts","","NHL","nhl.94.gen"),
("NHL 95","GEN","GEN",1994,"Sports","Electronic Arts","","NHL","nhl.95.gen"),
("NHL 96","GEN","GEN",1995,"Sports","Electronic Arts","","NHL","nhl.96.gen"),
("NHL 97","GEN","GEN",1996,"Sports","Electronic Arts","","NHL","nhl.97.gen"),
("NHL 98","GEN","GEN",1997,"Sports","Electronic Arts","","NHL","nhl.98.gen"),
("NHL 99","GEN","GEN",1998,"Sports","Electronic Arts","","NHL","nhl.99.gen"),
("EA Hockey","GEN","GEN",1991,"Sports","Electronic Arts","","EA Hockey","ea.hockey"),
("Tony La Russa Baseball","GEN","GEN",1991,"Sports","Electronic Arts","","Tony La Russa","tony.la.russa.baseball"),
("RBI Baseball 93","GEN","GEN",1992,"Sports","Tengen","","RBI Baseball","rbi.baseball.93"),
("RBI Baseball 94","GEN","GEN",1993,"Sports","Tengen","","RBI Baseball","rbi.baseball.94"),
("Tommy Lasorda Baseball","GEN","GEN",1989,"Sports","Sega","","Tommy Lasorda","tommy.lasorda.baseball"),
("Super Baseball 2020","GEN","GEN",1991,"Sports","Electro Brain","","Super Baseball","super.baseball.2020"),
("Pat Riley Basketball","GEN","GEN",1990,"Sports","Sega","","Pat Riley","pat.riley.basketball"),
("Arnold Palmer Tournament Golf","GEN","GEN",1989,"Sports","Electronic Arts","","Golf","arnold.palmer.tournament.golf"),
("The Games: Summer Challenge","GEN","GEN",1992,"Sports","Electronic Arts","","The Games","games.summer.challenge"),
("The Games: Winter Challenge","GEN","GEN",1992,"Sports","Electronic Arts","","The Games","games.winter.challenge"),
("Olympic Gold","GEN","GEN",1992,"Sports","U.S. Gold","","Olympic Gold","olympic.gold"),
("California Games","GEN","GEN",1991,"Sports","Epyx","","California Games","california.games.gen"),
("California Games II","GEN","GEN",1993,"Sports","Epyx","","California Games","california.games.2.gen"),
("James Buster Douglas Boxing","GEN","GEN",1990,"Sports","Taito","","Boxing","james.buster.douglas.boxing"),
("Evander Holyfield's Real Deal Boxing","GEN","GEN",1992,"Sports","ACLC","","Boxing","evander.holyfield.boxing"),
("George Foreman's KO Boxing","GEN","GEN",1992,"Sports","Software Creations","","Boxing","george.foreman.ko.boxing"),
("Heavyweight Champ","GEN","GEN",1991,"Sports","Sega","","Boxing","heavyweight.champ"),
("Champions World Class Soccer","GEN","GEN",1993,"Sports","Tiertex","","Soccer","champions.world.class.soccer"),
("World Cup Italia 90","GEN","GEN",1990,"Sports","Sega","","World Cup","world.cup.italia.90"),
("Super Sidekicks","GEN","GEN",1993,"Sports","SNK","","Super Sidekicks","super.sidekicks"),
("Super Kick Off","GEN","GEN",1992,"Sports","Tiertex","","Kick Off","super.kick.off"),
("FIFA Soccer 96","GEN","GEN",1995,"Sports","Electronic Arts","","FIFA","fifa.96.gen"),
("Strider","GEN","GEN",1990,"Action-Platformer","Sega","","Strider","strider.gen"),
("Captain America and the Avengers","GEN","GEN",1991,"Beat 'em Up","Data East","","Captain America","captain.america.gen"),
("Spider-Man: vs. The Kingpin","GEN","GEN",1991,"Action","Sega","","Spider-Man","spider.man.vs.the.kingpin"),
("X-Men","GEN","GEN",1993,"Action","Sega","","X-Men","xmen.gen"),
("Batman Returns","GEN","GEN",1992,"Beat 'em Up","Sega","","Batman","batman.returns.gen"),
("Batman Forever","GEN","GEN",1995,"Beat 'em Up","Acclaim","","Batman","batman.forever.gen"),
("The Amazing Spider-Man vs. The Kingpin","GEN","GEN",1990,"Action","Sega","","Spider-Man","amazing.spider.man.vs.kingpin"),
("T2: The Arcade Game","GEN","GEN",1993,"Shoot 'em Up","Midway","","Terminator","t2.arcade.game.gen"),
("RoboCop vs. Terminator","GEN","GEN",1993,"Action","Interplay","","Robocop","robocop.vs.terminator"),
("SubTerrania","GEN","GEN",1993,"Shoot 'em Up","Zyrinx","","SubTerrania","subterrania"),
("Gauntlet IV","GEN","GEN",1993,"Action","Tengen","","Gauntlet","gauntlet.4"),
("Dungeons & Dragons: Warriors of the Eternal Sun","GEN","GEN",1992,"RPG","Westwood Studios","","Dungeons & Dragons","dungeons.and.dragons.warriors.of.the.eternal.sun"),
("Shadowrun","GEN","GEN",1994,"RPG","BlueSky Software","","Shadowrun","shadowrun.gen"),
("Buck Rogers: Countdown to Doomsday","GEN","GEN",1990,"RPG","Strategic Simulations","","Buck Rogers","buck.rogers.countdown.to.doomsday"),
("Might and Magic III","GEN","GEN",1991,"RPG","New World Computing","","Might and Magic","might.and.magic.3"),
(" Rings of Power","GEN","GEN",1992,"RPG","Electronic Arts","","Rings of Power","rings.of.power"),
("Starflight","GEN","GEN",1991,"RPG","Binary Systems","","Starflight","starflight.gen"),
("Herzog Zwei","GEN","GEN",1989,"Strategy","Technosoft","","Herzog Zwei","herzog.zwei"),
("M.U.L.E.","GEN","GEN",1990,"Strategy","Electronic Arts","","M.U.L.E.","mule"),
("VGA Planets","GEN","GEN",1993,"Strategy","VGA Planets","","VGA Planets","vga.planets"),
("General Chaos","GEN","GEN",1993,"Strategy","Electronic Arts","","General Chaos","general.chaos"),
("King's Bounty","GEN","GEN",1991,"Strategy","New World Computing","","King's Bounty","kings.bounty"),
("Populous","GEN","GEN",1990,"Strategy","Bullfrog Productions","","Populous","populous.gen"),
("Syndicate","GEN","GEN",1993,"Strategy","Bullfrog Productions","","Syndicate","syndicate.gen"),
("The Chaos Engine","GEN","GEN",1993,"Run and Gun","The Bitmap Brothers","","The Chaos Engine","chaos.engine"),
("Zombies Ate My Neighbors (GEN)","GEN","GEN",1993,"Run and Gun","Lucasfilm Games","","Zombies Ate My Neighbors","zombies.ate.my.neighbors.gen"),
("Batman (GEN)","GEN","GEN",1990,"Action-Platformer","Sunsoft","","Batman","batman.gen"),
("Dick Tracy (GEN)","GEN","GEN",1990,"Action","Sega","","Dick Tracy","dick.tracy.gen"),
("The Revenge of Shinobi (GEN)","GEN","GEN",1989,"Action-Platformer","Sega","","Shinobi","revenge.of.shinobi.gen"),
("Super Street Fighter II (GEN)","GEN","GEN",1994,"Fighting","Capcom","","Street Fighter","super.street.fighter.2.gen"),
("Fatal Fury 2","GEN","GEN",1994,"Fighting","SNK","","Fatal Fury","fatal.fury.2"),
("Art of Fighting","GEN","GEN",1993,"Fighting","SNK","","Art of Fighting","art.of.fighting"),
("Samurai Shodown","GEN","GEN",1994,"Fighting","SNK","","Samurai Shodown","samurai.shodown"),
("World Heroes","GEN","GEN",1993,"Fighting","SNK","","World Heroes","world.heroes"),
("World Heroes 2","GEN","GEN",1994,"Fighting","SNK","","World Heroes","world.heroes.2"),
("Battletoads & Double Dragon (GEN)","GEN","GEN",1993,"Beat 'em Up","Rare","","Battletoads","battletoads.double.dragon.gen"),
("Double Dragon 3 (GEN)","GEN","GEN",1992,"Beat 'em Up","Technos Japan","","Double Dragon","double.dragon.3.gen"),
("Final Fight (GEN)","GEN","GEN",1994,"Beat 'em Up","Capcom","","Final Fight","final.fight.gen"),
("Streets of Rage (GEN)","GEN","GEN",1991,"Beat 'em Up","Sega","","Streets of Rage","streets.of.rage.gen"),
("Wonder Boy (GEN)","GEN","GEN",1987,"Platformer","Sega","","Wonder Boy","wonder.boy.gen"),
("Alex Kidd in the Enchanted Castle","GEN","GEN",1989,"Platformer","Sega","","Alex Kidd","alex.kidd.in.the.enchanted.castle"),
("Alex Kidd: The Lost Stars","GEN","GEN",1988,"Platformer","Sega","","Alex Kidd","alex.kidd.the.lost.stars"),
("The Super Shinobi","GEN","GEN",1990,"Action-Platformer","Sega","","Shinobi","super.shinobi"),
("Shadow Dancer (GEN)","GEN","GEN",1990,"Action-Platformer","Sega","","Shinobi","shadow.dancer.gen"),
("Gain Ground","GEN","GEN",1991,"Action","Sega","","Gain Ground","gain.ground"),
("Mega Bomberman (GEN)","GEN","GEN",1993,"Action","Hudson Soft","","Bomberman","mega.bomberman"),
("Wario's Woods (GEN)","GEN","GEN",1994,"Puzzle","Nintendo","","Wario","warios.woods.gen"),
("Columns (GEN)","GEN","GEN",1990,"Puzzle","Sega","","Columns","columns.gen"),
("Dr. Robotnik's Mean Bean Machine (GEN)","GEN","GEN",1993,"Puzzle","Compile","","Puyo Puyo","dr.robotniks.mean.bean.machine.gen"),
("Klax (GEN)","GEN","GEN",1991,"Puzzle","Atari Games","","Klax","klax.gen"),
("Tetris (GEN)","GEN","GEN",1990,"Puzzle","Sega","","Tetris","tetris.gen"),
("Sega Tetris","GEN","GEN",1990,"Puzzle","Sega","","Tetris","sega.tetris"),
("Flashback (GEN)","GEN","GEN",1992,"Action-Platformer","Delphine Software","","Flashback","flashback.gen"),
("Out of This World (GEN)","GEN","GEN",1992,"Action-Platformer","Delphine Software","","Another World","out.of.this.world.gen|another.world"),
("Prince of Persia (GEN)","GEN","GEN",1990,"Action-Platformer","Sega","","Prince of Persia","prince.of.persia.gen"),
("Lemmings (GEN)","GEN","GEN",1992,"Puzzle","DMA Design","","Lemmings","lemmings.gen"),
("The Lost Vikings (GEN)","GEN","GEN",1993,"Puzzle-Platformer","Blizzard","","The Lost Vikings","lost.vikings.gen"),
("Michael Jackson's Moonwalker","GEN","GEN",1990,"Action","Sega","","Michael Jackson","moonwalker|michael.jackson.moonwalker"),
("Road Rash (GEN)","GEN","GEN",1991,"Racing","Electronic Arts","","Road Rash","road.rash.gen"),
]
ba(gen_games)
print(f"GEN: {len(gen_games)}")

# ===================== DREAMCAST (100) =====================
dc_games = [
("Shenmue","DC","DC",1999,"Action-Adventure","Sega AM2","","Shenmue","shenmue"),
("Shenmue II","DC","DC",2001,"Action-Adventure","Sega AM2","","Shenmue","shenmue.2"),
("Soulcalibur","DC","DC",1999,"Fighting","Namco","","Soulcalibur","soulcalibur"),
("Sonic Adventure","DC","DC",1998,"Platformer","Sonic Team","","Sonic","sonic.adventure"),
("Sonic Adventure 2","DC","DC",2001,"Platformer","Sonic Team","","Sonic","sonic.adventure.2"),
("Crazy Taxi","DC","DC",1999,"Racing","Hitmaker","","Crazy Taxi","crazy.taxi"),
("Crazy Taxi 2","DC","DC",2001,"Racing","Hitmaker","","Crazy Taxi","crazy.taxi.2"),
("Jet Set Radio","DC","DC",2000,"Action","Smilebit","","Jet Set Radio","jet.set.radio"),
("Space Channel 5","DC","DC",1999,"Rhythm","United Game Artists","","Space Channel 5","space.channel.5.dc"),
("Skies of Arcadia","DC","DC",2000,"RPG","Overworks","","Skies of Arcadia","skies.of.arcadia"),
("Power Stone","DC","DC",1999,"Fighting","Capcom","","Power Stone","power.stone"),
("Power Stone 2","DC","DC",2000,"Fighting","Capcom","","Power Stone","power.stone.2"),
("Marvel vs. Capcom 2: New Age of Heroes","DC","DC",2000,"Fighting","Capcom","MvC2","Marvel vs. Capcom","marvel.vs.capcom.2.dc|mvc2"),
("Street Fighter III: 3rd Strike","DC","DC",2000,"Fighting","Capcom","","Street Fighter","street.fighter.3.3rd.strike.dc"),
("Street Fighter Alpha 3","DC","DC",1999,"Fighting","Capcom","","Street Fighter","street.fighter.alpha.3.dc"),
("Virtua Fighter 3tb","DC","DC",1998,"Fighting","Sega AM2","","Virtua Fighter","virtua.fighter.3tb"),
("Dead or Alive 2","DC","DC",2000,"Fighting","Team Ninja","","Dead or Alive","dead.or.alive.2.dc"),
("Resident Evil: Code Veronica","DC","DC",2000,"Survival Horror","Capcom","","Resident Evil","resident.evil.code.veronica.dc"),
("Dino Crisis","DC","DC",1999,"Survival Horror","Capcom","","Dino Crisis","dino.crisis.dc"),
("Grandia II","DC","DC",2000,"RPG","Game Arts","","Grandia","grandia.2.dc"),
("Phantasy Star Online","DC","DC",2000,"RPG","Sonic Team","","Phantasy Star","phantasy.star.online.dc"),
("Phantasy Star Online Ver. 2","DC","DC",2001,"RPG","Sonic Team","","Phantasy Star","phantasy.star.online.ver.2"),
("ChuChu Rocket!","DC","DC",1999,"Puzzle","Sonic Team","","ChuChu Rocket!","chuchu.rocket.dc"),
("Samba de Amigo","DC","DC",2000,"Rhythm","Sonic Team","","Samba de Amigo","samba.de.amigo"),
("Seaman","DC","DC",1999,"Simulation","Vivarium","","Seaman","seaman"),
("Typing of the Dead","DC","DC",2000,"Shooter","Sega","","The House of the Dead","typing.of.the.dead"),
("House of the Dead 2","DC","DC",1999,"Rail Shooter","Sega","","House of the Dead","house.of.the.dead.2.dc"),
("Virtua Tennis","DC","DC",2000,"Sports","Hitmaker","","Virtua Tennis","virtua.tennis"),
("Virtua Tennis 2","DC","DC",2001,"Sports","Hitmaker","","Virtua Tennis","virtua.tennis.2"),
("NFL 2K","DC","DC",1999,"Sports","Visual Concepts","","NFL 2K","nfl.2k"),
("NFL 2K1","DC","DC",2000,"Sports","Visual Concepts","","NFL 2K","nfl.2k1"),
("NBA 2K","DC","DC",1999,"Sports","Visual Concepts","","NBA 2K","nba.2k.dc"),
("NBA 2K1","DC","DC",2000,"Sports","Visual Concepts","","NBA 2K","nba.2k1.dc"),
("NBA 2K2","DC","DC",2001,"Sports","Visual Concepts","","NBA 2K","nba.2k2.dc"),
("MLB 2K","DC","DC",2000,"Sports","Visual Concepts","","MLB 2K","mlb.2k.dc"),
("NHL 2K","DC","DC",1999,"Sports","Visual Concepts","","NHL 2K","nhl.2k.dc"),
("Rayman 2: The Great Escape","DC","DC",1999,"Platformer","Ubisoft","","Rayman","rayman.2.dc"),
("Tomb Raider: The Last Revelation","DC","DC",1999,"Action-Adventure","Core Design","","Tomb Raider","tomb.raider.last.revelation.dc"),
("MDK 2","DC","DC",2000,"Third-Person Shooter","BioWare","","MDK","mdk.2.dc"),
("Quake III Arena","DC","DC",2000,"FPS","id Software","","Quake","quake.3.arena.dc"),
("Unreal Tournament","DC","DC",2000,"FPS","Epic Games","","Unreal Tournament","unreal.tournament.dc"),
("Half-Life","DC","DC",2001,"FPS","Valve","","Half-Life","half.life.dc"),
("Doom 64","DC","DC",1998,"FPS","Midway","","Doom","doom.64.dc"),
("Ecco the Dolphin: Defender of the Future","DC","DC",2000,"Action-Adventure","Appaloosa Interactive","","Ecco the Dolphin","ecco.the.dolphin.defender.of.the.future"),
("Blue Stinger","DC","DC",1999,"Action-Adventure","Climax Graphics","","Blue Stinger","blue.stinger"),
("Illbleed","DC","DC",2001,"Survival Horror","Climax Graphics","","Illbleed","illbleed"),
("Carrier","DC","DC",2000,"Survival Horror","Jaleco","","Carrier","carrier"),
("Record of Lodoss War","DC","DC",2000,"Action-RPG","Neverland","","Record of Lodoss War","record.of.lodoss.war"),
("Elemental Gimmick Gear","DC","DC",1999,"Action-RPG","Hudson Soft","","Elemental Gimmick Gear","elemental.gimmick.gear"),
("Silver","DC","DC",1999,"RPG","Climax Entertainment","","Silver","silver"),
("Evolution: The World of Sacred Device","DC","DC",1999,"RPG","Sting Entertainment","","Evolution","evolution"),
("Evolution 2: Far Off Promise","DC","DC",2000,"RPG","Sting Entertainment","","Evolution","evolution.2"),
("Super Runabout","DC","DC",2000,"Racing","Climax Entertainment","","Super Runabout","super.runabout"),
("Metropolis Street Racer","DC","DC",2000,"Racing","Bizarre Creations","","Metropolis Street Racer","metropolis.street.racer"),
("Tokyo Extreme Racer","DC","DC",1999,"Racing","Genki","","Tokyo Extreme Racer","tokyo.extreme.racer"),
("Tokyo Extreme Racer 2","DC","DC",2000,"Racing","Genki","","Tokyo Extreme Racer","tokyo.extreme.racer.2"),
("Speed Devils","DC","DC",1999,"Racing","Ubisoft","","Speed Devils","speed.devils"),
("Hydro Thunder","DC","DC",1999,"Racing","Midway","","Hydro Thunder","hydro.thunder.dc"),
("San Francisco Rush 2049","DC","DC",1999,"Racing","Midway","","Rush","rush.2049.dc"),
("4 Wheel Thunder","DC","DC",2000,"Racing","Midway","","4 Wheel Thunder","4.wheel.thunder"),
("Demolition Racer","DC","DC",1999,"Racing","Pitbull Syndicate","","Demolition Racer","demolition.racer"),
("Fur Fighters","DC","DC",2000,"Action","Bizarre Creations","","Fur Fighters","fur.fighters"),
("Toy Commander","DC","DC",1999,"Action","No Cliché","","Toy Commander","toy.commander"),
("Bomberman Online","DC","DC",2001,"Action","Hudson Soft","","Bomberman","bomberman.online"),
("Super Magnetic Neo","DC","DC",2000,"Platformer","Genki","","Super Magnetic Neo","super.magnetic.neo"),
("Tech Romancer","DC","DC",2000,"Action","Capcom","","Tech Romancer","tech.romancer"),
("Bangai-O","DC","DC",1999,"Shoot 'em Up","Treasure","","Bangai-O","bangai.o.dc"),
("Giga Wing","DC","DC",1999,"Shoot 'em Up","Capcom","","Giga Wing","giga.wing"),
("Giga Wing 2","DC","DC",2000,"Shoot 'em Up","Capcom","","Giga Wing","giga.wing.2"),
("Mars Matrix","DC","DC",2000,"Shoot 'em Up","Takumi","","Mars Matrix","mars.matrix"),
("Zero Gunner 2","DC","DC",2001,"Shoot 'em Up","Psikyo","","Zero Gunner","zero.gunner.2"),
("Cannon Spike","DC","DC",2000,"Action","Psikyo","","Cannon Spike","cannon.spike"),
("Spawn: In the Demon's Hand","DC","DC",2000,"Action","Capcom","","Spawn","spawn.in.the.demons.hand"),
("Guilty Gear X","DC","DC",2000,"Fighting","Arc System Works","","Guilty Gear","guilty.gear.x.dc"),
("Last Blade 2","DC","DC",2000,"Fighting","SNK","","Last Blade","last.blade.2.dc"),
("Fatal Fury: Mark of the Wolves","DC","DC",2001,"Fighting","SNK","","Fatal Fury","fatal.fury.mark.of.the.wolves.dc"),
]
ba(dc_games)
print(f"DC: {len(dc_games)}")

print(f"Total so far: {len(rows)}")

output = r"C:\Coding\Pascal\games_dictionary_part4.csv"
mode = 'a' if os.path.exists(output) else 'w'
with open(output, mode, newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow(row)
print(f"Appended {len(rows)} rows to {output}")
